### ISSUE TITLE
error object in case of a "state" parameter mismatch does not get populated correctly

### ISSUE THREAD

**Issue by tumata** [openid/AppAuth-iOS#103]
In OIDAuthorizationService.m, when there is a “state” parameter mismatch between authorizationRequest and authorizationResponse, the generated error is not populated with the right information. (Line 115 to 145)
Also, the OAuth 2 response is “valid” regardless of the state parameter so it makes sense to create the response object before checking for the state parameter.

Attached is my proposal.
[OIDAuthorizationService.m.zip](https://github.com/openid/AppAuth-iOS/files/883248/OIDAuthorizationService.m.zip)

**Comment by WilliamDenniss** [comment]
Can you send your proposal as a Github Pull request? Make sure you e-sign the [CLA](https://github.com/openid/AppAuth-iOS/blob/master/CONTRIBUTING.md) first so we can merge it.

**Comment by tumata** [comment]
I am getting an Authentication Fail: "You may not have permission to access AppAuth-iOS.". (Trying to make a pull request from GitHub Desktop). Know what could be the issue here?
I am confident I signed the documents a couple weeks ago.
