### ISSUE TITLE
Encoding the _needsTokenRefresh flag

### ISSUE THREAD

**Issue by chrismcs** [openid/AppAuth-iOS#104]
This is part question / part suggestion.  

I've got an app that is migrating from GTMOAuth2 to the latest GTMAppAuth framework.  As part of that, there are "keychain migration" helper methods to read in the serialized authentication class from the old keychain entry to the new one.  

In `GTMOAuth2KeychainCompatibility`, after instantiating the OIDAuthState from the old keychain entry, it has this:

```
// We're not serializing the token expiry date, so the first refresh needs to be forced.
[authState setNeedsTokenRefresh];

```

But the problem is right after it creates our OIDAuthState from there, it immediately serializes it into the keychain before it ever actually does the token refresh.  And since the token expiration date wasn't serialized in the old keychain entry, we now have serialized an OIDAuthState with no expiration date **and** it doesn't know that it needs to refresh itself - so when we try to use it next time, it fails (because it is expired) yet with a nil expiration date, it doesn't know that it needs to refresh.

So I've added this to `encodeWithCoder`:

```
//this line lives at the top with all the other constants...
static NSString *const kNeedsRefreshTokenKey = @"_needsTokenRefresh";

...

//this is at the end of encodeWithCoder
if(_needsTokenRefresh)
	  [aCoder encodeObject:@(1) forKey:kNeedsRefreshTokenKey];
```

and then, of course, I read that back in on `initWithCoder` and that seems to solve my problem.  

Can you think of any reason why this would be a bad idea?

**Comment by chrismcs** [comment]
Barring some underlying issue that I can't think of - this seems like it would be a useful change for others as well (specifically when upgrading from `GTMOAuth2`, but perhaps other situations where you have an `OIDAuthState` object with _needsTokenRefresh set to YES and it gets serialized before it actually does the refresh).  

I'm happy to make it a pull request if you agree.

**Comment by WilliamDenniss** [comment]
+1, agree that this would be useful. Object could be serialized at any time, including before token refresh as happens during that migration.

Please send through a PR! Make sure you've e-signed the [CLA](https://github.com/openid/AppAuth-iOS/blob/master/CONTRIBUTING.md) first.
