### ISSUE TITLE
Regression: Exception when deserializing migrated GTMOAuth2 objects

### ISSUE THREAD

**Issue by chrismcs** [openid/AppAuth-iOS#105]
This is due to a recent change made in #99 

I'm relatively new to AppAuth and GTMAppAuth, so it's very possible I'm misunderstanding how something should be working here - but here's what I'm seeing.

As part of #99 - if you now attempt to init an `OIDAuthorizationRequest` with a response type of `token`, an exception is thrown.  The problem is that GMTOAuth2 apparently used to use `token` as a response type, therefore a couple (related) things now break:

1.  An exception is thrown when merely deserializing a stored OIDAuthorizationRequest that was set to `token` as the response type

2.  https://github.com/google/GTMAppAuth - in the `GTMOAuth2KeychainCompatibility.m`, when they are deserializing the old keychain entry to migrate it to a new one, they explicitly use `token` as the response type in `authorizeFromPersistenceString:serviceProvider:tokenURL:redirectURI:clientID:clientSecret:`.  

3.  Even after I do the migration (by commenting out the change in #99), the problem seems to be that `OIDAuthState` stores a request/response history, so `_lastAuthorizationResponse` is set to be a `token` response.  So, if I make the changes for #99 live again, it will still throw the exception every time it grabs the new authorization object that is stored in the keychain.

So, should the changes in #99 be modified to not crash when deserializing an `OIDAuthorizationRequest` or is there some other way to handle this?

**Comment by mike-ferenduros** [comment]
+1
This makes the recommended migration path to app auth unusable.

**Comment by StevenEWright** [comment]
I'm just seeing this now. Wow. We'll get right on this.

**Comment by StevenEWright** [comment]
Also, @chrismcs thank you for the excellent problem summary.

**Comment by StevenEWright** [comment]
@WilliamDenniss I sat down to work on this, and realized it's not as simple as "we made a mistake". Can you comment on the progeny of this issue? It actually looks like this is WAI?

See: https://github.com/openid/AppAuth-iOS/issues/98

**Comment by StevenEWright** [comment]
The related error in GTMAppAuth is: https://github.com/google/GTMAppAuth/issues/35

**Comment by StevenEWright** [comment]
Thanks for the fast review, @WilliamDenniss 
Thanks for the problem report, @chrismcs
