### ISSUE TITLE
`startHTTPListener` crashes on a macOS app written in Swift

### ISSUE THREAD

**Issue by danielmartinprieto** [openid/AppAuth-iOS#107]
Hi. I'm having problems using AppAuth in a Swift macOS app.

I'm using Carthage as dependency manager and the integration seems to work as expected.

When I try to start the HTTP listener, I observe two different (related) issues. When I run this code:
```swift
let successURL = URL(string: "https://openid.github.io/AppAuth-iOS/redirect/")!
self.redirectHTTPHandler = OIDRedirectHTTPHandler(successURL: successURL)
let redirectURI = redirectHTTPHandler?.startHTTPListener(nil) // This line makes the app crash
```
I get this logged in the console: `CFSocketSetAddress bind failure: 1`, and then a crash in the last line of the snippet above.

I don't know why the server cannot be started in the first place, it seems to fail [here](https://github.com/openid/AppAuth-iOS/blob/b06a6bfcbf88ef6e24485f7d53c9c6af9ef17a84/Source/macOS/LoopbackHTTPServer/OIDLoopbackHTTPServer.m#L508), but I don't know why, and I think the crash after is due to the fact that the function `startHTTPListener` of `OIDRedirectHTTPHandler` is imported to Swift like this:
```swift
/*! @brief Starts listening on the loopback interface on a random available port, and returns a URL
            with the base address. Use the returned redirect URI to build an @c OIDAuthorizationRequest,
            and once you initiate the request, set the resulting @c OIDAuthorizationFlowSession to
            @c currentAuthorizationFlow so the response can be handled.
        @param error The error if an error occurred while starting the local HTTP server.
        @return The URL containing the address of the server with the randomly assigned available port.
        @discussion Each instance of @c OIDRedirectHTTPHandler can only listen for a single
            authorization response. Calling this more than once will result in the previous listener
            being cancelled (equivalent of @c cancelHTTPListener being called).
*/
open func startHTTPListener(_ error: NSErrorPointer) -> URL
```
and it should return `URL?` instead, right?

Thanks for your help.

**Comment by danielmartinprieto** [comment]
I've tried adding the library to a brand new project (also macOS in Swift) and the http listener starts (and therefore the app doesn't crash after). I also made a test accessing the library from Objective-C code (which I know it's not necessary) in my app, and obviously it doesn't crash, but the http listener doesn't start either, and I get the same output in the console: `CFSocketSetAddress bind failure: 1` and a `nil` redirect URI.

I guess there is something in my project (which isn't new) that's messing around with this, but I can't understand what. I can't find any useful info about this "bind failure" problem.

Does someone have any clue about what could be happening?

Thanks.

**Comment by WilliamDenniss** [comment]
Does the Objective-C macOS sample work for you?

**Comment by danielmartinprieto** [comment]
I have to check that, but probably it does, because it did in a brand new project I created to test the library.

**Comment by WilliamDenniss** [comment]
Can you provide a sample to reproduce this bug?

**Comment by danielmartinprieto** [comment]
Unfortunately I can't, the project where the problem happens belongs to a client. I've tried to reproduce the issue in a brand new project in Swift but it didn't happen. I've carefully checked the project where I experienced  it, looking for places where something could affect the proper functioning of AppAuth but it's pretty straightforward code, nothing special, mostly UI stuff, and I've followed the guides closely, and checked the examples. I've even written that part in Objective C, as I commented above, in case Swift itself was the problem, but I had the same error.

**Comment by StevenEWright** [comment]
Would it be possible for you to provide the crash dump along with your project's build settings?

**Comment by apparentsoft** [comment]
@danielmartinprieto If your app is sandboxed, you need to set a server entitlement for your app

**Comment by danielmartinprieto** [comment]
@apparentsoft thanks! I just wanted to confirm that this fixed my issue.
