### ISSUE TITLE
Manual Enable Safari 

### ISSUE THREAD

**Issue by ebainto** [openid/AppAuth-iOS#108]
Hi,
Since SFSafariViewController cant share session cookies. i need to disable manually (or switch) SFSafariViewController to Safari across ios version. thank you in advance.

**Comment by WilliamDenniss** [comment]
You could easily hack this by modifying OIDAuthorizationUICoordinatorIOS.m.  To do it properly, create your own instance of `OIDAuthorizationUICoordinator` (i.e. by copying and renaming`OIDAuthorizationUICoordinatorIOS.h` and `OIDAuthorizationUICoordinatorIOS.m`). Your implementation would only use Safari. 

Then, use your coordinator like:
```
  YourUICoordinatorIOS *coordinator = [[YourUICoordinatorIOS alloc] init];
  return [OIDAuthorizationService presentAuthorizationRequest:request UICoordinator:coordinator callback:callback];
 ```

**Comment by ebainto** [comment]
Thanks William...

**Comment by fukemy** [comment]
@ebainto hi buddy, i facing same issue about shareing  cookies, can u help?
