### ISSUE TITLE
Can't specify release 0.9.0 in Podfile for iOS use

### ISSUE THREAD

**Issue by markkelsallaw** [openid/AppAuth-iOS#110]
Hi guys,

Implemented AppAuth on 0.7.0 initially (but not specifying a version) on iOS. Everything worked hunky dory except with an issue we found on our back end which meant we had to put in a workaround for the time being in the source for ignoring challenges.
Finally got the backend fixed but now when I `pod install` again, Xcode complains saying that it can't build and seems to be in reference to https://github.com/openid/AppAuth-iOS/commit/ffcf3244736dd034fd4e3e4bfc299df30316f605

So tried to specify 0.9.0 in my Podfile but for some reason, it says that that version isn't available. Any thoughts/ideas as to why? I'm a bit new to all this so would still appreciate it if some points out that I've missed something glaringly obvious!

```
source "https://github.com/CocoaPods/Old-Specs"

target 'MyApp' do
    pod 'CocoaLumberjack'
    pod 'SCConfiguration'
    pod 'AppAuth', '0.9.0'
    pod 'KeychainItemWrapper'
end
```

If I do 

```
source "https://github.com/CocoaPods/Old-Specs"

target 'MyApp' do
    pod 'CocoaLumberjack'
    pod 'SCConfiguration'
    pod 'AppAuth', :git => 'https://github.com/openid/AppAuth-iOS.git', :tag => '0.9.0'
    pod 'KeychainItemWrapper'
end
```

then it seems to work, however I noticed that my Podfile.lock file specifies it at 0.8.0 based on when I do `pod install --repo-update` these are the logs I get:

```Re-creating CocoaPods due to major version update.
Updating local specs repositories
  $ /usr/bin/git -C /Users/markkelsall/.cocoapods/repos/cocoapods fetch origin --progress
  $ /usr/bin/git -C /Users/markkelsall/.cocoapods/repos/cocoapods rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/markkelsall/.cocoapods/repos/cocoapods reset --hard origin/master
  HEAD is now at 6e256cc Create a copy of CocoaPods/Specs@2d939ca0abb4172b9ef087d784b43e0696109e7c
Analyzing dependencies
Pre-downloading: `AppAuth` from `https://github.com/openid/AppAuth-iOS.git`, tag `0.9.0`
Downloading dependencies
Installing AppAuth (0.8.0)
Installing CocoaLumberjack (2.3.0)
Installing KeychainItemWrapper (1.2)
Installing RNCryptor (2.2)
Installing SCConfiguration (2.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 4 dependencies from the Podfile and 5 total pods installed.```

**Comment by WilliamDenniss** [comment]
I think the issue is that you're using `source "https://github.com/CocoaPods/Old-Specs"` as the CocoaPod source.

That repo was last updated 6 months ago, and AppAuth 0.9.0 is newer than that. That'd be my guess.
