### ISSUE TITLE
SKIP_INSTALL isn't set on AppAuth-macOS

### ISSUE THREAD

**Issue by R4N** [openid/AppAuth-iOS#115]
When attempting to archive a macOS project that includes AppAuth-macOS a generic xcarchive is generated rather than a macOS App Archive.  This is because SKIP_INSTALL isn't set on AppAuth-macOS.

Specifically it's necessary to add `SKIP_INSTALL = YES;` to these build configurations:

AppAuth-macOS ~ Debug (340DAE551D58216A00EC285B)
AppAuth-macOS ~ Release (340DAE561D58216A00EC285B)

Here is the link to the issue raised in google-api-objetivec-client-for-rest project related to this: https://github.com/google/google-api-objectivec-client-for-rest/issues/124

Should I issue a PR?

**Comment by StevenEWright** [comment]
Yes, please! That would be wonderful!

Thanks for bringing this to our attention!
