### ISSUE TITLE
Support "claims" OpenID Connect auth request parameter

### ISSUE THREAD

**Issue by iainmcgin** [openid/AppAuth-iOS#12]
[OpenID Connect Core 1.0, Section 5.5](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter), `claims` parameter:

> OPTIONAL. This parameter is used to request that specific Claims be returned. The value is a JSON object listing the requested Claims.
> 
> An example Claims request is as follows:
> 
> ``` json
> {
>   "userinfo":
>   {
>       "given_name": {"essential": true},
>       "nickname": null,
>       "email": {"essential": true},
>       "email_verified": {"essential": true},
>       "picture": null,
>       "http://example.info/claims/groups": null
>   },
>   "id_token":
>   {
>       "auth_time": {"essential": true},
>       "acr": {"values": ["urn:mace:incommon:iap:silver"] }
>   }
> }
> ```

**Comment by WilliamDenniss** [comment]
Note that this is supported via the `additionalParameters` param in the `OIDAuthorizationRequest` initializers.

**Comment by alvincrisuy** [comment]
How to use this? as it only accepts NSDictionary<NSString *, NSString *> *)

**Comment by ShimelesT** [comment]
what is the exact purpose of value? can a client pass values to OP? 
"acr": {"values": ["urn:mace:incommon:iap:silver"] } 
or is it for verification?

**Comment by WilliamDenniss** [comment]
> How to use this? as it only accepts NSDictionary<NSString *, NSString *> *)

In this case, "claims" is the NSString key, and the JSON-encoded NSString is the value.

additionalParameters are simply added to the URL in key=value format. OpenID is expecting the value to be a JSON-encoded string, so that's what you should supply.

**Comment by WilliamDenniss** [comment]
> what is the exact purpose of value? can a client pass values to OP?
> "acr": {"values": ["urn:mace:incommon:iap:silver"] }
> or is it for verification?

It allows you to request from the OP certain claims that you want included in the ID Token. Here's the text from the [spec](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter):

> The claims Authentication Request parameter requests that specific Claims be returned from the UserInfo Endpoint and/or in the ID Token. It is represented as a JSON object containing lists of Claims being requested from these locations. Properties of the Claims being requested MAY also be specified.

Actually delivering those claims is really OP-dependent, so probably best to check with them what claims can be requested in this way.

**Comment by v-khatri** [comment]
Is IdToken available in latest release? (0.7.1)
