### ISSUE TITLE
Misleading instruction for using AppAuth as a static library

### ISSUE THREAD

**Issue by zboralski** [openid/AppAuth-iOS#125]
we should update the readme to say :

>Add **AppAuth-iOS**/Source to your search paths of your target ("Build Settings -> "Header Search Paths").

**Comment by zboralski** [comment]
I had no problem before using CocoaPods  but I won't to use the static library option in order to test one of the pull request.

**Comment by zboralski** [comment]
Solved the issue... we should update the readme to say :

>Add **AppAuth-iOS**/Source to your search paths of your target ("Build Settings -> "Header Search Paths").

**Comment by WilliamDenniss** [comment]
Want to send a PR?
