### ISSUE TITLE
Is it possible to change the request url to open WebView?

### ISSUE THREAD

**Issue by a513091a** [openid/AppAuth-iOS#131]
I am try to add Facebook-login function via AppAuth to call IdentityServer login.
However I don't find any method to change the request url to my VerifyFacebookLogin page from the index page;

In this case, is it possible to allow me to change the url using AppAuth request?

**Comment by WilliamDenniss** [comment]
I don't understand the question, can you clarify and provide a code sample of what you're trying to do?
