### ISSUE TITLE
OAuthErrorWithDomain crashes when receiving error message from Facebook

### ISSUE THREAD

**Issue by ChrisBGriffith** [openid/AppAuth-iOS#135]
It would appear that instead of a single string, Facebook returns a dictionary, which causes line 88 of `OIDErrorUtilities.m` to crash.

**Comment by ChrisBGriffith** [comment]
```
{
    code = 101;
    "fbtrace_id" = ACMDUl5aHg5;
    message = "Missing client_id parameter.";
    type = OAuthException;
}```

**Comment by WilliamDenniss** [comment]
Can you provide a test case I can run (e.g. link me to a git repo with a simple test case)?

**Comment by WilliamDenniss** [comment]
Can't reproduce, please re-open with a test-case if you have one.
