### ISSUE TITLE
Making NSURLSession extensible

### ISSUE THREAD

**Issue by gazadge** [openid/AppAuth-iOS#137]
Hey there,

OIDAuthorizationService is currently using NSURLSession via `[NSURLSession sharedSession]`.
This way there's no option for providing a custom session specific to AppAuth network calls.

Our proposal is to make this extensible by being able to provide custom NSURLSession instances for each request. For example:
- passing it as a request parameter
- or adding a session provider interface to the service configuration class (similar to the Android implementation https://github.com/openid/AppAuth-Android/tree/master/library/java/net/openid/appauth/connectivity)

The biggest advantage of this would be that the users of AppAuth would be able to use there custom sessions for network calls adding extra functionalities such as network logging or tracing.
The default implementation of this provider would simply use the same `[NSURLSession sharedSession]` instance as it is using now in each case.

What do you think? Do you have any concerns? We are happy to contribute with this change.

**Comment by WilliamDenniss** [comment]
Hey,

Sounds like a good change to me. I prefer the option of adding it to the session provider interface to avoid adding new params that many people won't use to a bunch of methods.  We did something similar with SafariViewController customization (`OIDSafariViewControllerFactory`).

Very happy to see a pull request with this. Please make sure you've signed the [CLA](https://github.com/openid/AppAuth-iOS/blob/master/CONTRIBUTING.md) so we can merge.

**Comment by shahmharsh** [comment]
@WilliamDenniss When will this be available in an official release? I see the PR is merged into master branch about a month back but no release is made yet.

**Comment by Karthikeyan1108** [comment]
Thanks for the implementation.Very happy to get the prompt response from team.
