### ISSUE TITLE
shouldHandleURL is case sensitive

### ISSUE THREAD

**Issue by IgorPietraszko** [openid/AppAuth-iOS#139]
shouldHandleUrl method is case sensitive and thus does not allow for mixed case redirect URLs.  This is not bad in itself (as long as it it clearly documented) but the implementation differs from AppAuth implementation for Android which does allow for mixed case redirect URLs.

Could be as simple as modifying OIDIsEqualIncludingNil(x, y) to negate case differences (not applicable to paswords).

**Comment by WilliamDenniss** [comment]
What are the benefits for being case insensitive with redirects? I think I'd rather change Android to be case sensitive.

**Comment by IgorPietraszko** [comment]
I agree that there are no advantages of case insensitive redirect URIs other than one does not expect casing to be a problem with URIs.  However you enter, provide a URI, one (or at least I) expect the matching to be case insensitive.  That's all.

**Comment by WilliamDenniss** [comment]
I personally don't expect URIs to use case insensitive comparison. Apache uses case sensitive URI handling by default, for example.

Reading [RFC3986 Section 6.2.2.1](https://tools.ietf.org/html/rfc3986#section-6.2.2.1), there are some parts of a URI like the hostname which are considered case insensitive, but that should be normalized to lowercase anyway (such that a case-sensitive comparison should be fine). The path component is defined as case sensitive.

[W3C guidance](https://www.w3.org/TR/WD-html40-970708/htmlweb.html) seems to agree:
"URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive. /u"

**Comment by IgorPietraszko** [comment]
I stand corrected - it seems like W3C guidance is pretty clear and I will adjust my expectations accordingly.  Should this then be a bug with the Android implementation team?  Do you coordinate your efforts?  Since I was implementing AppAuth on both platforms, I found the discrepancy lead to some frustration.

**Comment by WilliamDenniss** [comment]
In general we try to keep the libraries in sync.

Closing this bug here as WAI, will consider for AppAuth Android.
