### ISSUE TITLE
presentingViewController was removed but is still referred to

### ISSUE THREAD

**Issue by simihartstein** [openid/AppAuth-iOS#140]
Correct me if I'm mistaken, but it looks like
`OIDAuthState.authStateByPresentingAuthorizationRequest:presentingViewController`
was removed and has been replaced with
`OIDAuthState.authStateByPresentingAuthorizationRequest:UICoordinator`.

But, presentingViewController is still being used in the readme as well as the examples.

**Comment by WilliamDenniss** [comment]
Thanks for the catch. Care to send a PR with the fix?

**Comment by WilliamDenniss** [comment]
`OIDAuthState:authStateByPresentingAuthorizationRequest:presentingViewController:callback` is defined in `OIDAuthState_IOS.h` and is _not_ deprecated. It's a convenience method that creates a `OIDAuthorizationUICoordinator` for iOS, and calls `OIDAuthState:presentAuthorizationRequest:UICoordinator:callback`.

No change required.
