### ISSUE TITLE
authStateByPresentingAuthorizationRequest seems to be broken on iPhone X simulator

### ISSUE THREAD

**Issue by johnjcsmith** [openid/AppAuth-iOS#141]
When attempting to use `authStateByPresentingAuthorizationRequest ` in the iPhone X simulator, the SFSafariViewController appears to be broken.

This is not the case for the other simulators.

![screen shot 2017-09-19 at 5 15 59 pm](https://user-images.githubusercontent.com/9162298/30581218-9007624e-9d5e-11e7-9095-aa215edae7a9.png)
![screen shot 2017-09-19 at 5 15 03 pm](https://user-images.githubusercontent.com/9162298/30581224-91c6005e-9d5e-11e7-899c-8a6912e7c99e.jpg)

**Comment by WilliamDenniss** [comment]
Does it work for you on real hardware? The simulator is not always perfect?

btw. are you on the latest version? AppAuth on iOS 11 uses `SFAuthenticationSession`, not `SFSafariViewController`.

AppAuth 0.90 is running fine on my iPhone 6 with the iOS 11 GM seed.

**Comment by johnjcsmith** [comment]
Ahh, 
My apologies.

Looks like I was using 0.8. 0.9 present's fine.
