### ISSUE TITLE
Accept Http requests for testing 

### ISSUE THREAD

**Issue by hadiidbouk** [openid/AppAuth-iOS#148]
How can i make AppAuth library to accept insecure network ?

> Error retrieving discovery document: Optional("The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.")

**Comment by huynguyennovem** [comment]
hello, why do you close this? Have you resolved it? 
I got the same error:
```
The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
```
