### ISSUE TITLE
Presenting URL in WebView for macOS

### ISSUE THREAD

**Issue by Touchcore** [openid/AppAuth-iOS#149]
Is there a current example on how to perform authentication using a WebView for macOS? I need to create a unique url and use that to show a WebView.

**Comment by WilliamDenniss** [comment]
AppAuth doesn't support WebView for the reasons stated in [Section 8.12 of RFC8252](https://tools.ietf.org/html/rfc8252#section-8.12).

AppAuth does support macOS, using the browser for obtaining end-user authorization.
