### ISSUE TITLE
Support "registration" OpenID Connect auth request parameter

### ISSUE THREAD

**Issue by iainmcgin** [openid/AppAuth-iOS#16]
[OpenID Connect Core 1.0, Section 7.2.1](https://openid.net/specs/openid-connect-core-1_0.html#RegistrationParameter), `registration` parameter:

> OPTIONAL. This parameter is used by the Client to provide information about itself to a Self-Issued OP that would normally be provided to an OP during Dynamic Client Registration. The value is a JSON object containing Client metadata values, as defined in [Section 2.1 of the OpenID Connect Dynamic Client Registration 1.0](https://openid.net/specs/openid-connect-registration-1_0.html#ClaimsLanguagesAndScripts) specification. The registration parameter SHOULD NOT be used when the OP is not a Self-Issued OP.

**Comment by NazarYavornytskyy** [comment]
So, is "registration" implemented? In code I can't find method(s) for that.

**Comment by WilliamDenniss** [comment]
No it's not. But you can use the additional parameters features to add any param that isn't declared as a property.

**Comment by WilliamDenniss** [comment]
Not supported currently in AppAuth, no plans to support.
