### ISSUE TITLE
Wrong iOS deployment target in podspec

### ISSUE THREAD

**Issue by Ad1991** [openid/AppAuth-iOS#164]
The AppAuth podspec has deployment target set to iOS 7.0 while it requires SafariServices framework which is only available in iOS 9.0 or later. This is causing build failure unless deployment target is bumped manually or via podfile. It would be great to have the deployment target in accordance with used frameworks. See the screenshot for reference:
<img width="772" alt="screen shot 2017-10-25 at 12 03 44 pm" src="https://user-images.githubusercontent.com/5869330/31983990-507a1636-b97d-11e7-87ca-21d89686d65e.png">

**Comment by WilliamDenniss** [comment]
This is fixed in master, the deployment target is fine (we can weakly link SafariServices), but there was an availability labelling issue.
