### ISSUE TITLE
Dialog asking for sign-in permissions

### ISSUE THREAD

**Issue by Copy33** [openid/AppAuth-iOS#177]
When I perform the authentication I get a dialog saying

**"AppName" Wants to Use "{idp link}" to Sign In.
This allows the app and website to share information about you.**

What is causing this dialog to appear? 

Note that I am allowing arbitrary loads for app transport settings and allowing insecure connections (http) since I'm working in a testing environment, might that be the reason? Is there a way to get rid of this dialog?

**Comment by WilliamDenniss** [comment]
This is a system dialog that was added in iOS 11 to `SFAuthenticationSession`. It is triggered by this code in AppAuth: https://github.com/openid/AppAuth-iOS/blob/83736c9a3f658bea63be9164e37d0be54d0240a5/Source/iOS/OIDAuthorizationUICoordinatorIOS.m#L93-L97

There isn't a way to get rid of the dialog, except to not use `SFAuthenticationSession` which means you lose Single SignOn, which is worse.

**Comment by jogu** [comment]
(I'm not sure if it is best to ask a strongly related question here or open a new ticket. If you'd prefer me to open a new ticket I'm happy to.)

I have exactly the same issue.

My use case does not care about Single SignOn, is a pull request to AppAuth that allows the app developer to opt out of single sign on (and hence use SFSafariViewController and avoid the system permission dialogue) likely to be accepted?

**Comment by sattaman** [comment]
I'm interested in this too. Not liking hte new dialogue, and doesn't make sense for us.

**Comment by jorgengranseth** [comment]
Any updates on whether we can disable this prompt if we do not need SSO? We would prefer to avoid it for the sake of UX.

**Comment by julienbodet** [comment]
@jorgengranseth Yes there is a way, if you do not need SSO, you just have to implement your own `[OIDExternalUserAgent](https://github.com/openid/AppAuth-iOS/blob/master/Source/OIDExternalUserAgent.h)` using `SFSafariViewController` instead of `SFAuthenticationSession`/`ASWebAuthenticationSession`.

**Comment by jorgengranseth** [comment]
@julienbodet Thanks. I haven't written a line of Objective C before but use this library through [react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth). So I forked AppAuth-iOS and removed the iOS 11 part using `SFAuthenticationSession` as a test, which seems to have worked.

Is this fundamentally different to implementing my own `OIDCExternalUserAgent`, or is the result the same since I reach the fallback code using `SFSafariViewController` in ` Source/iOS/OIDExternalUserAgentIOS.m`?

I branched out from the `0.95.1` tag, but do you know if [`ASWebAuthenticationSession`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) has the same prompt behaviour as `SFAuthenticationSession` (for iOS 12+) for future reference, when the `1.0.0` release is final?

**Comment by julienbodet** [comment]
> Is this fundamentally different to implementing my own `OIDCExternalUserAgent`, or is the result the same since I reach the fallback code using `SFSafariViewController` in ` Source/iOS/OIDExternalUserAgentIOS.m`?

Yes the result is the same. The is only difference is that you don't need to fork the library to implement your own `OIDExternalUserAgent`.

> I branched out from the `0.95.1` tag, but do you know if [`ASWebAuthenticationSession`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) has the same prompt behaviour as `SFAuthenticationSession` (for iOS 12+) for future reference, when the `1.0.0` release is final?

Yes `ASWebAuthenticationSession` has the same prompt behaviour as `SFAuthenticationSession`.

**Comment by marwamelfeky** [comment]
After pressing continue in this popup it causes my app to stop responding and only blur the screen without errors  what causes this error?

**Comment by felri** [comment]
@jorgengranseth Did it worked with react-native-app-auth? I'm having the same problem and can't find a solution.

**Comment by jorgengranseth** [comment]
@felri it works. Whether it's a good idea is another matter.

**Comment by JohnVRtron** [comment]
> After pressing continue in this popup it causes my app to stop responding and only blur the screen without errors what causes this error?

Hi, did you manage to resolve the issue? I'm having the same problem. Thanks.

**Comment by marwamelfeky** [comment]
> > After pressing continue in this popup it causes my app to stop responding and only blur the screen without errors what causes this error?
> 
> @marwamelfeky
> Hi, did you manage to resolve the issue? I'm having the same problem. Thanks.

 Solved in two steps
1-In the class you will open safari controller , override func viewWillDisappear(_ animated: Bool) {
if(self.presentedViewController != nil &&
self.presentedViewController!.isKind(of: SFSafariViewController.self)){
ThreadsUtility.execute({
self.presentedViewController!.view.frame = self.view.frame
}, afterDelay: 0.1)
}
}
This code will set the frame of SFSafariViewController 
2 - extension of SFSafariViewController to present full screen

extension SFSafariViewController {
    override open var modalPresentationStyle: UIModalPresentationStyle {
        get { return .fullScreen}
        set { super.modalPresentationStyle = newValue }
    }
}

**Comment by sudhakarselva** [comment]
any update on this topic ?. coming from react-native-app-auth which consumes this library.

**Comment by Laith-Bzour** [comment]
go to OIDExternalUserAgentIOS > line 117 after @available(iOS 13.0, *)
write this line  : authenticationVC.prefersEphemeralWebBrowserSession = true

**Comment by sudhakarselva** [comment]
@Laith-Bzour  Thanks for the update. can u pls clarify following doubts as I have not worked on native code before.

-  it will not support ios 11 and 12 ?.
-  authenticationVC.prefersEphemeralWebBrowserSession = true what does it do.

Thanks again!

**Comment by mtoninelli** [comment]
@sudhakarselva Did you figure it out? I'm also using react-native-app-auth.

**Comment by sudhakarselva** [comment]
@mtoninelli  Unfortunately, have not resolved it yet

**Comment by AdrianBordeianu** [comment]
Optionally Request Ephemeral Browsing

You can configure the session to request ephemeral browsing by setting the session’s [prefersEphemeralWebBrowserSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio) property to true:


session.prefersEphemeralWebBrowserSession = true

This setting asks the browser to avoid using any existing browsing data, like cookies, during the authentication process. It also asks that the browser avoid retaining any data collected during the authentication attempt beyond the lifetime of the attempt, or sharing it with any other session. An ephemeral session improves security but prevents reusing the result of a previously successful authentication, potentially forcing the user to reenter credentials. As a result, it’s typically best to let the user choose whether to request ephemeral browsing.

Safari always respects the request. In macOS, the user can choose a different default browser that might or might not respect the request.

https://developer.apple.com/documentation/authenticationservices/authenticating_a_user_through_a_web_service

**Comment by AdrianBordeianu** [comment]
> @Laith-Bzour Thanks for the update. can u pls clarify following doubts as I have not worked on native code before.
> 
>     * it will not support ios 11 and 12 ?.
> 
>     * authenticationVC.prefersEphemeralWebBrowserSession = true what does it do.
> 
> 
> Thanks again!

Optionally Request Ephemeral Browsing

You can configure the session to request ephemeral browsing by setting the session’s [prefersEphemeralWebBrowserSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio) property to true:


session.prefersEphemeralWebBrowserSession = true

This setting asks the browser to avoid using any existing browsing data, like cookies, during the authentication process. It also asks that the browser avoid retaining any data collected during the authentication attempt beyond the lifetime of the attempt, or sharing it with any other session. An ephemeral session improves security but prevents reusing the result of a previously successful authentication, potentially forcing the user to reenter credentials. As a result, it’s typically best to let the user choose whether to request ephemeral browsing.

Safari always respects the request. In macOS, the user can choose a different default browser that might or might not respect the request.

https://developer.apple.com/documentation/authenticationservices/authenticating_a_user_through_a_web_service

**Comment by groue** [comment]
Hello,

Support for ephemeral web browser sessions, mentioned several times in previous comments above, is useful, if only because it allows applications to avoid the system dialog mentioned in the OP.

Considering the age of this issue, it looks like community contributions are unable to fix this problem.

Please, benevolent core library contributors, don't let such issue stay open for that long. We all need a robust and reliable OAuth/OpenID library.

**Comment by groue** [comment]
It looks like commit c1a5080e5fe60579ba8f4c753535e18a248eb5b0 by @danblakemore is addressing this issue. It would be great a new version of the library would ship with this fix!

**Comment by hupendraaplite** [comment]
![Simulator Screenshot - iPhone 14 Pro - 2023-08-21 at 13 05 55](https://github.com/openid/AppAuth-iOS/assets/45382984/a6dbd593-4156-4ff0-ac7e-de161b2a7466)
 Can we remove (Sign in to “app name” and & Safari option from alert 
 I am using "AppAuth"iOS SDK.
