### ISSUE TITLE
Pre-filling user email addresses

### ISSUE THREAD

**Issue by atomicbird** [openid/AppAuth-iOS#178]
In my iOS app we *probably* know the user's email address before requesting access to their Google account. Users will have already logged in to our platform, and in most cases their username on our platform will be the same as their email address. So for Gmail-hosted addresses there's a high probability that we already know their username.

When requesting OAuth access, is there any way to pre-fill the user email address? I'd like to save our users an extra step if I can. They would of course be able to change that and authorize a different account, but if I could pre-fill this detail I'd save many of our users an extra step. Ideally I could provide this to something like `authStateByPresentingAuthorizationRequest:`, but whatever would work is welcome.

**Comment by panva** [comment]
providing extra `login_hint` authorization request parameter with the value you want to have pre-filled should do the trick for most OpenID Connect OPs

**Comment by atomicbird** [comment]
Where would that go? On the issuer URL when I create the authorization request?

**Comment by atomicbird** [comment]
Oh I see, the `additionalParameters` argument when creating the `OIDAuthorizationRequest`. Thanks.
