### ISSUE TITLE
How do I get the email address?

### ISSUE THREAD

**Issue by jysuh777** [openid/AppAuth-iOS#180]
Whenever I create a OIDAutorizationRequest, I include OIDScopeEmail as below

OIDAuthorizationRequest *request =
      [[OIDAuthorizationRequest alloc] initWithConfiguration:configuration
                                                    clientId:clientID
                                                clientSecret:clientSecret
                                                      scopes:@[ OIDScopeOpenID, OIDScopeProfile, OIDScopeEmail]
                                                 redirectURL:redirectURI
                                                responseType:OIDResponseTypeCode
                                        additionalParameters:nil];

I am able to successfully access token.
However, I am uncertain of how to find the user's email address.
Can you help me do so?
Thanks in advance!

**Comment by WilliamDenniss** [comment]
You can inspect the ID Token, or call the UserInfo endpoint, as the included sample does:

https://github.com/openid/AppAuth-iOS/blob/83736c9a3f658bea63be9164e37d0be54d0240a5/Examples/Example-iOS_ObjC/Source/AppAuthExampleViewController.m#L360-L448

If you need more help than this, please ask your question on StackOverflow where you will get more eyeballs on the problem.
