### ISSUE TITLE
Proper flow when user signs up (not logs in)

### ISSUE THREAD

**Issue by osgafarov** [openid/AppAuth-iOS#183]
Hey,

I am using AppAuth for iOS and I have an OAuth2 server.
When user logs in, everything works like a charm, however I am having problems implementing a sign up flow.
Is this a correct flow?
1. The client app sends some user specific data to the server (email, password, etc.).
2. The server returns back token info in a form:
```
{
    "access_token":"9154140d-b621-4391-9fdd-fbba9e5e4188",
    "token_type":"bearer",
    "refresh_token":"dd612036-7cc6-4858-a30f-c548fc2a823c",
    "expires_in":89,
    "scope":"write"
}
```
3. I save the OIDAuthState in keychain and perform a request with fresh tokens whenever required.

I have an issue with the third step, as I described here: https://github.com/openid/AppAuth-iOS/issues/165

I also posted a question on StackOverflow: https://stackoverflow.com/questions/47055826/appauth-ios-how-to-save-the-token-info-after-user-registers-an-account-in-my-ow
But I haven't received a working solution, so I am posting an issue here again to get a reply from creators of the AppAuth framework. 
You can see in the related issue that when I persist the OIDAuthState, it does not save the refresh token (it's not able to parse it from additional parameters).

In the examples I can only find a flow where an existing user signs in, but there is no example of the registration of a new user.

Thanks,
Osman

**Comment by WilliamDenniss** [comment]
From an OAuth protocol perspective, there is no difference between signing in, and signing up.  Those steps happen between the authorization request being sent to the browser, and the authorization response being returned.

As long as your return the correct OAuth 2.0 authorization response from the server after sign-up (same like you would during sign-in), AppAuth will process it correctly.
