### ISSUE TITLE
Support for Steam Auth

### ISSUE THREAD

**Issue by juthayn** [openid/AppAuth-iOS#192]
I'm attempting to use AppAuth-iOS to authenticate with Valve's Steam platform, which uses OpenID (https://steamcommunity.com/dev). Documentation from Steam/Valve is sparse but essentially all they give you is an API key and a provider URL (http://steamcommunity.com/openid)

AppAuth requires things like clientID, authentication endpoint, token endpoint, redirect URL, etc. but none of these are provided by Steam.

Is it possible to use AppAuth-iOS for Steam Authentication?

**Comment by WilliamDenniss** [comment]
You'd need to ask Steam this. If it's an OpenID Connect provider that supports the [server requirements of AppAuth](https://tools.ietf.org/search/rfc8252#appendix-A), it will work. Note that the older "OpenID" (i.e. not Connect) isn't supported.
