### ISSUE TITLE
Support "acr_values" OpenID Connect auth request parameter

### ISSUE THREAD

**Issue by sattaman** [openid/AppAuth-iOS#199]
I am currently migrating our app from oidc-client-js and implicit flow to app auth. 

A feature we are currently using is passing acr_values when logging in directly to Facebook and Google. 

`oidc.signinPopup({ acr_values: 'idp:Google' })`

A search of the issues revealed a previous request for this been closed as won't fix. https://github.com/openid/AppAuth-iOS/issues/11

I wondered if almost a year down the line this may now be something to be considered?

**Comment by panva** [comment]
I believe you can pass any parameters as `additionalParameters` in the authorization request, that also applies to `acr_values`. The one thing then you should then check yourself is if the acr claim is fulfilled and a part of the id token.

**Comment by WilliamDenniss** [comment]
+1. You can use `additionalParameters` for this in the initializer for `OIDAuthorizationRequest`.
