### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by nubbel** [openid/AppAuth-iOS#20]
Hey!

We're working on OSX support over at https://github.com/equinux/AppAuth-iOS.
Is there any chance we could get our changes merged into this repo (and change the name to AppAuth only)?
Alternatively, we could extract the platform-independent parts into a separate pod AppAuth-Core and create a new pod AppAuth-Mac that depends on it.

What do you think?

/cc @DarkDust

**Comment by iainmcgin** [comment]
Hey! I think it would probably make sense to try and split platform-specific pieces out into separate repos, so I would vote for some "core" repo (AppAuth-Darwin-Core?), with this repo and AppAuth-MacOS depending on it / acting as plugins for it. @WilliamDenniss, any thoughts?

I had a quick look at your changes, looks like you're using WKWebView - we strongly discourage this for a few reasons:

1. It is not clear to the user what page they are actually interacting with - phishing via WKWebView is trivial, and it trains users to blindly trust login forms that may not be safe.
2. It allows a malicious / compromised app to steal user credentials easily even when a legitimate login page is presented, by injecting JS into the view that can capture credentials.
3. Users will not get a real "single sign-on" experience as the WKWebView has no access to the cookies of the main browser, so they will be required to enter their credentials again. This can be particularly problematic if a hardware second factor is required, as it may not be possible to interact with this from a WKWebView depending on how it works.

I would instead recommend you start a localhost web server to capture the OAuth response, and then send the openURL request to the default browser. This solves all three issues listed above. There may be less crude ways of handling the response - I don't know if there is an equivalent to custom scheme registration or universal links in Mac OS, but some cursory searching hasn't turned anything up.

**Comment by nubbel** [comment]
Thanks for your quick answer!

I'd suggest AppAuth-Cocoa for the "core" project. You could also keep the plugins in the same repo and make them available as sub-pods.

The issues you mentioned are all valid, but are no big deal in our use case. Our app uses AppAuth to authenticate against our own identity provider, basically just replacing a native login dialog. True SSO is not required as we want the user to explicitly log in once. When the core functionality is factored out, it would become trivial for us to build a custom plugin (AppAuth-Mac-SuperDangerous?) that handles our special case.

In contrast, the "official" AppAuth-Mac plugin could implement the flow you described above. The response can be handled with a custom URL scheme just like on iOS. Universal links are not yet supported in OSX, but who knows what WWDC16 will bring ;).

Let me know if you want my help to make the changes. 🍻

**Comment by ve7jtb** [comment]
Just a reminder that new contributors need to OpenID Connect WG members and sign the CLA.   

I hope that is not a problem as seems like a good thing to be supporting.   We are also hoping to have Windows at some point.  

Let me know if you need any help with the IPR process, so we can take pull requests from you.

Regards
John B.

**Comment by StevenEWright** [comment]
@IainMcgin @WilliamDenniss:

Hey guys!

Just saw this thread and felt I should chime in...

I understand the reaction to seeing WKWebView -- but I feel the situation for desktop apps may be more nuanced than for mobile apps. I, for one, have a few questions...

As far as I know; desktop applications on MacOS (which are not sandboxed) have (or can easily obtain) basically unlimited power when it comes to a user's desktop... 

[Requests for "Administrator Privileges" (and the like) are still common in my experience. Even for legitimate apps doing legitimate things. If I had to guess; the request is almost always granted, usually without any explanation of why the privileges are being requested or what they will be used for.]

...powers which include, but are not limited to;

- Taking screenshots/video at any point in time,
- Logging keystrokes (even when not the application with focus),
- Enumerating windows for other applications,
- Inspecting the contents of other applications' windows' controls (like text boxes),
- Launching processes which stay alive after the launching process is terminated,
- Etc. (Ah... the good ol' days! Remember?)

Even Apple's free documentation provides a simple getting-started-style sample application called "Son of Grab" which demonstrates both enumerating the windows of all running applications and taking screenshots of those windows unobstructed... https://developer.apple.com/library/mac/samplecode/SonOfGrab/Introduction/Intro.html

So, while I don't disagree with the spirit of anything you've said, and I couldn't agree more that:

- Users should not be trained to enter credentials into an application which displays a box purporting to be the sign in page of an identity provider,
- and; Using a web view which doesn't share the system cookie jar introduces unnecessary friction and leads to bad UX,

I do think the suggestion that using the system browser actually solves all the (security) problems we are trying to avoid may not be completely accurate.

Perhaps we should put some effort into defining more clearly what we are trying to solve and what we are not.

Do we assume Sandboxing? If so, what realistic options exist for bi-directional communications with an external trusted agent? Must the trusted agent be the default browser on the system?

Where do we draw the line regarding what a person should reasonably assume to be secure vs. what would be unreasonable to assume to be secure? For example; I believe it's reasonable for a general consumer to assume the communications the cable company has with their cable modem is secure, and that the DHCP services which hand out IPs and DNS server addresses are also secure. I believe it's reasonable for a general consumer to assume the root certificate authorities that come installed with their OS are secure. I think those are fairly reasonable assumptions for most people. Are we willing to go so far as to say: "it should not be reasonable for the general consumer to assume their system is secure if they have installed any application whatsoever which is not sandboxed?" or how about: "It should be reasonable for the general consumer to assume that an app purchased from the app store is not going to steal the credentials to their identity provider."?

I'm not proposing answers to these questions - I'm simply trying to raise some of the questions which illustrate why I feel the situation for desktop apps may be more nuanced than for mobile apps.

I, for one, would very much like to see AppAuth on MacOS and Windows. Perhaps there is enough interest to make that happen! A bit of (public) clarity on the vision could make the difference between someone willing to risk their time on a contribution vs. simply forking the repo and doing their own thing?

**Comment by iainmcgin** [comment]
It sounds like we're all in agreement that launching something like Google Sign-in within an app is probably bad, caveat the myriad other ways that an app on MacOS can compromise your security. Launching your own sign-in flow with your own OAuth2 implementation is of course totally fine to embed into your app, particularly if there is no real expectation or need to share that core authenticated state across sites or applications. 

So. a MacOS variant of AppAuth that lets the app developer choose how to launch the flow, with appropriate discussion and full disclosure in the API documentation of the pros and cons of each approach, sounds fine to me.

**Comment by WilliamDenniss** [comment]
It's true that your use-case of a first-party authenticating to itself is the [one exception](https://tools.ietf.org/html/draft-ietf-oauth-native-apps-01#section-5.1) to never using web-view for OAuth.

For reference, even for first-party Google apps on Mac authenticating to Google, the Google OAuth team recommends the system browser. See Android Studio as a production example of this. But I understand that not every IdP/AS is the same in this regard and you have different requirements.

My concern about shipping a version of AppAuth with any kind of WebView support is that people will use it in places they shouldn't (like with a third-party OAuth provider such as Google).  Given this is open source, having a "SuperDangerous" plugin/fork in existence seems fine to me, but I think it's important not to ship that code in _this_ library, which strives to be opinionated on that front.

I talked this over with @iainmcgin and @StevenEWright, here's what we propose for your changes:
1. Add a new build target to the current project, and keep both the Mac & iOS code in this repo (which we can rename in the future).
2. Create a new AppAuth for OSX Pod
3. I'd love to take you up on your offer to help make the Mac changes to support custom-URI schemes!
4. Eventually we should add `localhost` support as an option too (this is where the library will spin up a tiny webserver just to capture the OAuth redirect, like what Android Studio does).

What do you think of this roadmap?

Before we go further, can you please sign the [CLA](https://github.com/openid/AppAuth-Android/blob/master/CONTRIBUTING.md) so we can start to look at merging your code? If the code you write is owned by your company, then it should be your company that signs.

**Comment by nubbel** [comment]
Hey guys, it's nice to see such a great discussion!

I passed the agreements on to our dev lead @martinott. He will check and (probably) sign them, so we can move on.

@WilliamDenniss I like the idea to have only one repo and Xcode project. We should do the same for the Pod. It's pretty common for pods to target multiple platforms.
I see your point in supporting the local web server approach - the user doesn't need to define a custom URL scheme and handle the callback. Have you ever thought of adding that to iOS as well?

**Comment by DarkDust** [comment]
Hey guys, I'm the one who wrote the first port to OS X. I was on vacation and can only now chime in.

I understand the security concerns and agree that using the system browser should be the default. Safe-by-default is important.

As has been mentioned before, our use case is probably a rare one. Personally, I mostly care about having a supported way for us to implement the WKWebView support so that we can update AppAuth without the need to maintain custom patches or something like that.

Making AppAuth work on OS X was actually pretty easy. There's only three classes that are (Apple-)OS-specific: `OIDAuthorizationFlowSessionImplementation`, `OIDAuthorizationService` and `OIDAuthState`. Actually, the later two only forward stuff to `OIDAuthorizationFlowSessionImplementation` so it can present and dismiss the view controllers.

Here's a rough proposal to solve this:

* Create a new protocol for the OS-dependent parts: Let's call it `OIDAuthorizationFlowShim` for the sake of discussion.
* The user would create an object that implements this protocol and this is what then gets passed by `OIDAuthorizationService` and `OIDAuthState` to `OIDAuthorizationFlowSessionImplementation`.
* To re-implement the current iOS flow, a `OIDAuthorizationFlowShimiOS` object would get initialized with the parent view controller. It would be the one that creates the `SFSafariViewController` if possible and presents it (or fall back to `openURL:`).
* We also need a way "back" so that the shim can call `-[OIDAuthorizationFlowSessionImplementation didFinishWithResponse:error:]`. Maybe a callback block that gets passed to the shim, [similar to `NSURLSession`](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSessionTaskDelegate_protocol/index.html#//apple_ref/occ/intfm/NSURLSessionTaskDelegate/URLSession:task:didReceiveChallenge:completionHandler:). 

This would make AppAuth OS-agnostic (except for the actual shim implementations) and allows AppAuth to provide safe default implementations for each OS, while also allowing us to provide a custom object that implements a WKWebView solution.

**Comment by StevenEWright** [comment]
@DarkDust Your plan sounds good to me!

**Comment by WilliamDenniss** [comment]
Sounds good to me too.

**Comment by msarda** [comment]
@DarkDust Is this something you are working on? Do you have an idea when the macOS support will be available in the AppAuth library?

Thank you.

**Comment by DarkDust** [comment]
@msarda: I'm going to be working on it Soon™, but I can't give a prediction right now. Unfortunately, we were very busy the last few weeks.

**Comment by msarda** [comment]
We will need a working solution for Mac in about 2 weeks. We'll probably implement your proposal then if you do not have the time to look it at before. Is that OK for you?

**Comment by DarkDust** [comment]
Of course that's OK for me :-)

**Comment by maxsz** [comment]
Fyi: I've just moved our code to a new branch, in case someone needs this for reference https://github.com/equinux/AppAuth-iOS/tree/feature/mac-support

**Comment by msarda** [comment]
To avoid doing any duplicate work, I've started implementing the suggestion above. I hope to have something ready soon (today or tomorrow).

**Comment by msarda** [comment]
PR https://github.com/openid/AppAuth-iOS/pull/30 contains the implementation that was suggested above.

**Comment by martinott** [comment]
I have signed the agreements for equinux AG covering the contributions from @nubbel, @DarkDust, and @maxsz.

**Comment by WilliamDenniss** [comment]
AppAuth officially supports macOS. Thanks to everyone who contributed!
