### ISSUE TITLE
Add support for other browsers on iOS

### ISSUE THREAD

**Issue by WilliamDenniss** [openid/AppAuth-iOS#200]
To support "enterprisy" use-cases like those encountered by the NCCoE's [Mobile SSO effort](https://nccoe.nist.gov/projects/use-cases/mobile-sso), it would be useful to include support to process the OAuth request in alternative user-agents on iOS such as Chrome and Firefox.

These external user-agents may support additional features like U2F which are required by some enterprise environments.

This feature would be specifically for environments where you can control what apps users have installed (such as an enterprise workplace). Consumer apps should continue to use the existing in-built external user-agents (i.e. the various incarnations of Safari) supported by AppAuth.

AppAuth already abstracts away the `UICoordinator` to handle requests in the user-agent to support browsers on different platforms, so this functionality could simply be provided as an alternative implementation `UICoordinator` on iOS.

**Comment by TommyJ1994** [comment]
@WilliamDenniss Mind adding how-to notes to the main Readme? It's not really visible that this feature exists there.

**Comment by WilliamDenniss** [comment]
In due course. This only just landed in HEAD, needs an example too ideally.

**Comment by sattaman** [comment]
Will this change also allow consumer apps to login without SSO ?

**Comment by WilliamDenniss** [comment]
@sattaman not directly, but a similar pattern could achieve that. Let's continue that discussion in #209 rather than here.

**Comment by munderk** [comment]
Working with safari but not with chrome..

**Comment by WilliamDenniss** [comment]
@munderk please file a bug report if you're experiencing an issue.

**Comment by WilliamDenniss** [comment]
For the record, I just tested AppAuth's custom browser support with Chrome (v67.0.3396.87) on iOS 11.4.1, following [these instructions](https://gist.github.com/WilliamDenniss/70da59c634055dfefbb79d2df14f306f), and everything worked as expected.
