### ISSUE TITLE
Gmail error: Parameter not allowed for this message type: redirect_uri

### ISSUE THREAD

**Issue by triton3** [openid/AppAuth-iOS#207]
I am using AppAuth (v0.92.0) on iOS and macOS. The app has already performed OAuth 2 authorization and received tokens from Gmail.

Recently, I have started seeing the error shown below intermittently on both iOS and macOS, when attempting to call `performActionWithFreshTokens:`.

    Parameter not allowed for this message type: redirect_uri

The console log output has the following message:

    OIDAuthState:updateWithTokenResponse should not be called in an error state [Error Domain=org.openid.appauth.oauth_token Code=-2 "invalid_request: Parameter not allowed for this message type: redirect_uri" UserInfo={OIDOAuthErrorResponseErrorKey={
    error = "invalid_request";
    "error_description" = "Parameter not allowed for this message type: redirect_uri";
    }, NSLocalizedDescription=invalid_request: Parameter not allowed for this message type: redirect_uri, NSUnderlyingError=0x1c8050920 {Error Domain=org.openid.appauth.remote-http Code=400 "{
      "error" : "invalid_request",
      "error_description" : "Parameter not allowed for this message type: redirect_uri"
    }" UserInfo={NSLocalizedDescription={
      "error" : "invalid_request",
      "error_description" : "Parameter not allowed for this message type: redirect_uri"
    }}}}] callupdateWithAuthorizationResponse with the result of the fresh authorization responsefirst

This error goes away after some time.

**Question:** Is there anything else  I would need to check before making API calls with IMAP server using OAuth? The examples seem to indicate that only `performActionWithFreshTokens:` is required for ensuring fresh tokens before making API calls, unless I missed something.

Any help would be greatly appreciated!

**Comment by WilliamDenniss** [comment]
I think this is a bug in AppAuth. `redirect_uri` isn't specified as a parameter during token refresh, yet we're sending it anyway.

**Comment by triton3** [comment]
Is there a workaround for now, until an update? Any help is much appreciated.

**Comment by WilliamDenniss** [comment]
You can apply the #213 PR locally. This will be fixed in HEAD when that is merged.
