### ISSUE TITLE
Release a new version with #200 changes

### ISSUE THREAD

**Issue by victorg1991** [openid/AppAuth-iOS#211]
I cannot use this library because SFSafariViewController is not sharing the cookies with Safari in iOS 11 making the SSO impossible to work

I see this PR https://github.com/openid/AppAuth-iOS/issues/200 and I think this would solve the issue but it is not released yet. When is it going to be released?

**Comment by WilliamDenniss** [comment]
I'll cut a release when some other refactoring is complete to avoid API churn. Until then, I'd suggest running with master (if you're using CocoaPods, you can point it at the master branch to get going with those features).
