### ISSUE TITLE
Use of undeclared type 'OIDAuthorizationFlowSession'

### ISSUE THREAD

**Issue by admeister** [openid/AppAuth-iOS#216]
After cloning a fresh copy of AppAuth with Carthage, commit 43541338d5a28a2305564d37997aef9e647b4df, Xcode reports an error saying

Use of undeclared type 'OIDAuthorizationFlowSession'

**Comment by WilliamDenniss** [comment]
Confirmed bug. Please point Carthage at one of the release tags, we're doing some refactoring right now in master.

**Comment by WilliamDenniss** [comment]
Should be resolved with #217

**Comment by EnderXenocida** [comment]
I have the same problem with the last version.

**Comment by Copy33** [comment]
Same issue as well @EnderXenocida, did you figure out a workaround?

**Comment by WilliamDenniss** [comment]
The last two comments that refer to the latest HEAD/1.0.0.beta1 version is unrelated to the initial bug, even though the error is the same so I'm going to lock this bug to avoid confusion (you're welcome to open a new bug for this new issue).

The issue that you're seeing with the 1.0.0.beta1 release is that we removed all deprecated classes and methods when we did the 1.x cut, of which this class is one.

To update, first point your code at the 0.95.0 release, resolve any "deprecated" warnings, then you should be able to point your code to 1.0.0.beta1.
