### ISSUE TITLE
safariViewControllerDidFinish triggers OIDErrorCodeProgramCanceledAuthorizationFlow instead of OIDErrorCodeUserCanceledAuthorizationFlow.

### ISSUE THREAD

**Issue by julienbodet** [openid/AppAuth-iOS#221]
From `OIDExternalUserAgentIOS.m`:

```
- (void)safariViewControllerDidFinish:(SFSafariViewController *)controller NS_AVAILABLE_IOS(9.0) {
  if (controller != _safariVC) {
    // Ignore this call if the safari view controller do not match.
    return;
  }
  if (!_externalUserAgentFlowInProgress) {
    // Ignore this call if there is no authorization flow in progress.
    return;
  }
  id<OIDExternalUserAgentSession> session = _session;
  [self cleanUp];
  NSError *error = [OIDErrorUtilities errorWithCode:OIDErrorCodeProgramCanceledAuthorizationFlow
                                    underlyingError:nil
                                        description:nil];
  [session failExternalUserAgentFlowWithError:error];
}
```

According to the [Apple documentation](https://developer.apple.com/documentation/safariservices/sfsafariviewcontrollerdelegate/1621214-safariviewcontrollerdidfinish) `safariViewControllerDidFinish:` is called when the user dismissed the view. Knowing that, this delegate method should trigger an `OIDErrorCodeUserCanceledAuthorizationFlow` error instead of `OIDErrorCodeProgramCanceledAuthorizationFlow`.

Is this bug or am I missing something?

**Comment by WilliamDenniss** [comment]
I agree, this is a bug.

**Comment by WilliamDenniss** [comment]
Docs [say](https://developer.apple.com/documentation/safariservices/sfsafariviewcontrollerdelegate/1621214-safariviewcontrollerdidfinish?language=objc) "Tells the delegate that the user dismissed the view."
