### ISSUE TITLE
OIDAuthorizationService in Swift

### ISSUE THREAD

**Issue by paulbrittain** [openid/AppAuth-iOS#225]
I need to declare a variable of type OIDAuthorizationService in Swift while translating the following Objective-C to Swift to use an objective-c library in a project.

**Pre-translated objective-c**
.h
```objective-c
+ @protocol OIDAuthorizationFlowSession;

  @interface AppDelegate : UIResponder <UIApplicationDelegate>
+ @property(nonatomic, strong, nullable) id<OIDAuthorizationFlowSession> currentAuthorizationFlow;
  @property (nonatomic, strong) UIWindow *window;
  @end
```
.m
```objective-c
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options {
  if ([_currentAuthorizationFlow resumeAuthorizationFlowWithURL:url]) {
    _currentAuthorizationFlow = nil;
    return YES;
  }
  return NO;
}
```

**So far I have the following translation:**

```swift
  var currentAuthorizationFlow: OIDAuthorizationFlowSession?

  ...

  func application(_ application: UIApplication, openURL: NSURL,
                   didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    if currentAuthorizationFlow!.resumeAuthorizationFlow(with: openURL as URL) {
      return true
    }
    return false
  }
```

Is this code correct? 

Error is: Use of undeclared type: 'OIDAuthorizationFlowSession', as espected, how do I do this?

**Comment by julienbodet** [comment]
Did you import AppAuth in the AppDelegate.swift file? Like the following: `import AppAuth` at the beginning of the file.

Your code is not correct as you don't call the `resumeAuthorizationFlow` method in `application(_:open:options:)`. 

You also forgot to set `self.currentAuthorizationFlow = nil` once `resumeAuthorizationFlow` returns `true`. And finally you should avoid force unwrapping `currentAuthorizationFlow` which may be nil when opening another url. Here is what you should have:

`
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey: Any] = [:]) -> Bool {
        if let authorizationFlow = currentAuthorizationFlow, authorizationFlow.resumeAuthorizationFlow(with: url as URL) {
            self.currentAuthorizationFlow = nil
            return true
        }
        
        return false
    }
`
One thing you could add is checking that the received `url` matches the `redirect_uri` you sent at the authorization in case your app handles multiples URLs.

**Comment by paulbrittain** [comment]
That worked great @julienbodet it's my first attempt at objc->swift translation I appreciate you taking the time to comment! It doesn't appear I'm required to import AppAuth in the AppDelegate.swift file, as long as it's in the bridging header it works. This also works:

```swift
    func application(
      _ app: UIApplication,
      open url: URL,
      options: [UIApplicationOpenURLOptionsKey: Any] = [:]) -> Bool {
      
      if currentAuthorizationFlow!.resumeAuthorizationFlow(with: url){
        currentAuthorizationFlow = nil
        return true
      }
      
      return false;
    }
```

It should also be noted for anyone else with this problem, that when working with pods you need to open the xcworkspace, not the xcodeproj so that the pods are visible.
