### ISSUE TITLE
Control over dismissing presented SFSafariViewController? 

### ISSUE THREAD

**Issue by ztepsa** [openid/AppAuth-iOS#237]
Is it possible to get control over dismissing presented SFSafariViewController?

When called `OIDAuthState.authState(byPresenting: , presenting: , callback: )` after successful login or by tapping cancel button, controller is dismissed and callback is called, I would like to do some API calls with newly fetched accessToken before dismissing the SFSafariViewController.

Ideas so far:
* create holder controller that will be used to present SFSafariViewController, so after login is done control goes back to holder controller and it's possible to do network call before returning control back to the user. (would like to avoid this option if possible)

* create instance of `OIDExternalUserAgentIOS` and present it using `OIDAuthorizationService.present( , externalUserAgent: , callback: )`, after that is done create tokenRequest and fetch it using `OIDAuthorizationService.perform( , callback: )`, but the issue here is that once token request is done, userAgent is dismissed automatically. I could subclass `OIDExternalUserAgentIOS` and override `dismiss(animated: , completion: )`, but it's really not a nice solution.

Any suggestion on how to solve this issue without implementing custom external user agent, or by wrapping SFSafariViewController some holder controller?

**Comment by StevenEWright** [comment]
@ztepsa I’d be interested to learn more about why you closed this. Did you find a workaround for your situation that worked well for you? Do you no longer feel the feature is worthwhile?

**Comment by ztepsa** [comment]
@StevenEWright in the end I decided to go with additional UI component that will display Safari and handle all the pre/post login actions. After checking out how the AppAuth is implemented and trying out different combinations this seemed to be the best way to do it, as I would not like to play around AppAuth flow, it works quite nicely, and I would have to go a bit deeper to reimplement some stuff that's already handled. There was not easy way to hack around this issue and that's probably for the best :D 

I wanted to avoid adding  UI by handling this with AppAuth, but in the end wrapping everything in additional UI component gives us more control, I'll probably just change `modalPresentationStyle` to be a bit more custom so that users don't see modal transition two times in a row. Just for info I'm implementing it in the SDK and wanted keep UI code to minimum as up until now did not have need for any, if it were basic iOS app I would wrap it into a holder controller and call it a day.

I still think it would be nice to possibly have control over safari, but not sure if it would make sense to actually expose it some way. It's always possible to create custom user agent but it seemed like an overkill in this case.
