### ISSUE TITLE
Resume after authenticating.

### ISSUE THREAD

**Issue by sandronoel** [openid/AppAuth-iOS#239]
After the application has had a previous authentication and the application restarts.
the authState is deserialized, attempting to access web service with the state fails, a normal login is then attempted, the webUI pops up but stalls without presenting the login page.

to resume the webdata needs to be deleted.

**Comment by StevenEWright** [comment]
Have you confirmed there is no problem with your identity provider?

**Comment by sandronoel** [comment]
Yes the identity provider works for other clients (web and native), and it works the "first time" I sign in with appAuth.

The problem occurs the next time the app is launched.

**Comment by sandronoel** [comment]
also, the redirect URL is never called the second time or the first time.

**Comment by julienbodet** [comment]
> the authState is deserialized, attempting to access web service with the state fails

@sandronoel What error do you get?

**Comment by sandronoel** [comment]
No errors, just there with a blank page in the safari embedded browser

**Comment by WilliamDenniss** [comment]
Can you provide a test-case that shows this behavior? E.g. based on the AppAuth sample?

**Comment by WilliamDenniss** [comment]
Closing as unreproducible, please provide a sample if you'd like us to investigate this as a possible bug.
