### ISSUE TITLE
How to do custom flows

### ISSUE THREAD

**Issue by mbogh** [openid/AppAuth-iOS#242]
Hi,

First of all, thanks for this nice project making OpenID much more accessible 🚀 

I am a bit confused about how I should handle custom flows, your examples nicely show how to handle a login flow.

As an example there could be an upgrade flow `https://identity.some.corp.com/client/upgrade...`, can I initiate this via AppAuth or do I need to setup `SFSafariViewController` myself the same way AppAuth does it?

-Morten

**Comment by StevenEWright** [comment]
I am sure I speak for all the (many) contributors who make this project possible when I say thanks for the compliment! 

I am not clear on what you mean when you say “upgrade flow”. Are you referring to the process of requesting additional scopes?

**Comment by mbogh** [comment]
@StevenEWright it was simply me not understanding that the registration, upgrade and verification flows we have, have nothing to do with OpenID.

Have a nice day 😸
