### ISSUE TITLE
SFSafariViewController still has Voice Over focus after login

### ISSUE THREAD

**Issue by shockoe-andrew** [openid/AppAuth-iOS#244]
While doing accessibility testing I've noticed that the SFSafariViewController still has focus for Voice Over after login is completed.

I can get the Voice Over black rectangles to show where the Save Password prompt options would be, but buttons on the new screen draw overtop cannot be selected.  If I select one of the Save Password options then I can then get the Voice Over black rectangles to show where the login form fields or login button would be.

If I close the app and reopen it then I am taken directly to my logged in screen and Voice Over functions as expected.

It seems like the SFSafariViewController is not being dismissed?  This might be what's going on with #236 ?  I am not getting an error in the authorization process.  My redirect_url is {bundle id}://  I've observed this behavior on an iPhone X running iOS 11.3.

Any ideas?

**Comment by WilliamDenniss** [comment]
Do you have any screenshots to share?  I don't think this is related to #236 as it sounds like it's specific to Voice Over. At a guess I think this might be a platform issue (which should be reported to Apple).

**Comment by shockoe-andrew** [comment]
Went to get screenshots and I can no longer reproduce it.  I'll report back if I see it again.  Thanks!
