### ISSUE TITLE
SFAuthenticationSession has been marked deprecated by Apple

### ISSUE THREAD

**Issue by stevekellyhpe** [openid/AppAuth-iOS#247]
https://developer.apple.com/documentation/safariservices/sfauthenticationsession

**Comment by WilliamDenniss** [comment]
Support for the replacement to `SFAuthenticationSession` was added in #246 and is available to try out in the ios12beta branch.

**Comment by WilliamDenniss** [comment]
Support for the replacement to `SFAuthenticationSession` was added in #246 and is available to try out in the [ios12beta](https://github.com/openid/AppAuth-iOS/tree/ios12beta) branch.

**Comment by stevekellyhpe** [comment]
That's great!  Thanks!
