### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by hzalaz** [openid/AppAuth-iOS#25]
Hi!,

Are there any plans on supporting [Carthage](https://github.com/Carthage/Carthage) dependency manager?. I work on this and make a PR if it's something you'd like, should not be a big change since in theory it will only require adding a dynamic framework target.

**Comment by WilliamDenniss** [comment]
No plans currently. Would be very happy to see a pull request!

Can you sign the CLA: https://github.com/openid/AppAuth-iOS/blob/master/CONTRIBUTING.md ?

**Comment by hzalaz** [comment]
@WilliamDenniss signed. Will try to submit a PR as soon I have some minutes to spare.

**Comment by WilliamDenniss** [comment]
Thanks @hzalaz for your contribution!

This is fixed.
