### ISSUE TITLE
Plans for iOS 12?

### ISSUE THREAD

**Issue by LeviDahl** [openid/AppAuth-iOS#251]
SFAuthenticationSession will be deprecated in iOS 12. Is there a plan to address this upcoming deprecation? 

https://developer.apple.com/documentation/safariservices/sfauthenticationsession

Thanks for all your work and support!

**Comment by StevenEWright** [comment]
Please see PR #246 

Cheers!

**Comment by LayMui** [comment]
I got this error when I use
ASWebAuthenticationSession

 No known class method for selector 'ASWebAuthenticationSessionASWebAuthenticationSessionASWebAuthenticationSession'

**Comment by LayMui** [comment]
Lay Mui Toh 
1 minute ago

update  "@react-native-firebase/app": "^16.5.2",

and add the following to the ios/Podfile:

target 'nativeIntegration' do
  config = use_native_modules!
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change false to true and then install pods
    :hermes_enabled => false
  )

  target 'nativeIntegrationTests' do
    inherit! :complete
    # Pods for testing
  end

Enables Flipper.
Note that if you have use_frameworks! enabled, Flipper will not work and
you should disable the next line.
   use_flipper!()

 

in xcode build, 

got this build error:

SFAuthenticationSession' is deprecated: first deprecated in iOS 12.0
Replace 'alloc' with 'ASWebAuthenticationSession'
 

After replace with ASWebAuthenticationSession

it give an error

No known class method for selector 'ASWebAuthenticationSession'
