### ISSUE TITLE
SFAuthenticationSession has been deprecated

### ISSUE THREAD

**Issue by mattio** [openid/AppAuth-iOS#252]
Looks like the docs for [SFAuthenticationSession](https://developer.apple.com/documentation/safariservices/sfauthenticationsession) were updated after WWDC to mark it as deprecated.

The replacement in iOS 12 appears to be [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession).

**Comment by StevenEWright** [comment]
Thanks. This has been asked and answered a couple times now. Please see: https://github.com/openid/AppAuth-iOS/issues/251 for example.
