### ISSUE TITLE
'OIDAuthState.h+IOS.h' file not found

### ISSUE THREAD

**Issue by Strafer14** [openid/AppAuth-iOS#254]
**Describe the bug**
While installing the library in Xcode I fail to build because I'm receiving this message

**To Reproduce**
1. I downloaded the bridging react-native-app-auth and linked it correctly
2. I downloaded the AppAuth-iOS from git as a zip as I don't use cocoapods.
3. I moved the downloaded AppAuth-iOS folder into node-modules/react-native-app-auth
4. I dragged AppAuth.xcodeproj into my XCode Project.
5. I added the AppAuth lib and did all the steps by your guide.
6. I put $(SRCROOT)/../node_modules/react-native-app-auth/AppAuth-iOS/Source in my header search paths.
7. I build the project and I get this error

**Expected behavior**
The project to build successfully.

**Smartphone (please complete the following information):**
 - OS: iOS

Any help would be greatly appreciated.

**Comment by WilliamDenniss** [comment]
You'll need the `AppAuth-iOS/Source/iOS` directory as well from AppAuth, that's where that header lives.  I'd add it as a separate search path, rather than making the existing one recursive, as you likely don't want the other sub-directories like `Mac`.
