### ISSUE TITLE
[Firefox bug] Redirect URI is never called by Firefox and authorization gets stuck

### ISSUE THREAD

**Issue by julienbodet** [openid/AppAuth-iOS#260]
**Are you filing an issue about iOS 12?**
No.

**Describe the bug**
This is not a bug with AppAuth but I'm opening this issue only for tracking the Firefox bug and for informational purpose. The related ticket can be found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1470664).

Authorization flow performed in Firefox using `OIDExternalUserAgentCustomBrowser` doesn't work as Firefox doesn't redirect back to the app that initiated the OAuth flow. 

**To Reproduce**
1. Download the example
2. Modify `doAuthWithAutoCodeExchange` method to use the convenience method `authStateByPresentingAuthorizationRequest:externalUserAgent:callback:` from OIDAuthState specifying `OIDExternalUserAgentIOSCustomBrowser.CustomBrowserFirefox()`
3. Do Authorization
4. Login with your provider and see the redirect is never fired by Firefox

**Expected behavior**
Firefox should redirect back to the app once the login is completed.

**Smartphone:**
 - Device: iPhone 6
 - OS: iOS 12 developer beta 2
 - Browser Firefox 12.1

**Comment by WilliamDenniss** [comment]
Thanks for the cross-post, it's good to track these issues. I believe this was working when I added that feature originally, must be a regression.

**Comment by julienbodet** [comment]
It is now fixed in the master branch of firefox iOS. It'll be included included in the next major release next month (13.0) or might be included in a minor version sooner.

**Comment by WilliamDenniss** [comment]
Great news!

**Comment by julienbodet** [comment]
Firefox 13.0 has now been released. I tested it and it works fine! Closing this issue.
