### ISSUE TITLE
Breaking change in v0.93

### ISSUE THREAD

**Issue by DarkoDamjanovic** [openid/AppAuth-iOS#263]
Hello!

V0.93 introduced a breaking change, but I can't find any informations regarding this change.

- OIDAuthorizationFlowSession was replaced with OIDExternalUserAgentSession
- OIDAuthorizationUICoordinatorIOS was removed

Could you comment on this change? What happened and why?
I can see now an error on SFAuthenticationViewController:

- "Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<SFAuthenticationViewController: 0x7fa4a18ad600>)"

But as I do not really understand the change I also do not know how to react on this. I just can the that on specific use cases SFAuthenticationViewController gets closed automatically. 

Any help is appreciated. Thanks.

Br,
Darko

**Comment by StevenEWright** [comment]
I believe the PR you’re referring to is here: https://github.com/openid/AppAuth-iOS/pull/196

I think OIDAuthorizationUICoordinatorIOS was just renamed to OIDExternalUserAgentCoordinator, not removed. 

We strongly encourage people to use the issue templates provided when creating issues. Is there any way you could close this issue and open a new one (if you find there to be an issue with AppAuth) for the SFAuthenticationViewController problem?

**Comment by WilliamDenniss** [comment]
`OIDAuthorizationUICoordinatorIOS`  was renamed to `OIDExternalUserAgentIOS` to be precise.

I can't reproduce this bug with the samples. Are you making a strong reference to the returned session object?

+1 to Steve's comment, we don't have enough information here to investigate a potential bug.

**Comment by StevenEWright** [comment]
@williamdenniss I noticed when you create an issue on mobile site it doesn’t pre-fill the template :(

**Comment by WilliamDenniss** [comment]
One note on breaking changes, until we cut 1.0.0 (which is soon hopefully) breaking changes are to be expected. You can always go back a release if you don't want the changes though.

**Comment by DarkoDamjanovic** [comment]
Thanks! The explanations here were enough for me to solve everything:
https://github.com/openid/AppAuth-iOS/pull/196

The problem with the  SFAuthenticationViewController just happened because I had to remove the OIDAuthorizationUICoordinatorIOS and was not aware that this was just a rename.
