### ISSUE TITLE
Validating issuedAt claim is within +/- 5 mins of the current time causes a problem with AzureAD

### ISSUE THREAD

**Issue by admeister** [openid/AppAuth-iOS#264]
After updating to the latest version of the AppAuth framework for my iOS app, it appears there is now a check on the issuedAt claim, just after you've acquired a new token, to make sure it's within 5 minutes of the current time. 

After spending a lot of time debugging this, it appears Microsoft AzureAD always sets the issuedAt claim to 5 minutes before you actually requested it. This therefore means that tokens are never valid:

```
// OIDAuthorizationService.m
// Lines 477 - 488
NSTimeInterval issuedAtDifference = [idToken.issuedAt timeIntervalSinceNow];
if (fabs(issuedAtDifference) > 300) {     // <-- 300 seconds/5 minutes check
  NSError *invalidIDToken =
    [OIDErrorUtilities errorWithCode:OIDErrorCodeIDTokenFailedValidationError
                     underlyingError:nil
                         description:@"Issued at time is more than 5 minutes before or after "
                                      "the current time"];
  dispatch_async(dispatch_get_main_queue(), ^{
    callback(nil, invalidIDToken);
  });
  return;
}
```

To reproduce, use any Azure AD to authenticate against (I've tried with 3 completely separate ones with different users).

Could the 5 minute window be extended? Maybe to 6 minutes?

**Comment by WilliamDenniss** [comment]
For the record, this is the rule we are implementing here:

http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

> 3.1.3.7.  (10)
> The iat Claim can be used to reject tokens that were issued too far away from the current time, limiting the amount of time that nonces need to be stored to prevent attacks. The acceptable range is Client specific.

The nonce storage issue is not a problem for AppAuth (at most one pending request is "stored" in memory), but it seems like good practice to reject old tokens.

I'm surprised to see Azure AD back-date their tokens, I'm guessing it's (ironically) to avoid clock-skew issue on clients that validate it.

I don't see an issue with doubling the time-range that we accept.

**Comment by admeister** [comment]
Surprised no one has raised this bug before me. Looks like this change has been in a while.

Either double the check to 10 mins, or somehow allow it to be configurable works equally well for me.

**Comment by WilliamDenniss** [comment]
Could allow it to be configurable, but to me this is something that *should* be one-size-fits-all. Like I don't see a legitimate reason for accepting 1 day old tokens, for example. 

The spec doesn't define "too far away", but 10m doesn't seem "too far" to me, so I think we may as well double it.

**Comment by admeister** [comment]
Great turnabout on this issue. Thanks @WilliamDenniss !

**Comment by xerners** [comment]
Feel free to ping me on issues like these and we can help. What @WilliamDenniss guessed is correct it is to avoid clock skew issues.

**Comment by cassianodialpad** [comment]
@WilliamDenniss I'm facing this issue sometimes when the iOS device DateTime settings timezone are set to manual (even though with the correct timezone). I couldn't find a reliable way to reproduce it, but while debugging I could see that the idToken.issuedAt [here](https://github.com/openid/AppAuth-iOS/blob/master/Source/OIDAuthorizationService.m#L621) is in a different timezone than the system, causing the value to be way larger than 10min. Any ideas?

**Comment by MatthewScholefield** [comment]
@cassianodialpad Actually, I'm experiencing the same issue myself as a user of an app that uses this library. My email client randomly stopped sending emails because I set my phone to a manual time an hour ahead. Is there a better wat to implement this so that it doesn't rely on client server time synchronization?

**Comment by cassianodialpad** [comment]
@MatthewScholefield Unfortunately I didn't find any way to fix this issue. A workaround that seemed to work for our customers was simply set the phone to automatic and then back to manual (on iPhone).
