### ISSUE TITLE
Version 0.94 cartfiles contain local links

### ISSUE THREAD

**Issue by seanmcneil** [openid/AppAuth-iOS#270]
https://github.com/openid/AppAuth-iOS/commit/70c1d55c4955a2535870ac9d8c3b555820ab7a99#diff-6744b417b728d1c1dc2ee954249fffe8

**Comment by WilliamDenniss** [comment]
Thanks @seanmcneil, this was corrected.

**Comment by seanmcneil** [comment]
np @WilliamDenniss  - thanks for the quick fix
