### ISSUE TITLE
Unknown type name 'OIDAuthorizationFlowSession'

### ISSUE THREAD

**Issue by EnderXenocida** [openid/AppAuth-iOS#279]
I have the problem with the last version with Carthage after #import <AppAuth/AppAuth.h> in AppDelegate. 

I'm using similar code that other app where I have used pods instead of Carthage.

- with
@property (nonatomic, strong, nullable) id<OIDAuthorizationFlowSession> currentAuthorizationFlow;
- message
Type argument 'OIDAuthorizationService' must be a pointer (requires a '*')
Type arguments cannot be applied to non-class type 'id'

- with 
@property (nonatomic, strong, nullable) id<OIDAuthorizationFlowSession*> currentAuthorizationFlow;
- message
Type arguments cannot be applied to non-class type 'id'

Could you please help me with that?

**Comment by WilliamDenniss** [comment]
OIDAuthorizationFlowSession was removed in HEAD. We're removing all deprecated methods in preparation for cutting the 1.0.0 release. Point Carthage at the latest [release](https://github.com/openid/AppAuth-iOS/releases), resolve all deprecation warnings before using HEAD (or the future 1.0.0 release).

Specifically you ned to change `OIDAuthorizationFlowSession` to:

https://github.com/openid/AppAuth-iOS/blob/b4ca39a38f0d991bd17c56ebd01756a41da54061/Examples/Example-iOS_ObjC/Source/AppDelegate.h#L35

And change the method to `resumeExternalUserAgentFlowWithURL`:

https://github.com/openid/AppAuth-iOS/blob/b4ca39a38f0d991bd17c56ebd01756a41da54061/Examples/Example-iOS_ObjC/Source/AppDelegate.m#L52-L54

**Comment by EnderXenocida** [comment]
Thanks!
