### ISSUE TITLE
OIDExternalUserAgentIOS.dismissExternalUserAgentAnimated:completion: doesn't call completion when no current auth flow

### ISSUE THREAD

**Issue by julienbodet** [openid/AppAuth-iOS#280]
**Are you filing an issue about iOS 12?**
No.

**Describe the bug**
`OIDExternalUserAgentIOS.dismissExternalUserAgentAnimated:completion:` doesn't execute completion block if there is no authorization flow in progress (`_externalUserAgentFlowInProgress` is `false`). I believe the completion block should be called in every case and could maybe return a boolean to tell the caller if the authorization agent was actually dismissed or not (`true` if a flow was in progress, `false` otherwise).

```
- (void)dismissExternalUserAgentAnimated:(BOOL)animated completion:(void (^)(void))completion {
  if (!_externalUserAgentFlowInProgress) {
    // Ignore this call if there is no authorization flow in progress.
    return;
  }
  
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wpartial-availability"
  SFSafariViewController *safariVC = _safariVC;
  SFAuthenticationSession *authenticationVC = _authenticationVC;
#pragma clang diagnostic pop
  
  [self cleanUp];
  
  if (@available(iOS 11.0, *)) {
    [authenticationVC cancel];
    if (completion) completion();
  } else if (@available(iOS 9.0, *)) {
    if (safariVC) {
      [safariVC dismissViewControllerAnimated:YES completion:completion];
    } else {
      if (completion) completion();
    }
  } else {
    if (completion) completion();
  }
}
```

I noticed this completion block was not called while calling `dismissExternalUserAgentAnimated:completion:` because I wanted to cancel the authorization in a certain case and execute some code after it is actually cancelled or not (if no flow in progress). The preferred way to do would be to call `OIDExternalUserAgentSession.cancel()` but this method does not currently allow to pass a completion block to execute once the authorization is cancelled. That said, adding a completion to this cancel method would be nice too.

**Comment by WilliamDenniss** [comment]
Makes sense that a block named "completion" should be called on completion in every case I guess.

Do you think the caller would need to know whether or not something was actually dismissed? (i.e is the BOOL even needed?)

**Comment by julienbodet** [comment]
Currently `dismissExternalUserAgentAnimated:completion` is called from `OIDAuthorizationService.cancel`:
```
- (void)cancel {
  [_externalUserAgent dismissExternalUserAgentAnimated:YES completion:^{
      NSError *error = [OIDErrorUtilities errorWithCode:OIDErrorCodeUserCanceledAuthorizationFlow
                                        underlyingError:nil
                                            description:@"Authorization flow was cancelled."];
      [self didFinishWithResponse:nil error:error];
  }];
}
```

But if cancel is called while there is no running authorization flow, and completion is executed by `dismissExternalUserAgentAnimated:completion:`, then as you can see in the snippet above, `[self didFinishWithResponse:nil error:error]` will be called. But we want to call this only if an authorization flow was effectively dismissed. That is the reason of the boolean I proposed. If the `cancel` method is the only need for this, I guess we can find another way to check directly in the `cancel` method for an authorization flow in progress.

**Comment by julienbodet** [comment]
After thinking about that, I realize the boolean I propose in my previous comment is not needed because `cancel` is called on `OIDExternalUserAgentSession`, and a user should not keep a reference on a session that is not in progress. So if that happens, the problem is on the developer side.

I'll make a pull request adding a completion block to the `cancel` method, and also call the completion block in any case for the `dismissExternalUserAgentAnimated:completion`.
