### ISSUE TITLE
Support for customizing SFSafariViewController presentation

### ISSUE THREAD

**Issue by maxsz** [openid/AppAuth-iOS#29]
Hi everyone,

we need to customize the modal presentation of the SFSafariViewController. Specifically setting the `modalPresentationStyle` and `modalTransitionStyle`. I've created a PR (#28) with a sample of how this could be achieved.

We'd greatly appreciate if you could add this kind of support.

Thanks 🙏,
Max

**Comment by WilliamDenniss** [comment]
Seems like a reasonable enhancement. See my comments in PR.

**Comment by WilliamDenniss** [comment]
We have two PRs, #28 and #34 to address this.  I put my review notes in #28. Please reply in that PR if you have any comments, let's try and get this resolved soon :)

**Comment by WilliamDenniss** [comment]
This feature was implemented, here's an example:

1. Create your own Safari factory. 

This example sets the tint color to 55% black, replacing the default blue tint.

```
@interface CustomSafariViewControllerFactory : NSObject<OIDSafariViewControllerFactory>
@end

@implementation CustomSafariViewControllerFactory
- (SFSafariViewController *)safariViewControllerWithURL:(NSURL *)URL {
  SFSafariViewController *safariViewController =
      [[SFSafariViewController alloc] initWithURL:URL entersReaderIfAvailable:NO];
  safariViewController.preferredControlTintColor = [UIColor colorWithWhite:0.45f alpha:1.0f];
  return safariViewController;
}
@end
```

2. Set an instance of your factory before you use AppAuth.

```
[OIDAuthorizationUICoordinatorIOS setSafariViewControllerFactory:[[CustomSafariViewControllerFactory alloc] init]];
```

**Comment by vidoree** [comment]
Hi, I am new to objective-c. I forked this project and updated AppAuth to 1.4.0 version and trying to change Safari's tint color but te example code not working. Can you help me, please?
