### ISSUE TITLE
Very awkward for developers using appauth to use hybrid flow

### ISSUE THREAD

**Issue by jogu** [openid/AppAuth-iOS#292]
**Describe the bug**

It's very awkward for library users to use hybrid flow.

**To Reproduce**

If you set the response_type to code id_token, appauth throws an assert:

https://github.com/openid/AppAuth-iOS/blob/master/Source/OIDAuthorizationRequest.m#L134

which references:

https://github.com/openid/AppAuth-iOS/issues/98

which says:

> After discussing id_token support with @ve7jtb, we agreed that it could be possible to use code id_token in a secure way with AppAuth, if you validate the ID Token, verify the c_hash, and only use the ID Token after the code is exchanged successfully with PKCE verification.

I agree with this comment. I've implemented id token signature verification and c_hash verification in my app in exactly this way.

and:

> It's not currently supported and there are no plans to do so. Hybrid (and implicit) negate the PKCE protection required by RFC 8252 so it's generally not recommended for native apps.

I'm not sure I understand this comment (you can use hybrid and PKCE together, and FAPI part 2 requires this for public clients.)

The actual assert was added as part of https://github.com/openid/AppAuth-iOS/pull/117

**Expected behavior**

AppAuth should allow library users to use the hybrid flow as library users can implement id_token and c_hash verification. As far as I can see it's currently either awkward or impossible to do this without changing the AppAuth source code, as this assert is in the designated initialiser for OIDAuthorizationRequest.

**Additional context**

FAPI requires the use of the hybrid flow, so it's not currently possibly to make a FAPI compliant OIDC client without modifying appauth.

**Comment by jogu** [comment]
I don't currently have a suggestion on how to fix this, other than simply removing the assert and uncommenting the line in initWithCoder.

That does seem okay to me though, as there is already code that leaves the token exchange to the application developer when using a response type other than code:

 https://github.com/openid/AppAuth-iOS/blob/master/Source/OIDAuthState.m#L141 

It may be worth tweaking the related comment ( https://github.com/openid/AppAuth-iOS/blob/master/Source/OIDAuthState.m#L162 ) to say something along the lines of "Either the code is not for this client (ie. will be sent to a web service for ultimate exchange) or the code is for this client and, for security reasons, the application developer must verify the id_token signature and c_hash before calling the token endpoint."

If this approach sounds okay I should be able to prepare a pull request.

**Comment by WilliamDenniss** [comment]
Happy to consider a PR that changes this behavior, your points make sense to me.

I think base AppAuth should continue to ignore the id_token coming in from the authorization response (if any), do you agree? (this would leave you to process it how you like on your side). The reason being that we don't perform signature validation, so only ID Tokens coming from the token endpoint over TLS are safe for AppAuth to consume.

Also I think we should still assert on any combination that isn't `code id_token`. i.e. `code token` doesn't make sense to me in the native app context, nor does `token`.

**Comment by jogu** [comment]
Thanks William!

> I think base AppAuth should continue to ignore the id_token coming in from the authorization response (if any), do you agree? 

Yes, definitely agree on this point, which also means AppAuth should continue (as the code already does) to leave calling the token endpoint to the application in this case - the application can then call the token endpoint once it is happy the id token is valid and the c_hash correct.

> Also I think we should still assert on any combination that isn't code id_token. i.e. code token doesn't make sense to me in the native app context, nor does token.

This also sounds sensible to me.

**Comment by WilliamDenniss** [comment]
Hey @jogu, it was good working with you on these improvements. How is AppAuth looking for your use-case now?

This issue was auto-closed, can re-open if there's more to track.

**Comment by jogu** [comment]
Hi @WilliamDenniss  - yes, thanks for your help with all these.

Hybrid (and all the other things I'd mentioned in #290) are working fine in our app as best I can tell - I tested using the master branch of AppAuth iOS after you'd merged the last of my pull requests. This means we can use AppAuth in our project without needing to modify AppAuth, which is a great step forward and I believe we've managed to create a FAPI part 2 compliant RP in this way.

It'd still be nice to build more of the functionality into AppAuth, but unfortunately I don't have the budget to spend any more time on that right now.

**Comment by stgarrity** [comment]
@jogu and @WilliamDenniss, apologies if this is a dumb question, but #298 doesn't seem to solve the URL fragment issue that was discussed in #88 ... I'm trying to use AppAuth for a Google hybrid "code id_token" flow and running into the same state mismatch error when the redirect url comes back ...:/oauth_redirect#state= instead of redirect?state= (which per @leastprivilege's comment on #88 is per spec). This seems to all occur internal to AppAuth in OIDExternalUserAgent.presentExternalUserAgentRequest; is there a different way I should be using it that I'm missing? If it's a bug, happy to work on a patch for it (presumably in OIDURLQueryComponent)

**Comment by jogu** [comment]
I worked around this in my app though this isn't really a good way to do it:

```
+ (BOOL)resume:(NSURL *)url
{
    NSString *urlStr = url.absoluteString;
    // workaround for appauth not fully supporting hybrid flow - see https://github.com/openid/AppAuth-iOS/issues/88
    urlStr = [urlStr stringByReplacingOccurrencesOfString:@"#" withString:@"?"];
    NSURL *newUrl = [NSURL URLWithString:urlStr];

    if ([currentAuthorizationFlow resumeExternalUserAgentFlowWithURL:newUrl]) {
        currentAuthorizationFlow = nil;
        return YES;
    }
    return NO;
}
```

I did look at making a change to AppAuth, but it looked very awkward to do correctly as AppAuth's current supported OS versions means some of the OS provided URL functionality you'd want to use isn't available.

**Comment by stgarrity** [comment]
@jogu thanks, I tried that when I saw your earlier comment, but that callback isn't getting called for me. I think on iOS 12+, AppAuth uses ASWebAuthenticationSession, which manages its own callback logic that bypasses the URL handler(s)? (I have confirmed that my app does call the url handler from eg the browser, but not on authenticating). 

Are you using an earlier iOS version, or is there something I'm missing on intercepting ASWebAuth callbacks?

**Comment by jogu** [comment]
Ah yes, actually on that product the app always used a SFSafariViewController (for various reasons), so it would behave differently.

You could probably achieve the same effect as I was [without modifying appauth] by creating your own version of OIDExternalUserAgentIOS.m

**Comment by stgarrity** [comment]
@jogu thanks, great point ... I got that working pretty quickly and you’re right, not ideal but it solves the problem. Given that we’re actually working in SwiftUI for this, though, I think I’ll just drop the whole framework and go direct to ASWebAuthenticationSession. Going to use Google’s client-to-server auth flow (where the client passes a server_code up that can be exchanged for a server-secreted-keyed access token) and haven’t found support for that yet. Thanks for your help!

**Comment by jogu** [comment]
Great!

I'm not familiar with that particular flow (I think it's just an extra step you'd do after AppAuth has finished?), but if you move away from AppAuth beware that you'll need to be more careful about keeping things secure. (e.g. AppAuth is automatically doing PKCE for you, so without AppAuth you're likely by default vulnerable to various mixup attacks unless you implement PKCE yourself.)

**Comment by stgarrity** [comment]
It’s not well-documented but Google implements it in their GoogleSignIn pod...unfortunately that’s not OSS or particularly actively maintained, and doesn’t work under Catalyst, so I’m trying to stick with one codebase as much as possible between Mac/iPad/iPhone. It’s just another parameter that’s exposed in the /token response, but not plumbed through AppAuth yet AFAIK.

Yep, just finished PKCE :) I don’t love implementing it myself but that + state checking is all you need and it reduces dependencies pretty dramatically.

**Comment by sashaweiss** [comment]
@WilliamDenniss, wanted to revive this thread since I think I'm in the same boat. I'm trying to use the hybrid flow with an Azure app registration, and ran into the `#` URL issue. I'm going to try and use the `OIDExternalUserAgentIOS` route as recommended above to replace the hash with a `?`, but wanted to see if that seems like a reasonable workaround?

I'm extremely new to OAuth/OpenID, so for context my use case is as follows. We have a service for which we want to use an OpenID provider to authenticate our users, so I'm trying to implement the hybrid flow to get an `id_token` on the client that can then be sent up to our service. Service-side, we'd then validate the signature on that `id_token` to authenticate the user.

As a sanity check, is there anything out of line in that plan that might make this question irrelevant? Or should I go ahead with an `OIDExternalUserAgentIOS` workaround?

**Comment by sashaweiss** [comment]
Just kidding - did some more reading and realized there were some gaps in my understanding! Got it working with the `code` flow - my problem was that I was expecting an `id_token` before calling `performActionwithFreshTokens`. So I was seeing a call to `/authorize` without an `id_token` and getting confused, but have since come to understand that there's a subsequent call to `/token` from which the `id_token` comes back.

So - leaving this comment here for posterity, but I'm all good and things work as expected. Was just getting ahead of myself!

**Comment by sw-tt-kirtanvaghela** [comment]
> performActionwithFreshTokens

I am getting error "State mismatch|,
I have tried to useOIDExternalUserAgent. It open new page in browser . 
My confusion is how to give call back of browser to app?

`let agent = OIDExternalUserAgentIOSSafariViewController(presentingViewController: self)`

**Comment by sw-tt-kirtanvaghela** [comment]
> performActionwithFreshTokens

` let agent = OIDExternalUserAgentIOSSafariViewController(presentingViewController: self)`

After using this line auth screen open in safari. 
But after Authentication is completed does not redirect to app back.
How to get callback on App back with token info?
I have used two redirect URL for this
com.bundle id geenrated 
and https url .

**Comment by ywsang** [comment]
@sw-tt-kirtanvaghela Could you please open a new issue and provide more details on the flow that you're using? For instance, which method are you calling and passing the `OIDExternalUserAgentIOSSafariViewController` to? From your comments it's unclear to me what you are attempting to do.

**Comment by sw-tt-kirtanvaghela** [comment]
@ywsang  There are already some issues with state mismatch so not created new one. Have review but still issue is same.

I am trying to login with hybrid flow. With response type "code id_token". But in response the error is "state mismatch".
Here is my code.
I have add redirect URL in URL types in plist.

`  let issuer = URL(string:<URL>)!
        
        OIDAuthorizationService.discoverConfiguration(forIssuer: issuer) { configuration, error in
            guard configuration != nil else {
            print("Error retrieving discovery document: \(error?.localizedDescription ?? "Unknown error")")
            return
            }
            let redirectURL = URL(string: REDIRECT_URL)!
            print(redirectURL)

            let request = OIDAuthorizationRequest(configuration: configuration!, clientId: CLIENT_ID, scopes: ["openid","content.api.fullaccess"], redirectURL: redirectURL, responseType:"code id_token", additionalParameters: nil)

        // performs authentication request
        print("Initiating authorization request with scope: \(request.scope ?? "nil")")
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
            print("OIDAuthState request \(request)")
            
        appDelegate.currentAuthorizationFlow =
                OIDAuthState.authState(byPresenting: request, presenting: self) { authState, error in
              if let authState = authState {
                print("Fetch user info")
              }else{
                 print("Authorization error: \(error?.localizedDescription ?? "Unknown error")")
               }
`
as @sashaweiss answer i tried with OIDExternalUserAgentIOS

` appDelegate.currentAuthorizationFlow = OIDAuthState.authState(byPresenting: request2, externalUserAgent: agent, callback: { authState, error in
  if let authState = authState {
                print("Fetch user info")
              }else{
                 print("Authorization error: \(error?.localizedDescription ?? "Unknown error")")
               }
`
can you please tell me where i am wrong or anything else i have to do here.
Thanks

**Comment by ywsang** [comment]
@sw-tt-kirtanvaghela Based on conversations in this issue above (starting in https://github.com/openid/AppAuth-iOS/issues/292#issuecomment-575993626) and in the referenced issue #88, it seems that the suggested workaround is that you'd have to have your own version of `OIDExternalUserAgentIOS`: 
 
> You could probably achieve the same effect as I was [without modifying appauth] by creating your own version of OIDExternalUserAgentIOS.m
(from https://github.com/openid/AppAuth-iOS/issues/292#issuecomment-576478836)

**Comment by J6ey** [comment]
@sw-tt-kirtanvaghela  make sure you've included the path of that redirect URL in the /.well-known/apple-app-site-association
