### ISSUE TITLE
iOS 12 Support Timeline

### ISSUE THREAD

**Issue by CraigLn** [openid/AppAuth-iOS#293]
Hello, 

I was just curious if there was a timeline on when to expect an iOS 12 pod that uses [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession?language=objc).

Thanks!

**Comment by WilliamDenniss** [comment]
`1.0.0.beta1` is out. It includes iOS 12 support, and requires Xcode 10. 🚀
