### ISSUE TITLE
AuthenticationServices/AuthenticationServices.h file not found.

### ISSUE THREAD

**Issue by nkbem** [openid/AppAuth-iOS#302]
Hi guys,

I am new to this library, I tried to run the iOS app from the examples and I got this error.

AuthenticationServices/AuthenticationServices.h' file not found. 

I need to run this project in order to see how the library works. 

Thanks in advance.

**Comment by jogu** [comment]
You need to build using the latest Xcode (ie. Xcode 10), or use an older version of AppAuth. AIUI AppAuth is always requires the latest version of Xcode.

**Comment by WilliamDenniss** [comment]
Correct, AppAuth requires the latest dev tools (but still supports targeting all the way back to iOS 7!).

If you can't upgrade, grab the last release before XCode 10 came out (0.94.0).
