### ISSUE TITLE
Yahoo throwing an error in 0.94.0 release

### ISSUE THREAD

**Issue by tbelaire** [openid/AppAuth-iOS#305]
We've updated to 0.94.0, and now when we make requests to Yahoo, it's started to include: 

    &code_challenge_method=S256

But then Yahoo's login screen shows an error, and says:

    Developers: Please specify valid code challenge and code challenge method and submit again 

Is there an easy way to not sent the `code_challenge_method`?

**Comment by WilliamDenniss** [comment]
hmm, is Yahoo not spec compliant with PKCE?

> Is there an easy way to not sent the code_challenge_method?

Yes there is!

Just call the designated initializer for OIDAuthorizationRequest, and pass `nil` for codeVerifier, codeChallenge and codeChallengeMethod. That will remove PKCE handling entirely.

https://github.com/openid/AppAuth-iOS/blob/fadb76d2da6958bd3c75703fc38bb91d40fa790f/Source/OIDAuthorizationRequest.h#L227-L258

**Comment by tbelaire** [comment]
I see we are calling
https://github.com/openid/AppAuth-iOS/blob/fadb76d2da6958bd3c75703fc38bb91d40fa790f/Source/OIDAuthorizationRequest.m#L184

Which is actually forcing    `codeChallengeMethod` to `OIDOAuthorizationRequestCodeChallengeMethodS256`.

**Comment by tbelaire** [comment]
I'll try and switch off the deprecated method, since I see you've already removed it.

**Comment by tbelaire** [comment]
Also, your deprecation notice had a typo in it, saying AuthState instead of AuthorizationRequest.  That threw me for a loop looking in AuthState instead.   Didn't see the addition of `nonce` in the middle for a while.

Not like you can fix that now though since you've already deleted it.

**Comment by tbelaire** [comment]
Switching off the deprecated method fixed it!

**Comment by WilliamDenniss** [comment]
> Which is actually forcing codeChallengeMethod to OIDOAuthorizationRequestCodeChallengeMethodS256.

Yes. For the record, this is what the [spec](https://tools.ietf.org/html/rfc7636#section-4.2) requires (I know because I wrote that section): `If the client is capable of using "S256", it MUST use "S256", as "S256" is Mandatory To Implement (MTI) on the server.`

**Comment by tbelaire** [comment]
Eh, this breaks Yahoo, and was a surprising change on a version bump.  Especially since the other non deprecated version of the function does not force S256.

Thanks for the replies!  Everything is working great now.
