### ISSUE TITLE
INVALID_ARGUMENT errors showing up

### ISSUE THREAD

**Issue by guidedways** [openid/AppAuth-iOS#306]
I'm not sure if this is related to issue #288 but I'm now seeing this all of a sudden on an app that's been unchanged for a few months. Notice the `%20` in the scope below, could this be tripping Google up again? Can someone please get Google to stop making these changes without thinking through? This is the third time in 12 months that our apps have stopped working all of a sudden.

```
OAuth: request failed: <OIDTokenRequest: 0x6100008b6200, ClientID: 506211136043-6tslfe4ok4ib6faeh9i07qgo1f39uenr.apps.googleusercontent.com, Secret? 24 Scope: email https://www.googleapis.com/auth/carddav, Grant: refresh_token, request: <URL: https://www.googleapis.com/oauth2/v4/token, HTTPBody: grant_type=refresh_token&scope=email%20https://www.googleapis.com/auth/carddav&refresh_token=1/G3BaNEf4R0QiP3O-8lmP1nxz0xW8KmKlSmlgvvuMsEC&client_id=503211136043-6tslfe4ok4ib6faeh9i02qgo1f39uenr.apps.googleusercontent.com&client_secret=OgHS5U0O5dVn0i96t1acNk1e>> (<NSMutableURLRequest: 0x618000015ca0> { URL: https://www.googleapis.com/oauth2/v4/token }) => <NSHTTPURLResponse: 0x60000063f380> { URL: https://www.googleapis.com/oauth2/v4/token } { status code: 400, headers {
    "Cache-Control" = private;
    "Content-Encoding" = gzip;
    "Content-Length" = 129;
    "Content-Type" = "application/json; charset=UTF-8";
    Date = "Wed, 26 Sep 2018 22:44:56 GMT";
    Server = ESF;
    Vary = "Origin, X-Origin, Referer";
    "alt-svc" = "quic=\":443\"; ma=2592000; v=\"44,43,39,35\"";
    "x-content-type-options" = nosniff;
    "x-frame-options" = SAMEORIGIN;
    "x-xss-protection" = "1; mode=block";
} } (server error: Error Domain=org.openid.appauth.remote-http Code=400 "{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
" UserInfo={NSLocalizedDescription={
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
})
2018-09-26 15:44:56.301 -2- OAuth: underlying json error: {
    error =     {
        code = 400;
        message = "Request contains an invalid argument.";
        status = "INVALID_ARGUMENT";
    };
}
```

**Comment by guidedways** [comment]
@WilliamDenniss would appreciate your help on this, this has only started showing up earlier today and only for a hand-full of users. This error is in fact causing the app to crash given AppAuth seems to be trying to parse a `NSDictionary` as a string here (from Crashlytics):

```
OIDErrorUtilities.m line 89
+[OIDErrorUtilities OAuthErrorWithDomain:OAuthResponse:underlyingError:]
```

**Comment by guidedways** [comment]
I spoke too soon - we're now being flooded with support emails regarding this issue, complaining that the app is constantly crashing.

Sigh.

**Comment by triton3** [comment]
We are seeing the same issue since past 30 mins. App constantly crashes with Gmail, and the crash report mentions the same error stated above (looks like the crash is because OIDErrorUtilities is expecting a string to append to description, but it turns out to be a dictionary).

But the underlying reason for `INVALID_ARGUMENT` is still unclear...

**Comment by guidedways** [comment]
@triton3 I logged on to Google's Console and can see that the OAuth Screen says 'Needs Verification' - I don't recall seeing that or going though that before. Perhaps they've blocked the OAuth Screen and so it won't verify? Can you see if the same applies to you?

**Comment by triton3** [comment]
@guidedways I checked but I dont see any such message on the console for our account

**Comment by guidedways** [comment]
I really hope we can figure out what's going on. So far I've got my inbox filled with 200 emails in the past 1 hour and more than 10k crash reports, not to mention I've had a sleepless night.

**Comment by wangw469** [comment]
@guidedways  https://github.com/wangw469/AppAuth-iOS/commit/5339ec23a9176dc2658cbb101fbb1ca68cc717ec

**Comment by guidedways** [comment]
Oh my God... @wangw469 you're right! this worked!

```
//    [httpHeaders setObject:authValue forKey:@"Authorization"];
    
    [bodyParameters addParameter:kClientIDKey value:_clientID];
    [bodyParameters addParameter:kClientSecretKey value:_clientSecret];
```

This reminds me of the issue I raised 8 months ago, it looks like Google broke something for sure. See #226

**Comment by guidedways** [comment]
@iainmcgin Can you get in touch with your contact at Google again? I recall you did that for issue #226 as a similar patch fixed the bug for us, but then something happened and Google 'fixed it' again. This is a serious issue

@WilliamDenniss please can we get a resolution on this once and for all? Is the client secret and id in the body or in the header or both?

**Comment by guidedways** [comment]
@wangw469 Thanks again, although this does fix the issue, I'm super reluctant patching it this way and posting an update out to hundreds of thousands of users, only to have this broken again if and when Google fixes it.

We really need this resolved rather quickly.

**Comment by WilliamDenniss** [comment]
Yes, that is the fix https://github.com/WilliamDenniss/AppAuth-iOS/commit/d0c0359e560452851e4666bc7900d4346b872753

I regret there was a regression @guidedways. I believe it's always been possible to send the client authentication in the request body and it would have avoided both incidents of this. AppAuth doesn't do this by default, as the Basic Auth header should work – but I think it would be OK for you to apply that patch.

**Comment by wangw469** [comment]
@guidedways I think it's google to blame for this crash. They should notify developer if they're trying to change server API. Especially AppAuth-iOS is their recommend implementation for iOS.

You can found google's api document here:
https://developers.google.com/identity/protocols/OAuth2InstalledApp#exchange-authorization-code

In rfc6749 Client Password section(https://tools.ietf.org/html/rfc6749#section-2.3.1)
It wrote:
> Alternatively, the authorization server MAY support including the
>    client credentials in the request-body using the following
>    parameters:
> 
>    client_id
>          REQUIRED.  The client identifier issued to the client during
>          the registration process described by Section 2.2.
> 
>    client_secret
>          REQUIRED.  The client secret.  The client MAY omit the
>          parameter if the client secret is an empty string.

**Comment by WilliamDenniss** [comment]
From your sample in the original post, it looks like you were already passing client_secret in the post body, so the delta for you would just be not also sending the secret in the header.

In fact, it's a bit dangerous to do *both* (i.e. send the header, and the body params), I would recommended just picking one option.

**Comment by WilliamDenniss** [comment]
I filed #307 to fix the crash issue.  That was caused by AppAuth thinking the error response was an OAuth error response (as it was JSON that contained an "error" key), however it was in fact just a generic JSON error message that happened to have an "error" key.

**Comment by guidedways** [comment]
Thanks guys, much appreciated! I'll then proceed to applying the patch with confidence and prepare for a rough weekend, replying to now 300 emails and counting.

**Comment by rhwu** [comment]
Thanks for the fix, appreciated!

William, is it possible to let Google know about this so that maybe them can keep the old behavior of a little bit longer? It takes time to roll out update on app store.

**Comment by rhwu** [comment]
@WilliamDenniss Got it, thanks for explaining!

**Comment by wangw469** [comment]
@WilliamDenniss @guidedways  Seems like Google has fix this problem.
I can now login with _clientSecret & _clientID in HTTP header.(Basic Auth)

**Comment by guidedways** [comment]
@WilliamDenniss thanks for your prompt replies and patches! After tonight's ordeal, I can only pray they stop tweaking whatever they keep tweaking every few months, or at least do it and release it as a new version of the API. Repeatedly breaking existing implementation without providing support for backward compatibility just sounds sloppy - that's something I only expect from myself.

**Comment by WilliamDenniss** [comment]
The fix went live just before midnight Pacific Time. Thanks all!

@guidedways, I hear you.

**Comment by WilliamDenniss** [comment]
AppAuth 0.95.0 includes a fix to the issue which cause the crash yesterday, also tightens up some handling around the "scope" param during token refresh to guard against future changes (AppAuth was sending the scope param unnecessarily during refresh). I highly recommend updating to this version.

Note that you will need to carry your own patches for client authentication if you wish to do it in the HTTP body.
