### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by danipralea** [openid/AppAuth-iOS#311]
Hello!
Firstly, thank you for the library and the work you have put in it!

Is there such a capability to open the register page directly?
I have the login, which works fine, but I also have a request to add a register functionality as well and I tried a lot lately to find such a functionality.

Thanks,
Dan.

**Comment by WilliamDenniss** [comment]
The authorization server can do anything it wants during the authorization flow, including registering the user.

If you try the included example, with Google as the IdP, click "Use another account", and "create account", you'll be able to register an account.

**Comment by danipralea** [comment]
@WilliamDenniss unfortunately I cannot build the example app:
<img width="1123" alt="screenshot 2018-10-11 16 47 29" src="https://user-images.githubusercontent.com/768893/46808590-6427d580-cd75-11e8-939b-ab2e7821a5f4.png">

is there a code snippet you can share that I can use in order to achieve reaching the registration page? 
Cause I'm not sure from your response if it's a job for me or the server.

Thanks.

**Comment by WilliamDenniss** [comment]
AppAuth requires Xcode 10, judging from that error it looks like you're not using Xcode 10. If you need a version that works with Xcode 9, try the 0.95.0 release. 

Generically speaking, a server can potentially do a registration during a OAuth flow, that I can tell you. 

I'm not sure I have the context to advise you how to design your app however, I imagine this would be something you would design together with the server team.
