### ISSUE TITLE
IdToken not refreshed on performActionWithFreshTokens

### ISSUE THREAD

**Issue by pgorzelany-objectivity** [openid/AppAuth-iOS#316]
Hi,

I have a question about the IdToken refresh mechanism. In my code when I am making api calls I need to add the IdToken as a header. The IdToken has an expiration date and when it expires, it does not get refreshed when calling performActionWithFreshTokens.

Is this the correct behavior? I would assume we always get a valid (not expired) token in performActionWithFreshTokens?

**Comment by WilliamDenniss** [comment]
This behavior is up to your IdP. AppAuth will return the ID Token it received during the latest token endpoint response (typically, the refresh response), or the original ID Token it received during authorization if none was received on the token response.

https://github.com/openid/AppAuth-iOS/blob/2a7a6754fd5b612aa554fa56d6e7853218e2d84f/Source/OIDAuthState.m#L321-L327
