### ISSUE TITLE
Release 0.95.0?

### ISSUE THREAD

**Issue by tamasprezi** [openid/AppAuth-iOS#317]
Hi, I see there is a 0.95.0 tag in the repo but it's not yet merged to master. Are there any blockers to that? We are depending on the new release for the Xcode 10 migration. Could you complete the release or give an ETA? Thanks!

**Comment by WilliamDenniss** [comment]
Hi,

All the code from the 0.95.0 release has been merged into the master branch, it was a re-base so the SHAs differ. You can verify this if you `git merge 0.95.0`, you'll see that there are no changes.

The 0.9x series of releases is cut from the `pre1.0` branch, where as the 1.x series of releases are cut from the `master` branch.

`1.0.0.beta1` has Xcode 10 support. The 0.9x series will not be getting Xcode 10 support. I would recommend using the `1.0.0.beta1` release.
