### ISSUE TITLE
Remove header and footer of Authentication login screen

### ISSUE THREAD

**Issue by effy4u** [openid/AppAuth-iOS#319]
Hi guys, this is not really an issue, my boss wants me to remove the header that shows the login url and its footer from the authentication screen, when making a login, please how can I go about this. By the way it's swift.

Thanks.

**Comment by WilliamDenniss** [comment]
Hey, that UI you are referring to is rendered by iOS itself, not AppAuth, so you'd have to ask Apple if you wanted to change it.
