### ISSUE TITLE
Client Secret not handled in ios SDK

### ISSUE THREAD

**Issue by DavidCorrado** [openid/AppAuth-iOS#32]
It is not possible with the current implementation to allow the client secret authentication.  Below is the spec for it:
https://tools.ietf.org/html/rfc6749#section-2.3.1

It appears this pull request is regarding the same issue.  
https://github.com/openid/AppAuth-iOS/pull/24

It would be nice if this would built in like it is in the Android SDK.

Thanks for taking time reviewing this request.

**Comment by WilliamDenniss** [comment]
Have you patched in the pull request and tried it out? Does it work as you would expect?

**Comment by hamedmohammadi** [comment]
client_secret is missing. in example test even after setting the secret key when instantiating "OIDAuthorizationRequest" object

**Comment by WilliamDenniss** [comment]
Fixed in #100.
