### ISSUE TITLE
Archive failed: carthage update --platform iOS

### ISSUE THREAD

**Issue by ramunasjurgilas** [openid/AppAuth-iOS#321]
Command line execution failed: carthage update --platform iOS

{code}
** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/rj/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/AppAuth-iOS/e15216fe9636ff86265c49a9de15ccdcedb69132/Build/Intermediates.noindex/ArchiveIntermediates/AppAuth_iOS/IntermediateBuildFilesPath/AppAuth.build/Release-iphoneos/AppAuth_iOS.build/Objects-normal/armv7/OIDExternalUserAgentIOS.o Source/iOS/OIDExternalUserAgentIOS.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
{code}

**Comment by WilliamDenniss** [comment]
Are you using Xcode 10?

**Comment by WilliamDenniss** [comment]
ok, you can always use an old branch with Xcode 9, but HEAD requires the current version of Xcode. It builds for me.
