### ISSUE TITLE
Gmail shows 400/401 error during OAuth

### ISSUE THREAD

**Issue by triton3** [openid/AppAuth-iOS#323]
**Are you filing an issue about iOS 12?**
No

**Describe the bug**
Gmail OAuth process shows a 400/401 error sometimes (screenshots attached) after entering password for OAuth. This happens if the email address has not been used on the device before (iOS and Android platforms). Upon second attempt at OAuth login, it works correctly.

**To Reproduce**
1. Initiate GMail OAuth using an email account that has never been used on an iOS or Android device
2. When prompted enter password and continue. 

**Expected behavior**
Expected behavior is to see the screen that asks the user to allow the app to access email with an "Allow Access" or "Deny" buttons. But instead, it shows a 400 (on iOS) or 401 (on Android) error.

**Screenshots**
![gmail-400-ios](https://user-images.githubusercontent.com/13472986/47454712-dea51c00-d79d-11e8-9179-6390dbc77b43.png)

![gmail-401-android](https://user-images.githubusercontent.com/13472986/47454718-e4026680-d79d-11e8-8f79-9ee625675bed.png)

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS 11/12
 - Browser: safari
 - Version for AppAuth: 0.95.0

 - Device: Nexus 5
 - OS: Android 6.0.1
 - Browser: chrome
 - Version for AppAuth: net.openid:appauth:0.7.0

**Additional context**
The configuration used is the following for oauth:
"AuthURI": "https://accounts.google.com/o/oauth2/v2/auth",
"Scope": "https://mail.google.com/",
"TokenURI": "https://www.googleapis.com/oauth2/v4/token"

**Comment by petea** [comment]
I'm unable to reproduce the 400 response on iOS using the example app with the https://mail.google.com/ scope.  Are you still seeing this behavior?  If so, are you able to reproduce it using the Example app configured with a test project?

**Comment by triton3** [comment]
Apologies for the late response. We dont see this error anymore. Will report it if it happens again.
