### ISSUE TITLE
Universal Link won't close SFSafariViewController

### ISSUE THREAD

**Issue by mab5vot9us9a** [openid/AppAuth-iOS#328]
**Describe the bug**
On your Readme page you state that Universal Links are supported. Unfortunately the SFSafariViewController that gets presented using the `OIDAuthState.authState(byPresenting: request, presenting: presentingVC)` does not close once the redirect URL is reached.
However, copying the URL from the SFSafariViewController and pasting it into Safari manually triggers the App redirect and continues the auth flow in the `func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool` method resulting in getting a valid authToken, refreshToken, idToken.

My redirect URL looks like this: https://appSubdomain.domain.com/ios/oauth2/callback

I have added `applinks:appSubdomain.domain.com` under the _Associated Domains_ group in the Target Capabilities. As mentioned before, manually entering `https://appSubdomain.domain.com/ios/` in Safari opens the app correctly.

I don't get any feedback from the Library what might be wrong. Any help would be appreciated.

**To Reproduce**
```swift
/// Login ViewController
let configuration = OIDServiceConfiguration(authorizationEndpoint: authURL,
                                            tokenEndpoint: tokenURL,
                                            issuer: issuerURL)

let request = OIDAuthorizationRequest(configuration: configuration,
                                      clientId: "clientID",
                                      clientSecret: "clientSecret",
                                      scopes: [OIDScopeOpenID, OIDScopeProfile],
                                      redirectURL: URL(string: "https://appSubdomain.domain.com/ios/oauth2/callback")!,
                                      responseType: OIDResponseTypeCode,
                                      additionalParameters: nil)

self.currentAuthorizationFlow = OIDAuthState.authState(byPresenting: request, presenting: presentingVC) { authState, error in
    
    if let authState = authState {
        os_log("Got authorization tokens. Access token: %@\nRefresh Token: %@\nIDToken: %@", log: self.logger, type: .debug, authState.lastTokenResponse?.accessToken ?? "DEFAULT_TOKEN", authState.lastTokenResponse?.refreshToken ?? "NONE", authState.lastTokenResponse?.idToken ?? "NONE")
        
    } else {
        os_log("Authorization error: %@", log: self.logger, type: .error, error?.localizedDescription ?? "DEFAULT_ERROR")
    }
}
```
```swift
/// AppDelegate
func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {
    
    guard userActivity.activityType == NSUserActivityTypeBrowsingWeb,
        let url = userActivity.webpageURL else {
            return false
    }
    
    if let authorizationFlow = self.currentAuthorizationFlow, authorizationFlow.resumeExternalUserAgentFlow(with: url) {
        self.currentAuthorizationFlow = nil
        return true
    }
    
    return false
}
```
**Expected behavior**
I would expect the Safari ViewController to close and continue with the authorization flow.

**Smartphone (please complete the following information):**
 - Device: iPhone XS Simulator
 - OS: iOS 12
 - Browser: SFSafariViewController
 - Version: AppAuth (0.95.0) via Cocoapods

**Additional context**
Using Swift.

**Comment by WilliamDenniss** [comment]
AppAuth doesn't use SFSafariViewController on iOS 12, so I assume you mean ASWebAuthenticationSession or SFWebAuthenticationSession.

Can you try this on the `master` branch (simply point your Podfile at `master` & `pod install`).

Have you verified that the `resumeExternalUserAgentFlow` method is being called?

I did find one bug, but it wasn't present in version 0.95.0…

**Comment by shobhitpuri** [comment]
@WilliamDenniss Can you please share if handling Universal Link callback URLs is supported by `ASWebAuthenticationSession` that's used for iOS 12+? 

I am unable to get it to work on iOS, when after successful login, the redirect happens inside the `ASWebAuthenticationSession` web view. However, the app opens if the links are clicked from outside the app. More on the issue here: https://github.com/MaikuB/flutter_appauth/issues/293

**Comment by J6ey** [comment]
@shobhitpuri Here's what worked for me and since Safari redirect works for you, this should workaround should work too:
```
let userAgent = OIDExternalUserAgentIOSCustomBrowser.customBrowserSafari()

appDelegate.currentAuthorizationFlow = OIDAuthState.authState(byPresenting: request, externalUserAgent: userAgent) {
...
```
