### ISSUE TITLE
Getting error : "Connection error making token request to "<hostname>/connect/token": The network connection was lost..." on iOS 12

### ISSUE THREAD

**Issue by munderk** [openid/AppAuth-iOS#336]
**Are you filing an issue about iOS 12?**
YES

**Describe the bug**
After successful authentication on the browser, while it switches to the app , the error occurs.

**Expected behavior**
The error should not occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/17243538/48690827-1ca72b80-ebf6-11e8-95a9-37e8f68b1b9e.png)

**Comment by WilliamDenniss** [comment]
To me this looks like a network issue on the device. Do you have any evidence that it's a bug in the AppAuth library?

**Comment by munderk** [comment]
While making network calls, app is still in background, that's why the issue. have to check for Application state everytime before making this network call. Anyway i did workaround do fix this.

**Comment by harsh-pcc** [comment]
Am facing the same issue. Even thought the request is a HTTP 200, the request with the same error as described in the issue.
Not really related to network as all the other features of the app works.

**Comment by harsh-pcc** [comment]
@munderk : what was workaround you added?

**Comment by shravankumarbj** [comment]
Will you please provide the what workaround? we are facing this issue.

**Comment by fukemy** [comment]
hi, did someone solved this?

**Comment by fukemy** [comment]
@munderk because when present safari with customOID, app navigate to safari login ( not open safari inside app). then got this error
