### ISSUE TITLE
'archivedDataWithRootObject:' is deprecated: first deprecated in iOS 12.0 - Use +archivedDataWithRootObject:requiringSecureCoding:error: instead

### ISSUE THREAD

**Issue by jeffemandel** [openid/AppAuth-iOS#342]
I'm trying to archive my authState and save it to the keychain. The example code saveState and loadState both use deprecated methods and suggest the new methods. When I try these:

`NSData *myAuthData = [NSKeyedArchiver archivedDataWithRootObject:self->_authState requiringSecureCoding:YES error:&myError];
OIDAuthState *storedAuthState = [NSKeyedUnarchiver unarchivedObjectOfClass:[OIDAuthState class] fromData:myAuthData error:&myError];
`
fails with the unhelpful message "The data couldn’t be read because it isn’t in the correct format."

I've tried all the classes I could find:
`
unarchivedObjectOfClasses:[NSSet setWithArray:@[[OIDAuthState class],[NSError class],[OIDTokenResponse class],[OIDRegistrationResponse class],[NSString class],[OIDServiceConfiguration class],[OIDRegistrationRequest class],[NSDictionary class],[NSArray class],[NSNumber class],[NSURL class]]] 
`
but no luck. Suggestions?

**Comment by jeffemandel** [comment]
I tracked down the problem. In OIDServiceDiscovery.m, we need to change the encode/decode:
```
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder {
  NSError *error;
  NSSet *codingClasses = [NSSet setWithArray:@[ [NSDictionary class],[NSArray class] ]];
  NSDictionary *dictionary = [aDecoder decodeObjectOfClasses:codingClasses forKey:kDiscoveryDictionary];
//  NSDictionary *dictionary = [[NSDictionary alloc] initWithCoder:aDecoder];
  self = [self initWithDictionary:dictionary error:&error];
  if (error) {
    return nil;
  }
  return self;
}

- (void)encodeWithCoder:(NSCoder *)aCoder {
  [aCoder encodeObject:_discoveryDictionary forKey:kDiscoveryDictionary];
}

```
It looks like this is the only place that you don't use this pattern; I'm now able to unarchive specifying the single top-level class:

`OIDAuthState *storedAuthState = [NSKeyedUnarchiver unarchivedObjectOfClass:[OIDAuthState class] fromData:myAuthData error:&myError];`

There are some other things that are deprecated in iOS 12, but they are all in OIDExternalUserAgentIOSCustomBrowser.

**Comment by vineethnkforios** [comment]
@jeffemandel  tried, but not working for me, Any solutions ?
