### ISSUE TITLE
ASWebAuthenticationSession and SFAuthenticationSession use the target name instead of bundle display name

### ISSUE THREAD

**Issue by ugenlik** [openid/AppAuth-iOS#343]
**Describe the bug**
When using `OIDAuthState.authState(byPresenting: request, presenting: viewController)` there is an alertview for devices greater than iOS 11  for single-sign on.  Which is obvious. 

But the problem is alertview uses `scheme` name of the app not  `Display Name` from the Info.plist or bundle identifier name from bundle. 

Which makes it very confusing for the user, because name of my App is `GO`, but the project scheme/workspace name is `HUGIN`

and user sees following when try to login:

<img width="257" alt="screen shot 2018-12-03 at 8 56 31 pm" src="https://user-images.githubusercontent.com/1995917/49475386-15327580-f7e5-11e8-8c1d-1555dfe00f52.png">

User doesn't know what HUGIN is , so it is incredibly confusing for everybody. 

They need to see either one of this values:

<img width="618" alt="screen shot 2018-12-04 at 4 57 07 pm" src="https://user-images.githubusercontent.com/1995917/49475622-b3264000-f7e5-11e8-9cf6-bff8f9330f69.png">

Is there a way to pass the Display Name to system so OS doesnt use the `scheme` name ???

**To Reproduce**
Steps to reproduce the behavior , just use `OIDAuthState.authState(byPresenting` in iOS 11 or iOS 12
```
 // builds authentication request
        let request = OIDAuthorizationRequest(configuration: configuration,
                                clientId: clientID,
                                clientSecret: Config.sharedInstance.identity_ClientSecret,
                                scope: "xxxx",
                                redirectURL: redirectURI,
                                responseType: OIDResponseTypeCode,
                                state: nil, nonce: nil, codeVerifier: nil, codeChallenge: nil, codeChallengeMethod: nil,
                                additionalParameters: additionalParams)

OIDAuthState.authState(byPresenting: request, presenting: viewController) { authState, error in

}
```

**Comment by WilliamDenniss** [comment]
I always thought it was the app name, but now that you raise this I've never directly confirmed that, nor do I know how to change it. Hopefully someone here knows the answer!

So to be clear, it's not using the name that shows under your app's icon on the homescreen?

**Comment by ugenlik** [comment]
@WilliamDenniss no it does not, it uses either target name or project name, I am not sure which one it is using. 

As you can see target name is Hugin, but the display name is `mHelpDeskGO QA`

<img width="854" alt="screen shot 2018-12-04 at 6 20 01 pm" src="https://user-images.githubusercontent.com/1995917/49479606-9db71300-f7f1-11e8-8829-afd2df7cd5e5.png">


in the device
<img width="348" alt="screen shot 2018-12-04 at 6 21 31 pm" src="https://user-images.githubusercontent.com/1995917/49479635-b45d6a00-f7f1-11e8-9f4c-b42538a5cb4f.png">

**Comment by julienbodet** [comment]
I also tested on my side and confirm this is the target name that is used (not the project name). It appears to be a bug from Apple's `ASWebAuthenticationSession` (also the deprecated SFAuthenticationSession on iOS 11) with no way to change this behaviour.

**Comment by ugenlik** [comment]
It is really annoying, luckily our team has their own identity server and our stake holders are okay with using the identity server without sso. 

So I created a gist and by passing the alertview for now. 

https://gist.github.com/ugenlik/2a543f351e9b9425800b48266760dc85

**Comment by WilliamDenniss** [comment]
Glad you resolved it for your case @ugenlik.

I would expect the standard workaround for this to be renaming the target to the desired name.

**Comment by WilliamDenniss** [comment]
Closing this as there's not much we can do on the AppAuth side, and we have a known workaround, but feel free to continue commenting for how you all workaround this, and if any changes to the OS behavior are observed!

**Comment by gregersn** [comment]
Struggling with the same problem, I found that what is set in `CFBundleName` in `Info.plist` is what is displayed in that dialog. That is the short version of `CFBundleDisplayName`.

**Comment by liuyang2211** [comment]
![4271709519256_ pic](https://github.com/openid/AppAuth-iOS/assets/19897206/0dc25cd2-afc9-4e4d-ad26-88be32e7a599)

Change info.plist Bundle name is invalid. We need change in buildSetting -> Product Name
