### ISSUE TITLE
PhaseScriptAppAutExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by CapitalVideo** [openid/AppAuth-iOS#348]
I'm trying to run Example-iOS_Swift-Carthage, but keep getting error:
Failed to read file or folder at /Users/airesrego/Desktop/AppAuth-iOS-master/Examples/Example-iOS_Swift-Carthage/Carthage/Build/iOS/AppAuth.framework
Command PhaseScriptExecution failed with a nonzero exit code
running iOS 12 and Swift 4.2. Has anyone come across this issue?
I'm new to both Xcode and Swift, could use a detailed solution to resolve this error.
Thanks

**Comment by WilliamDenniss** [comment]
Can't repro, please re-open with repro steps if you can.
