### ISSUE TITLE
App crash on 10.3.1 (simulator)

### ISSUE THREAD

**Issue by torianin** [openid/AppAuth-iOS#350]
**Describe the bug**
App crash on 10.3.1 ( Simulator ) when using experimental dev-logout branch

**To Reproduce**
1. Use dev-logout branch 
    `pod 'AppAuth', :git => 'git@github.com:openid/AppAuth-iOS.git', :branch => 'dev-logout'`
2. Run app in iPhone 5s (10.3.1)
3. Crash when the application starts

`dyld: Library not loaded: /System/Library/Frameworks/AuthenticationServices.framework/AuthenticationServices
  Reason: image not found`

**Expected behavior**
App should run without crash

**Comment by ugenlik** [comment]
Same happened to me, it worked fine using simulator but my apps crashed on Crashyltics and Testflight. 

You need to go to your  Target-> General->Linked Frameworks and Libraries 
and add `AuthenticationServices.framework` then you need to make it optional.

![screen shot 2019-02-27 at 5 54 57 pm](https://user-images.githubusercontent.com/1995917/53528941-1eb43c80-3ab9-11e9-9533-cdc30b4d1c52.png)
