### ISSUE TITLE
Single Sign On - SAML 2.0 Compliant

### ISSUE THREAD

**Issue by WrightsCS** [openid/AppAuth-iOS#351]
Trying to use this with OneLogin, but when I try their issuer Url, I get a 404 response **Non-200 HTTP response (404) fetching discovery document 'https://app.onelogin.com/saml/metadata/myuid/.well-known/openid-configuration'**.

Wondering if this can be used for **SSO / SAML 2.0 compliant sign on**. I need to support BOTH IdP and SP initiated SSO.

**Comment by WrightsCS** [comment]
Does anyone have insight to this?

**Comment by WilliamDenniss** [comment]
AppAuth doesn't support SAML 2.0, only OpenID Connect and OAuth 2.0.

**Comment by CodeGradientsProjects** [comment]
How did you managed to solve it ? any solutions ?
