### ISSUE TITLE
Mac OSX - Closing the Browser after getting the token

### ISSUE THREAD

**Issue by kkprvn** [openid/AppAuth-iOS#361]
I am using AppAuth for Mac OSX 10.13.I am able to receive the tokens but the browser opened through [[NSWorkspace sharedWorkspace] openURL:requestURL] but unable to close the browser instance.
Above code is from OIDExternalUserAgentMac.m -->presentExternalUserAgentRequest() function.
Do you have an API to handle this?

**Comment by WilliamDenniss** [comment]
I don't think it's possible, I'm not aware of any API AppAuth can use to achieve this.

I wish it was!
