### ISSUE TITLE
Log in doesn't work in Guided Access or Single App modes

### ISSUE THREAD

**Issue by cassianodialpad** [openid/AppAuth-iOS#365]
**Describe the bug**
Log in doesn't work in Guided Access mode or single app mode with supervised devices under an MDM. As per https://openradar.appspot.com/48376122, both ASWebAuthenticationSession and SFAuthenticationSession return an error (Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=1 "(null)") in these cases.

**To Reproduce**
1. Enable guided access on a device (Settings -> General -> Accessibility)
2. Set up and run the example project.
3. Start guided access mode on device (Tap home/power button 3 times, depending on device type)
4. Tap button "Authorize" in the app.

**Expected behavior**
Have an alert window to continue sign-in, and then the webview should appear.

** Actual behavior**
Neither the alert window nor the webview are presented, and an error occurs (Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=1 "(null)").

**Smartphone:**
 - Device: iPhone8
 - OS: iOS 12.1.4
 - XCode: 10.1 10B61

Tested with library versions 0.95.0 and master.

**Comment by WilliamDenniss** [comment]
Is this feasible to fix? If the WebAuthenticationSession is restricted by the operating system, I'm not sure what AppAuth should do.

**Comment by cassianodialpad** [comment]
I have fixed it in my fork, I will make a pull request as soon as I sign the agreement.

**Comment by WilliamDenniss** [comment]
Awesome, thank you!

**Comment by cassianodialpad** [comment]
I'm still waiting on my company to sign the agreement, that should happen soon.

**Comment by cassianodialpad** [comment]
Legal department has signed the agreement, I'm under Dialpad.
