### ISSUE TITLE
State mismatch returned when trying to authenticate with reponse type id token and code

### ISSUE THREAD

**Issue by Brijak0** [openid/AppAuth-iOS#366]
Hi
**Are you filing an issue about iOS 12?**
Yes - OS = iOS12.1 
You can find preliminary support for iOS 12 in the (ios12beta branch)[https://github.com/openid/AppAuth-iOS/tree/ios12beta] and background information in (the associated pull request)[https://github.com/openid/AppAuth-iOS/pull/246]. Please review these materials before filing iOS 12 issues. Thanks.

**Describe the bug**
I'm trying out AppAuth for OpenId connect to a mobile app I'm doing (please note I'm a newbi to IOS and swift ) and I would like to use the hybrid flow and setting response type to Id Token Code works as described in issue 88. (Identity server 4 is used as ID provider service) We gets to logon and do consent validation, but when returning to the AppAuth demo app the state value is null. If I try the same inside an internet browser it works fine. I have tried the workaround descriped by wmcainsh in issue 88 but the "func application" get no hits upon return of the request. Do I need to set something special here? Note return url is set the in the plist does the bundle name need to be alike the return url?

**To Reproduce**
1. Use the AppAuth demo app, modified with correct client id, scope and response type (Id token Code) ect
2. Click on manual authentication
3. Logon using Demo.Identityserver as Authentication body
3. Press yes to agree to consent
4. See error State mismatch in app window

**Expected behavior**
I would expect the app to be authorized and an access token, a refresh token and an id token be retured to the app.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: IPhone 10
 - OS: IOS12.1
 - Browser safar]

I hope the description make sense. Many thanks in advance.
br
Brijak0

**Comment by WilliamDenniss** [comment]
I'm sorry, but I don't believe this is a bug in AppAuth, and I don't quite know what to suggest.

**Comment by sw-tt-kirtanvaghela** [comment]
I am having the same issue. After login process is completed there is ans state mismatch error and tokens and all values are null.
