### ISSUE TITLE
How sign in with login and password without show browser. 

### ISSUE THREAD

**Issue by balkarov** [openid/AppAuth-iOS#370]
Hello. 

Thank you for your library!
Sorry for my question, I tried to find the similar questions but nothing found. 

How to sign in AppAuth if I have login and password (silent)? I mean without open browser I need get authState.

**Comment by WilliamDenniss** [comment]
This OAuth library cannot be used for that.

**Comment by fukemy** [comment]
hi @balkarov did u find any solution?

**Comment by balkarov** [comment]
@fukemy Hello.
I created new client in IdentityServer4 with `Resource Owner Password` type.
App sends request to `/connect/token` with login and password to IdentityServer4 for get auth state (accessToken, refreshToken, expiresAt).
Save this state.
And in any request I check token expired time.
Example:
```swift

/*! @brief Number of seconds the access token is refreshed before it actually expires.
     */
static var kExpiryTimeTolerance: Double = 60;

static func isTokenFresh(_ expiresAt: Date) -> Bool {
        let tokenFresh = expiresAt.timeIntervalSinceNow > kExpiryTimeTolerance
        return tokenFresh
}
```

If accessToken is expired then I app refreshes it with refreshToken: send refreshToken to `/connect/token`
http body raw:
```swift
var raw = "client_id=CLIENT_ID&client_secret=SECRET&grant_type=refresh_token&refresh_token=REFRESH_TOKEN"
```
