### ISSUE TITLE
AppAuth SDK being actively maintained?

### ISSUE THREAD

**Issue by tizaks** [openid/AppAuth-iOS#372]
Hi there,

I'm curious to understand whether this SDK is being actively maintained and if there are plans to continue doing so in future. I'm beginning work on a new project and considering the use of this SDK, but am hesitant to continue as it seems there hasn't been much work on the project recently, and there are a number of unmerged Pull Requests from the community ready to be merged in.

Thanks for your help

**Comment by WilliamDenniss** [comment]
Yes it's still maintained, we plan to cut 1.0 shortly.

**Comment by tizaks** [comment]
Great, thank you.
