### ISSUE TITLE
1.0.0.beta1 Cancel a pending OIDAuthState request crashes.

### ISSUE THREAD

**Issue by the-pear** [openid/AppAuth-iOS#376]
**Describe the bug**
[1.0.0.beta1] Cancel a pending OIDAuthState request crashes.
Can't reproduce it on 0.9.5 using the same code.

**To Reproduce**
Code to reproduce:
```swift
        let configuration = OIDServiceConfiguration(authorizationEndpoint: kAuthorizationEndpoint,
                                                             tokenEndpoint: kTokenEndpoint)
        let request = OIDAuthorizationRequest(configuration: configuration,
                                              clientId: kClientID,
                                              clientSecret: nil,
                                              scopes: [OIDScopeOpenID],
                                              redirectURL: kRedirectURI,
                                              responseType: OIDResponseTypeCode,
                                              additionalParameters: nil)
        let extAgent = OIDAuthState.authState(byPresenting: request, presenting: self) { (state, error) in
            
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 3 ) {
            extAgent.cancel()
        }
```

**Expected behavior**
No crash.

**Screenshots**
![Screen Shot 2019-03-27 at 17 55 32](https://user-images.githubusercontent.com/30165525/55062579-9924ac00-50b9-11e9-8f6b-8e992a951ba7.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XR simulator
 - OS: iOS 12.2

**Additional context**
N/A

**Comment by WilliamDenniss** [comment]
I can't repro on HEAD using the Swift Carthage sample.

The dialog appears, then disappears - no crash.

Here's my code:

```
    @IBAction func authWithAutoCodeExchange(_ sender: UIButton) {

        let configuration = OIDServiceConfiguration(authorizationEndpoint: URL(string:"https://google.com")!,
                                                    tokenEndpoint: URL(string:"https://appauth.io")!)
        let request = OIDAuthorizationRequest(configuration: configuration,
                                              clientId: kClientID!,
                                              clientSecret: nil,
                                              scopes: [OIDScopeOpenID],
                                              redirectURL: URL(string:kRedirectURI)!,
                                              responseType: OIDResponseTypeCode,
                                              additionalParameters: nil)
        let extAgent = OIDAuthState.authState(byPresenting: request, presenting: self) { (state, error) in
            
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 5 ) {
            extAgent.cancel()
        }
}
```

XCode 10.1
iOS 12.1 (16B91)
Model: iPhone Xʀ

**Comment by the-pear** [comment]
> The dialog appears, then disappears - no crash.
The dialog, you mean the dialog for permission or the SFAuthenticationSession after you confirm the dialog?
It crashes for me if I accept the permission and SFAuthenticationSession is on screen.

**Comment by wilmarvh** [comment]
We've seen multiple instances of this crash in production over the last 2 weeks.

**Comment by WilliamDenniss** [comment]
Can someone push a test case to GitHub that repro's this? e.g. based off the sample?

Otherwise I'm closing as can't reproduce, as that code above is working for me.

**Comment by the-pear** [comment]
> Otherwise I'm closing as can't reproduce, as that code above is working for me.

I tried on 1.0.0.rc1, can't reproduce the issue any more.
