### ISSUE TITLE
1.0.0.beta1 Weak frameworks is referenced strongly

### ISSUE THREAD

**Issue by esbenr** [openid/AppAuth-iOS#377]
**Are you filing an issue about iOS 12?**
You can find preliminary support for iOS 12 in the (ios12beta branch)[https://github.com/openid/AppAuth-iOS/tree/ios12beta] and background information in (the associated pull request)[https://github.com/openid/AppAuth-iOS/pull/246]. Please review these materials before filing iOS 12 issues. Thanks.

**Describe the bug**
When using v. 1.0.0.beta1 via cocoapods the reference to Apples AuthenticationServices becomes strong. The AuthenticationServices SDK is only available on iOS 12+, which means that the app will crash with the following error when using AppAuth SDK on a device lower than iOS 12 (i.e. iOS 11.4).

Error:
```
dyld: Library not loaded: /System/Library/Frameworks/AuthenticationServices.framework/AuthenticationServices
  Referenced from: /Users/dkesbras/Library/Developer/CoreSimulator/Devices/C7AF7A0D-79A9-48C2-8619-DEF94BBD2D10/data/Containers/Bundle/Application/636E7A81-4047-47FD-A182-04A2B76E7B8F/AppAuthTestDirect.app/AppAuthTestDirect
  Reason: image not found
```

**To Reproduce**
1. New single view project
2. Create Podspec with "pod 'AppAuth', '~> 1.0.0.beta1'"
3. Run "pod install"
4. Run app on iOS i.e 11.4 (iOS < 12)
5. App crashes with the above error
*6. Change Podspec to "pod 'AppAuth', '~> 0.95'"
*7. App works fine on iOS 11.4 (iOS < 12)

**Expected behavior**
I think there is problems with the .weak_framework AuthenticationServices framework reference in the podspec, byt I'm not sure.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone X (device) + iPhone 8 (simulator)
 - OS: iOS 11.4 (All lower than 12)

**Additional context**
See example project here:  
https://github.com/esbenr/AppAuth100beta1DependencyIssue

**Comment by esbenr** [comment]
Fixed in this commit:
https://github.com/openid/AppAuth-iOS/commit/2217b944ac72c3588ffa110a93ba1cf03a6bea32#diff-a4458f9fb06defbec20fb9b3f211bd97

But still an issue until a new version has been made. Would it make sense på make a 1.0.0.beta2 while waiting for https://github.com/openid/AppAuth-iOS/issues/96?

**Comment by WilliamDenniss** [comment]
Try `1.0.0.rc1`, let me know how you go!
