### ISSUE TITLE
IDToken validation period is hardcoded

### ISSUE THREAD

**Issue by wilmarvh** [openid/AppAuth-iOS#381]
According to [this code](https://github.com/openid/AppAuth-iOS/blame/2a7a6754fd5b612aa554fa56d6e7853218e2d84f/Source/OIDAuthorizationService.m#L470), the IDToken validation is hardcoded to a period of 600 seconds (10 minutes).

The Open ID connect spec defines in the relevant section ([3.1.3.7 rule 10](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation)) that the acceptable range should be client specific. 

Having 600 seconds as a default is sensible, however we require this range to be slightly adjusted for our implementation, and would thus want the ability to override it.

**Comment by julienbodet** [comment]
Hi @wilmarvh, this seems to be a duplicate of https://github.com/openid/AppAuth-iOS/issues/362.

**Comment by wilmarvh** [comment]
O goodie, how'd I miss that! Closing
