### ISSUE TITLE
Suddenly Nothing after login 

### ISSUE THREAD

**Issue by RanjeetStiga** [openid/AppAuth-iOS#384]
**Are you filing an issue about iOS 12?**
You can find preliminary support for iOS 12 in the (ios12beta branch)[https://github.com/openid/AppAuth-iOS/tree/ios12beta] and background information in (the associated pull request)[https://github.com/openid/AppAuth-iOS/pull/246]. Please review these materials before filing iOS 12 issues. Thanks.

**Describe the bug**

**To Reproduce**
1. Go to 'Logging.'
2. Click on ' submit'
3. login success 

**Expected behavior**

**Screenshots**
![Simulator Screen Shot - iPhone 6s Plus - 2019-04-09 at 11 18 51](https://user-images.githubusercontent.com/49231621/55776208-95c9f100-5ab9-11e9-81ba-917c6c150d0d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6s]
 - OS: [e.g. iOS12.1]
 - Version [e.g. 0.95.0]

**Additional context**
I am using SDk version 0.95.0 . After login screen is balnk and nothing to happened . Its suddenly start before its working fine .

**Comment by WilliamDenniss** [comment]
I don't believe this is a bug in AppAuth, however if you can supply a test case that I can reproduce, I'll take a look.
