### ISSUE TITLE
How to remove safari cache and cookies for iOS 

### ISSUE THREAD

**Issue by RanjeetStiga** [openid/AppAuth-iOS#387]
**Are you filing an issue about iOS 12?**
You can find preliminary support for iOS 12 in the (ios12beta branch)[https://github.com/openid/AppAuth-iOS/tree/ios12beta] and background information in (the associated pull request)[https://github.com/openid/AppAuth-iOS/pull/246]. Please review these materials before filing iOS 12 issues. Thanks.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WilliamDenniss** [comment]
Only the website that created the cookies in Safari can remove them, or the user themselves. You can however not use AppAuth with SSO, see https://github.com/openid/AppAuth-iOS/issues/209#issuecomment-404353236.
