### ISSUE TITLE
After delete app when install again I get previous (gmail) login user.

### ISSUE THREAD

**Issue by RanjeetStiga** [openid/AppAuth-iOS#388]
**Are you filing an issue about iOS 12?**
You can find preliminary support for iOS 12 in the (ios12beta branch)[https://github.com/openid/AppAuth-iOS/tree/ios12beta] and background information in (the associated pull request)[https://github.com/openid/AppAuth-iOS/pull/246]. Please review these materials before filing iOS 12 issues. Thanks.

**Describe the bug**
I have login with gmail , I have delete the app from device . then again reinstall the app and try to login I am getting previous log in user which is one log in before delete app. when I delete the safari data from device then its working fine.
**To Reproduce**
1. Go to login with gmail  
2. delete app
3. reinstall app 
4. click on log in
5. previous user get

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WilliamDenniss** [comment]
What you're observing is a function of how SSO works, where the user's cookie remains in Safari. If you don't want to use AppAuth with SSO (which is not the normal usage), you can use SFSafariViewController [instead](https://github.com/openid/AppAuth-iOS/issues/209#issuecomment-404353236).
