### ISSUE TITLE
Persisting OIDAuthState on token refresh

### ISSUE THREAD

**Issue by taimila** [openid/AppAuth-iOS#392]
What is the right approach to make sure that secure storage has always the latest tokens (aka `OIDAuthState` instance) persisted?

In example app we persist `OIDAuthState` after intial authorization and that's fine, but shouldn't I always update persisted state after tokens have been refreshed? I use convinience API `performActionWithFreshTokens` to make all backend calls. Should I persist my `OIDAuthState` everytime `performActionWithFreshTokens` calls it's callback with valid tokens? Or is there a way to know if tokens were actually refreshed and only perform serialization to secure storage in that case?

**Comment by taimila** [comment]
I noticed that I can register `OIDAuthStateChangeDelegate` to `OIDAuthState` which gets called everytime the authState changes. I assume that the right approach is use this delegate to update persisted state on state change. 

Let me know if I'm wrong.

**Comment by WilliamDenniss** [comment]
You are correct. `didChangeState` will be called when the token is refreshed.

This LOC will eventually call that:

https://github.com/openid/AppAuth-iOS/blob/2a7a6754fd5b612aa554fa56d6e7853218e2d84f/Source/OIDAuthState.m#L520

Any errors encountered will call it as well.
