### ISSUE TITLE
Merge or update the dev-logout branch

### ISSUE THREAD

**Issue by mattio** [openid/AppAuth-iOS#393]
I noticed the pod bump to version 1.0.0.rc1 on master, which is awesome.

Unfortunately I'm stuck on the dev-logout branch for now because we need that feature.

Totally understand that there may not be enough usage to merge dev-logout into master yet. Would it be possible to catch dev-logout up to master?

**Comment by WilliamDenniss** [comment]
Done. dev-logout rebased to master.

If this now-rebased branch is working for people, can you comment in #259 and share your experience (even if you have already)? I'd like to get it merged right after cutting 1.0.
