### ISSUE TITLE
Opening website from App with SSO

### ISSUE THREAD

**Issue by P-Treiber** [openid/AppAuth-iOS#395]
Hello,

we are using AppAuth to sign in our app with an external IDP. Now we want to open a web page from within the app, so the user can change his password. Unfortunately, the user is asked to login a second time when he wants to open the web page. This is not a user experience that we want in our app. What would be the AppAuth way to open such a wep page within the same session?

Any help is appreciated.

Kind regards.

**Comment by P-Treiber** [comment]
Hello,

we managed to open a website without having to login again by using the SFAuthenticatedSession class. However, before we open the website, the user will be asked to give his consent. Is there any possibility to avoid the alert every time we open the web page?

Kind regards.

**Comment by WilliamDenniss** [comment]
Alas, it is not possible to avoid that alert.

Your approach looks solid. If you want to support every version of iOS that AppAuth does, you could instead use the `OIDExternalUserAgentRequest` pattern to open your request using a `OIDExternalUserAgent`.

**Comment by muiscatron** [comment]
> Hello,
> 
> we managed to open a website without having to login again by using the SFAuthenticatedSession class. However, before we open the website, the user will be asked to give his consent. Is there any possibility to avoid the alert every time we open the web page?
> 
> Kind regards.

@P-Treiber Hello, would you be able to share how you achieved this? thanks
