### ISSUE TITLE
Support "nonce" OpenID Connect auth request parameter

### ISSUE THREAD

**Issue by iainmcgin** [openid/AppAuth-iOS#4]
[OpenID Connect Core 1.0, Section 3.1.2.1](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), "nonce" parameter:

> OPTIONAL. String value used to associate a Client session with an ID Token, and to mitigate replay attacks. The value is passed through unmodified from the Authentication Request to the ID Token. Sufficient entropy MUST be present in the nonce values used to prevent attackers from guessing values. For implementation notes, see [Section 15.5.2](https://openid.net/specs/openid-connect-core-1_0.html#NonceNotes).

[Section 3.2.2.1](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest), "Authentication Request" specifies that this parameter is REQUIRED for implicit flow authentication requests (those with response type `id_token` or `id_token token`).

**Comment by WilliamDenniss** [comment]
This has been implemented.
