### ISSUE TITLE
Carthage: Task failed with exit code 65

### ISSUE THREAD

**Issue by lapinek** [openid/AppAuth-iOS#404]
**Are you filing an issue about iOS 12?**
No.

**Describe the bug**
Building scheme "AppAuthCore" fails:
```
Build Failed
	Task failed with exit code 65:
. . . /Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/AppAuth-iOS/e9c2c7c54d6fa6af0deb2d87f48296ec4bcb9024 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/_r/2955z3512fj10q1h91zd83mc0000gp/T/AppAuth-iOS SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO

```
The error in the xcodebuild log seems to be:
```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_OIDEndSessionResponse", referenced from:
      objc-class-ref in OIDAuthorizationService.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**To Reproduce**
1. echo 'github "openid/AppAuth-iOS" "master"' > Cartfile
2. carthage bootstrap

**Expected behavior**
`*** Building scheme "AppAuthCore" in AppAuth.xcodeproj` results in no messages.

**Desktop (please complete the following information):**
 - OS: 10.14.4
 - Xcode: 10.2.1 (10E1001)

**Additional context**
I don't know if this is an issue with the library or one with Carthage or Xcode, but the latest commit I can build is `d62069a0fafee04def61431c8cf6cf589177dd42` from 05/31/2019. It seems the issue was introduced in `1b8fd7906ea7009bbc2b3b28c1b5ce793549a966` from 06/26/2018 in `dev-logout`, which was recently merged in.

**Comment by julienbodet** [comment]
This is a bug in AppAuth. Some files (OIDEndSessionResponse.h/.m, OIDEndSessionResponse.h/.m) are not checked for the target `AppAuthCore`.

**Comment by WilliamDenniss** [comment]
We should add a Carthage test to Travis to catch this in the future.

**Comment by ktran03** [comment]
Is there a fix for this? This branch gives me the error "Task failed with exit code 65:".

Cartfile
github "openid/AppAuth-iOS" "dev-logout"
