### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by falipate** [openid/AppAuth-iOS#405]
**Are you filing an issue about iOS 12?**
- No

**Is your feature request related to a problem? Please describe.**
- https://github.com/openid/AppAuth-iOS/issues/71

**Describe the solution you'd like**
- Support for Swift Package Manager

**Additional context**
- Apple is integrating SPM in Xcode 11, wondering if it's possible to revisit this issue? 
https://github.com/openid/AppAuth-iOS/issues/71

**Comment by WilliamDenniss** [comment]
Assuming the SPM can support Objective-C code, +1. 

If you have any docs on this topic, please share them.

**Comment by below** [comment]
@WilliamDenniss As the name "Swift Package Manager" indicates, it does not support Objective-C. First, a Swift port of the project would be required

**Comment by julienbodet** [comment]
@below From Apple's `[website](https://developer.apple.com/documentation/swift_packages)`: 

> Swift packages are reusable components of Swift, Objective-C, Objective-C++, C, or C++ code that developers can use in their projects.

Also [here](https://developer.apple.com/documentation/swift_packages/creating_a_swift_package_with_xcode#3235007) is some restrictions about the content of packages: 

> A Swift package’s targets can contain Swift, Objective-C/C++, or C/C++ code, but an individual target can’t mix Swift with C-family languages. For example, a Swift package can have two targets, one that contains Objective-C, Objective-C++, and C code, and a second one that contains Swift code. Swift packages contain source code but don’t support assets and resources.

**Comment by below** [comment]
@julienbodet Oh, I overlooked that! In that case, I will look at that!

**Comment by haemi** [comment]
any update on this?

**Comment by adamayoung** [comment]
Any update yet on this? SDWebImage https://github.com/SDWebImage/SDWebImage managed to do it, and they're using Objective-C.

**Comment by jeroenleenarts** [comment]
What's the status of SPM support?

**Comment by thomas-sempf** [comment]
I wish for the same :)
It would be great to get SPM support.

**Comment by mbogh** [comment]
If the code is restructured a bit, it is easy to get it semi working :)

Package.swift
```swift
// swift-tools-version:5.0
// The swift-tools-version declares the minimum version of Swift required to build this package.
import PackageDescription

let package = Package(
    name: "AppAuth",
    platforms: [
        .macOS(.v10_10),
        .iOS(.v8),
        .tvOS(.v9),
        .watchOS(.v2)
    ],
    products: [
        .library(
            name: "AppAuth",
            targets: ["AppAuth"]),
        .library(
            name: "AppAuthCore",
            targets: ["AppAuthCore"])
    ],
    dependencies: [],
    targets: [
        .target(
            name: "AppAuthCore",
            dependencies: [],
            path: ".",
            sources: ["Source/Core"],
            publicHeadersPath: "Source/Core",
            cSettings: [
                .headerSearchPath("Source/Core")
            ]
        ),
        .testTarget(
            name: "AppAuthCoreTests", 
            dependencies: ["AppAuthCore"], 
            path: ".", 
            exclude: ["UnitTests/OIDSwiftTests.swift"], 
            sources: ["UnitTests"]
        ),
        .target(
            name: "AppAuth",
            dependencies: ["AppAuthCore"],
            path: ".",
            sources: ["Source/iOS"]
        )
    ]
)
```

Here `AppAuth` would only work for iOS where as `AppAuthCore` can be built for any of the platforms. Either there should be added a product + target for each platform which then can only be built when targeting that platform or the code needs to be wrapped in some `#if XX`.

**Comment by mbogh** [comment]
I would be glad to give this a try but would like to know from the maintainers of AppAuth which approach they would prefer.

**Comment by MapaX** [comment]
Nice 👍
Is there any progress to get this to the project? It would be really nice to get this through SwiftPM.

**Comment by kimdv** [comment]
Any progress on this?

**Comment by jacobsapps** [comment]
Hi AppAuth team, bumping this to show my support for this change.

**Comment by f8full** [comment]
+1, would definitely use it

**Comment by karimhm** [comment]
I have a question, would the **AppAuth-iOS** team mind if the structure of the project change?

**Comment by karimhm** [comment]
I have a question, would the **AppAuth-iOS** team mind if the structure of the project changes? in order to make Swift PM work @WilliamDenniss @julienbodet @mbogh

**Comment by karimhm** [comment]
https://github.com/openid/AppAuth-iOS/pull/525 add support for Swift Package Manager.

**Comment by julienbodet** [comment]
> I have a question, would the **AppAuth-iOS** team mind if the structure of the project changes? in order to make Swift PM work @WilliamDenniss @julienbodet @mbogh

Hi @karimhm, I worked on this a bit a few weeks ago and from what I experienced it seems easier to make it work by changing the project structure. I think it’s the way to go.

Thanks for your pull request, I’ll take a look.

**Comment by karimhm** [comment]
> > I have a question, would the **AppAuth-iOS** team mind if the structure of the project changes? in order to make Swift PM work @WilliamDenniss @julienbodet @mbogh
> 
> Hi @karimhm, I worked on this a bit a few weeks ago and from what I experienced it seems easier to make it work by changing the project structure. I think it’s the way to go.
> 
> Thanks for your pull request, I’ll take a look.

Hi,

The pull requests have updated tests and Podspec file

**Comment by julienbodet** [comment]
#525 added SPM support.
