### ISSUE TITLE
OIDTokenRequest dose not apply additional parameters?

### ISSUE THREAD

**Issue by pelego84** [openid/AppAuth-iOS#414]
**Describe the bug**
I'm create a request with additionalParameters and invoke "appDelegate.currentAuthorizationFlow = OIDAuthState.authState(byPresenting: request)".
But this method dont invoke internal the tokenExchangeRequestWithAdditionalParameters, instead always invoke "OIDTokenRequest *tokenExchangeRequest =  [authorizationResponse tokenExchangeRequest];"

**To Reproduce**
1. Create request with additional parameteres, example:
       // Building authorization request.
        let request = OIDAuthorizationRequest(
            configuration: configuration,
            clientId: clientId,
            clientSecret: kClientSecret,
            scopes: scopes,
            redirectURL: redirectURI,
            responseType: OIDResponseTypeCode,
            additionalParameters: [JWT_ENCODE_PARAMETER: TRUE_STRING_VALUE]
        )
2. Invoke method: 
     appDelegate.currentAuthorizationFlow = OIDAuthState.authState(byPresenting: request) {
                authState, error in
                completion(authState, error)
            }
3. As result create tokenExchangeRequest without parameter

**Expected behavior**
I expected that yout can pass additional parametres on OIDTokenRequest, example: "OIDTokenRequest *tokenExchangeRequest =  [authorizationResponse tokenExchangeRequestWithAdditionalParameters:authorizationRequest.additionalParameters];
"

**Comment by WilliamDenniss** [comment]
Both the authorization request and the token request supports additional parameters. It looks like you are adding them only to the `OIDAuthorizationRequest`. We don't pass on Authorization additional parameters to the Token request as these are different endpoints.

To send additional parameters on the token exchange, you may need to do the code exchange manually (which is actually pretty straight forward, and there is an example in the sample code).

**Comment by pelego84** [comment]
Thanks, I was able to pass additional parameters  using the code exchange manually
