### ISSUE TITLE
"Audience mismatch" error during ID token validation despite azp claim

### ISSUE THREAD

**Issue by petea** [openid/AppAuth-iOS#418]
**Describe the bug**
An ID token containing an azp Claim equal to the client's client_id and an aud that does not contain client_id is rejected with an "Audience mismatch" error.  This behavior is in conflict with the definition of the azp Claim:
https://openid.net/specs/openid-connect-core-1_0.html#IDToken

**To Reproduce**
1. Create a Google Developer Console project containing both an iOS client ID for the app and a web application client ID to be used as the "audience" parameter.
2. Configure the Example-iOS_ObjC app with Google as the IDP.
3. Modify the app to send "audience" as an additional parameter in both authorization and token requests.
4. Run the app and perform a manual auth and then a code exchange.
5. See an "Audience mismatch" error.

**Expected behavior**
The ID token is accepted as valid.

**Additional context**
The OpenID Connect spec is inconsistent in regard to the verification of the aud and azp claims.

**Comment by julienbodet** [comment]
In the Spec you linked I read that `aud` claim 'MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value'.

Also, referring to [ID Token Validation](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation) step 3 is:

> The Client MUST validate that the aud (audience) Claim contains its client_id value...

The above rule doesn't say the `aud` claim validation depends on the `azp` value.

Am I missing something?

**Comment by petea** [comment]
The dependency is implied by the definition of the azp claim.
> azp
> OPTIONAL. Authorized party - the party to which the ID Token was issued. If present, it MUST contain the OAuth 2.0 Client ID of this party. **This Claim is only needed when the ID Token has a single audience value and that audience is different than the authorized party.**

**Comment by KarlBusse** [comment]
Is this a ‘known ambiguity’ related to this open discussion?
https://bitbucket.org/openid/connect/issues/973/

**Comment by WilliamDenniss** [comment]
The way `azp` is documented in the spec, it does seem to imply that the validation rule added in #419 is valid, though that text in the spec is in conflict with the spec's own `aud` ID Token validation rules.

#419 does look fairly safe to me in that it would not affect anyone not using `azp`, and does, technically, implement text in OpenID Connect (thus is arguably not a vendor-specific hack which we try to avoid). 

AppAuth tries to follow the spec as faithfully as possible. In this case the spec does not provide an unambiguous answer to this particular issue. Is anyone harmed by the addition of this validation rule?

**Comment by WilliamDenniss** [comment]
@KarlBusse yes, I believe so.

Regarding that [issue](https://bitbucket.org/openid/connect/issues/973/), one thing that issue is lacking is any comments by someone whose OIDC implementation is using `azp`. It would be nice to have that information on the record for review and potential resolution of that outstanding issue.

**Comment by WilliamDenniss** [comment]
The way `azp` is documented in the spec, it does seem to imply that the validation rule added in #419 is valid, though that text in the spec is in conflict with the spec's own `aud` ID Token validation rules.

#419 does look fairly safe to me in that it would not affect anyone not using `azp`, and does, technically, implement text in OpenID Connect (thus is arguably not a vendor-specific hack which we try to avoid). 

AppAuth tries to follow the spec as faithfully as possible. In this case the spec does not provide an unambiguous answer to this particular issue. Is anyone harmed by the addition of this validation rule?

**Comment by adamayoung** [comment]
I'm getting this problem too when using Google for authentication and getting a token for a different application. It's a show stopper.

**Comment by WilliamDenniss** [comment]
I'm in favor of merging #419 for the reasons that:

1. It implements standard behavior that is documented in the official OpenID Connect core spec (even if that spec contains an internal inconsistency).
2. It doesn't appear to impact anyone *not* using `azp`, so the implementation should theoretically be correct for those who are using `azp` without being incorrect for those _not_ using `azp`.

Does anyone believe that this rule change (accepting ID Tokens where `azp` matches the client ID) would either be against AppAuth's philosophy of only implementing standards-based flows, or be in any way detrimental to existing users who don't use `azp`?

**Comment by WilliamDenniss** [comment]
To get a second opinion on this, yesterday I asked AppAuth maintainers @iainmcgin and @tikurahul offline to consider this change from an architectural standpoint, they both felt it seemed OK.

I also conducted a thorough review of the OpenID Connect Core spec itself, and have made a comprehensive [proposal](https://bitbucket.org/openid/connect/issues/973/#comment-53339474) to resolve the inconsistencies I believe exist in the text.

It appears consistent with the `azp` definition in Section 2 that the `azp` can differ from the `aud`, and based on other text, that `azp` is semantically considered one of the audiences. Based on this interpretation, I believe the change in #419 is valid.

**Comment by petea** [comment]
This issue was fixed with the 1.1.0 release.
