### ISSUE TITLE
Doesn't show the browser on iOS 10.0 simulator

### ISSUE THREAD

**Issue by buscarini** [openid/AppAuth-iOS#420]
**Describe the bug**
I just tried using it on iOS 10.0 simulator, and it never shows the browser. On iOS 12 it works fine.

**To Reproduce**
1. Set it up
2. Run on iOS 10.0 simulator (iPhone SE)

**Expected behavior**
I guess a dialog should be displayed asking to continue, and then the browser should be displayed.

**Desktop (please complete the following information):**
Mojave 10.14.5
Xcode Version 10.2.1 (10E1001)

**Additional info**

I can't really test it on a device, as I can't downgrade any device to iOS 10, so it might just happen on the simulator.

**Comment by buscarini** [comment]
Nevermind. Turns out that I was presenting a modal view controller, but the browser was being presented on the window root view controller. This works on ios 12, but not on ios 10

**Comment by WilliamDenniss** [comment]
Glad you solved it!

AppAuth uses SFSafariViewController on iOS 10, there is no “continue”
dialog for that.
