### ISSUE TITLE
setNeedsTokenRefresh not refreshing tokens on performAction

### ISSUE THREAD

**Issue by ndguarino** [openid/AppAuth-iOS#422]
**Describe the bug**
OIDAuthState.setNeedsTokenRefresh is not causing an update of state to be passed to didChange(_ state: OIDAuthState) or a new access token to be given to OIDAuthState.performAction(freshTokens).

**To Reproduce**
1. Initialise a valid authState with a refresh_token grant
2. Call authState.setNeedsTokenRefresh()
3. Call authState.performAction {(...)}

**Expected behavior**
didChange(_ state) should receive the new OIDAuthState upon the first call to OIDAuthState.performAction, and the performAction call should return the new accessToken and idToken

**Smartphone (please complete the following information):**
 - Device: Simulator
 - OS: iOS 12.2

**Additional context**
Using commit "ae38a4a96d7c090c115b439d14b8b4da7b85196a"

Just from an initial look around, it looks like OIDAuthState.m is still calling _stateChangeDelegate.didChangeState inside OIDAuthState.didChangeState, which seems to be deprecated in favour of _stateChangeDelegate.didChange.

**Comment by julienbodet** [comment]
It works for me by using the example provided with AppAuth. I added a call to `setNeedsTokenRefresh()` before calling the user info endpoint and got the refreshed access token in both `didChangeState` and the callback of `performAction`.

> Just from an initial look around, it looks like OIDAuthState.m is still calling _stateChangeDelegate.didChangeState inside OIDAuthState.didChangeState, which seems to be deprecated in favour of _stateChangeDelegate.didChange.

didChangeState is not deprecated. I guess you are using Swift, in which case `func didChange(_ state: OIDAuthState)` is the Swift notation of the Objc `(void)didChangeState:(OIDAuthState *)state`.

Did you try using the example provided?

**Comment by ndguarino** [comment]
We used the Swift example as a basis for our code, with minor modifications (moving authstate to a singleton, disusing provided UI).

Repository with example of failure is here: https://github.com/cadmia/AppAuthRefreshFailureTest
It prints an access token before and after a performAction. It is set up for Salesforce, but changing the url in NetService.swift and the values in Info.plist will allow for testing. I was not able to include a clientId in this example.

**Comment by ndguarino** [comment]
I just tested with the provided Swift-Carthage example in the AppAuth-ios repository for completeness sake, adding only the following line after line 229
```
self.authState?.setNeedsRefreshToken()
```

Output was the following:
```
2019-07-27 09:23:51.091881-0400 Example[73797:2357536] [MC] Reading from private effective user settings.
Got authorization tokens. Access token: REMOVED
Performing userinfo request
Access token was fresh and not updated REMOVED
Success: [AnyHashable...
```

**Comment by julienbodet** [comment]
I tested your example against Google OAuth API and by changing some scopes to match my provider config. It works fine. I got the updated access token in the `didChange` callback and the `performAction`.

I guess what you experience might be an issue with your provider?

**Comment by ndguarino** [comment]
After further investigation, it's an issue with the Salesforce provider. It only returns a new accessToken on refresh if the old one has expired - if you try to refresh while the old token is active, it returns the old access token. It helpfully also does not include an expiry time.

My apologies for wasting your time with this one. Thank you for your help.

**Comment by julienbodet** [comment]
That’s what I was suspecting... I’m happy you found a solution!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
