### ISSUE TITLE
pod update -> AppAuth 1.0.0 -> docs out of date, no idea how to migrate

### ISSUE THREAD

**Issue by xaphod** [openid/AppAuth-iOS#425]
Today I did a pod update, and was upgraded from AppAuth 0.95.1 to 1.0.0.
This is odd, given that your changelog doesn't indicate that 1.0.0 is released yet.
Anyways, my projects do not compile anymore because I have no idea how to migrate this:

`[OIDAuthState authStateByPresentingAuthorizationRequest:request presentingViewController:vc callback:^(OIDAuthState * _Nullable authState, NSError * _Nullable error)`

to this:
`[OIDAuthState authStateByPresentingAuthorizationRequest:request externalUserAgent:??? callback:^(OIDAuthState * _Nullable authState, NSError * _Nullable error)`

Your README and API documentation all say to use the convenience method with presentingViewController, which no longer exists on `OIDAuthState`. I cannot find any updated documentation to help me.

What am I missing?

**Comment by julienbodet** [comment]
The first method you are referring to [still exists in 1.0.0](https://github.com/openid/AppAuth-iOS/blob/1.0.0/Source/iOS/OIDAuthState%2BIOS.h). The only difference with 0.95.1 is the return type, deprecated `OIDAuthorizationFlowSession` has been removed and renamed to `OIDExternalUserAgentSession'.

You can have a look at [the example](https://github.com/openid/AppAuth-iOS/blob/1.0.0/Examples/Example-iOS_ObjC/Source/AppAuthExampleViewController.m#L216) on how to use it.

**Comment by xaphod** [comment]
I apologize: even though I had carefully cleaned the build folder, this morning when I reinstalled the pods this problem just magically disappeared. I suppose somehow the AppAuth+iOS.h header wasn't being included properly. 
In any case thanks for your help!

**Comment by euroboy** [comment]
Version 1.2.0 doesn't contain the first method anymore, how to migrate?

**Comment by xaphod** [comment]
1.2.0 (still) contains `[OIDAuthState authStateByPresentingAuthorizationRequest:request presentingViewController:vc callback:^(OIDAuthState *_Nullable authState, NSError *_Nullable error) { }]`
If you're still using `OIDAuthorizationFlowSession` instead of `OIDExternalUserAgentSession`, just have a look at the type `OIDExternalUserAgentSession` and you'll figure it out: you hold a reference to it somewhere, and then call `resumeExternalUserAgentFlowWithURL` on it from your AppDelegate (from continueUserActivity etc)

**Comment by WilliamDenniss** [comment]
For 1.0, we removed all deprecated methods. As an upgrade path, I recommend upgrading to the last 0.9* release, resolving all deprecation warnings, then you should be able to go to 1.0 without issue.

**Comment by gaguiraud** [comment]
> 1.2.0 (still) contains `[OIDAuthState authStateByPresentingAuthorizationRequest:request presentingViewController:vc callback:^(OIDAuthState *_Nullable authState, NSError *_Nullable error) { }]`
> If you're still using `OIDAuthorizationFlowSession` instead of `OIDExternalUserAgentSession`, just have a look at the type `OIDExternalUserAgentSession` and you'll figure it out: you hold a reference to it somewhere, and then call `resumeExternalUserAgentFlowWithURL` on it from your AppDelegate (from continueUserActivity etc)

How do you call `resumeExternalUserAgentFlowWithURL` from continueUserActivity? continueUserActivity does not have a NSURL parameter.

Thanks!

**Comment by saru2020** [comment]
> > 1.2.0 (still) contains `[OIDAuthState authStateByPresentingAuthorizationRequest:request presentingViewController:vc callback:^(OIDAuthState *_Nullable authState, NSError *_Nullable error) { }]`
> > If you're still using `OIDAuthorizationFlowSession` instead of `OIDExternalUserAgentSession`, just have a look at the type `OIDExternalUserAgentSession` and you'll figure it out: you hold a reference to it somewhere, and then call `resumeExternalUserAgentFlowWithURL` on it from your AppDelegate (from continueUserActivity etc)
> 
> How do you call `resumeExternalUserAgentFlowWithURL` from continueUserActivity? continueUserActivity does not have a NSURL parameter.
> 
> Thanks!

For the record, URL is accessible: 'userActivity.webpageURL'
