### ISSUE TITLE
Add as Static Library missing files.

### ISSUE THREAD

**Issue by ktran03** [openid/AppAuth-iOS#427]
**Describe the bug**
I created a new blank project, added the library, linked the library, then added the header search path ("AppAuth-iOS/Source").

I get the error for 8 files.
Build input file cannot be found: '/Users/xxx/Developer/appauthtest/Source/iOS/OIDExternalUserAgentIOS.m'
 "
:-1: Build input file cannot be found: '/Users/xxx/Developer/appauthtest/Source/iOS/OIDExternalUserAgentIOS.m'

"
**To Reproduce**
1. Create new project
2. Right click project, click add files
3. Select AppAuth.xcodeproj
4. Under app target, go to linked frameworks and libraries, select AppAuth-iOS.a
5. Add "AppAuth-iOS/Source" in app target header search paths
6. Build

**Expected behavior**
It should build without errors.

**Smartphone (please complete the following information):**
-Simulator iPhone Xs, Physical device iPhone 7 plus

**Comment by WilliamDenniss** [comment]
Did you add it recursively? Those files are in the iOS directory under Source. I see them included in the static binary target, so I'm not sure what the problem is.

**Comment by kingofkings00** [comment]
ok?????????

Sendt fra min iPhone

**Comment by WilliamDenniss** [comment]
I'm not sure what the bug is here, but if you found one - please file a pull request with the fix!
