### ISSUE TITLE
Login by providing email and password

### ISSUE THREAD

**Issue by peterpaulis** [openid/AppAuth-iOS#440]
How to login by providing email and password, without opening any webview?

I looked at the sample and the documentation and didn't found a way for this, can you pinpoint me on this?

**Comment by WilliamDenniss** [comment]
This library is for OAuth, not username and password login.

**Comment by fukemy** [comment]
hi @peterpaulis did u find any solution?

**Comment by lordzsolt** [comment]
> This library is for OAuth, not username and password login.

No, this library is a partial implementation of the OAuth/OpenID Connect protocol, which excludes two-legged resource owner flow.
You assume everyone is using a separate Identity Provider (aka doing social login), and exclude the scenario where the server, client and the identity provider are owned by the same company, which eliminates the insecure client problem.
(I already have access to the database, there's no point in me stealing the client credentials...)

----

@fukemy This issue describes a potential solution: https://github.com/openid/AppAuth-iOS/issues/593
