### ISSUE TITLE
Nullability warning in OIDExternalUserAgentIOS

### ISSUE THREAD

**Issue by PGaissert** [openid/AppAuth-iOS#442]
In version 1.2.0 of AppAuth I get a nullability warning in Xcode 10.3 (10G8) at the follow line of code:

@interface OIDExternalUserAgentIOS : NSObject<OIDExternalUserAgent>
**- (nullable instancetype)init API_AVAILABLE(ios(11))
    __deprecated_msg("This method will not work on iOS 13, use "
                     "initWithPresentingViewController:presentingViewController");**

the warning reads:
**Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'**

For the time being I amended the issue be surrounding the line of code with:
_#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnullability"_
**- (nullable instancetype)init API_AVAILABLE(ios(11))
    __deprecated_msg("This method will not work on iOS 13, use "
                     "initWithPresentingViewController:presentingViewController");**
_#pragma clang diagnostic pop_

Would be great if you could fix this in the next version.

**Comment by bpollman** [comment]
Is there any reason not to merge this? Would love to see these warnings get cleaned up.

**Comment by Parameswaran-Irulandi** [comment]
Can you please merge this PR?

**Comment by bryanrahn** [comment]
Can we merge this in? 

To save others the headache, your project (after performing Clean Build Folder) if you have `SWIFT_TREAT_WARNINGS_AS_ERRORS = YES` in your build settings will fail to compile.

**Comment by Wooder** [comment]
Is there a reason not to merge this?  Maybe that's just been forgotten?

**Comment by below** [comment]
Probably because this is more a problem of project configuration: I have an old project, where I get this issue (an error actually) after trying to update AppAuth.
In a brand new project, however, I don't get any warning.

I am out of ideas why this is the case …
