### ISSUE TITLE
ID Token expired when device is set to a future date manually

### ISSUE THREAD

**Issue by karansota** [openid/AppAuth-iOS#443]
When I set the iOS device date time to a future date manually and then try to login, it always fails with the following error:

Error Domain=org.openid.appauth.general Code=-15 "ID Token expired" UserInfo={NSLocalizedDescription=ID Token expired}

**Comment by WilliamDenniss** [comment]
That's the intended behavior. The ID Token expire on a particular date and time, you have presumably set the device to be after that date.

**Comment by fedu44** [comment]
I had the same problem due to having my device time set manually, just set it to automatic and the error should disappear. Hope to help you @karansota .
