### ISSUE TITLE
Please remove 'UIWebView' reference in AppAuth.h

### ISSUE THREAD

**Issue by istvanelekes** [openid/AppAuth-iOS#449]
Introduction text contains 'UIWebView' and I guess that is way Apple sending me:
"ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs ."

**Comment by WilliamDenniss** [comment]
Being this line:

https://github.com/openid/AppAuth-iOS/blob/e07ba3325e2b5e9cca1c7a022715fe98368dd18d/Source/AppAuth.h#L77

Interesting theory. I guess we could just say "web view" instead of 'UIWebView', but it would be nice of Apple to fix their false positive.

Someone with a CLA on file want to file a PR?

**Comment by julienbodet** [comment]
@istvanelekes are you still experiencing this issue?

**Comment by istvanelekes** [comment]
No, thanks for your effort.

**Comment by julienbodet** [comment]
Thanks for the update. I'm closing this, feel free to reopen if the issue happens again.

**Comment by DanielWijonoJacksLabs** [comment]
so how do you resolve the issue ? just change the text in appAuth.h ?

**Comment by vibhaalchemy** [comment]
I'm still facing this issue. Please help me out with this issue.
```for the auth request. `UIWebView` and `WKWebView` are explicitly *not*```

**Comment by paigeyahnke** [comment]
I'm also having this issue and it looks like Apple is planning on rejecting apps soon: https://developer.apple.com/news/?id=12232019b

I originally thought it was just a different cocoapod causing issues, but I removed that cocoapod and now when I do a search for UIWebView in the code base, the only instance is this comment.

**Comment by julienbodet** [comment]
Thanks @vibhaalchemy @paigeyahnke for letting us know about this still happening! I reopened the issue and opened PR #515.

**Comment by kobeli** [comment]
@julienbodet I'm still facing this issue. Does it merge to master? Thanks.

**Comment by vijayan-sop** [comment]
i am also getting same issues can you tell me with some clarifications.

We identified one or more issues with a recent delivery for your app, "onecchat" 1.0 (4). Please correct the following issues, then upload again.

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).
