### ISSUE TITLE
Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by RanjeetStiga** [openid/AppAuth-iOS#450]
Hi, 
I am using dev-logout branch. Today i have upload build on test flight xcode 10.3.  I have received message from Apple.

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
Best regards,
The App Store Team

**Comment by WilliamDenniss** [comment]
AppAuth doesn't use UIWebView, but this could be a false positive. Tracking here: #449
