### ISSUE TITLE
How do I update the OIDAuthState object after `performAction(freshTokens:`

### ISSUE THREAD

**Issue by DMCApps** [openid/AppAuth-iOS#453]
Hello,

I'm wondering how do I update the OIDAuthState object after getting fresh tokens from the `performAction(freshTokens:`?

```swift
authManager.performAction(freshTokens: { (accessToken, idToken, error) in
    guard error == nil else {
        log.error("Failed to refresh token with Error: \(error!.localizedDescription)")
        return
    }
                
    // TODO: How to update the access tokens on the state
    // Perform original request.
})
```

**Comment by DMCApps** [comment]
Looks like the token in my saved OIDAuthState updates however I'm looking for some callback that is triggered to re-save this new state for future use as it doesn't seem to call the `func didChange(_ newState: OIDAuthState)` method

**Comment by julienbodet** [comment]
@DMCApps This should be working, did you set the delegate on the state object?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DMCApps** [comment]
@julienbodet Ah I think that was the issue. I was setting the delegate on the object initially but when reloading the app and getting the state from the keychain I was forgetting to reset it there. My apologies on this one and great library! Really appreciate the work on this!
