### ISSUE TITLE
Whether we can login with user email and password by using user email and user password

### ISSUE THREAD

**Issue by dli-conviva** [openid/AppAuth-iOS#457]
Do we have a api to get token by passing clientid, clientsecret, user name, user password and other parameters in iOS client

**Comment by dermaaarkus** [comment]
Dear @dli-conviva, unfortunately your questions seems not to be understood, because no one replied to it yet. Please clarify your request or close the issue, if its not relevant anymore. Thanks

**Comment by vijayradke** [comment]
@dermaaarkus His question is related to Password flow where we can provide username and password instead showing login screen in webview. Here he has his login screen where he takes username and password from user and want to pass these to this library to get token. I hope this clears his question.

**Comment by vijayradke** [comment]
@dli-conviva I assume [This issue](https://github.com/openid/AppAuth-iOS/issues/370) is similar to your issue

**Comment by dli-conviva** [comment]
> @dli-conviva I assume [This issue](https://github.com/openid/AppAuth-iOS/issues/370) is similar to your issue

**Comment by vijayradke** [comment]
@dli-conviva  Have you solved your issue? if yes could you please provide some details?
