### ISSUE TITLE
Dispatching callback/completion/action blocks on the main queue is not always appropriate

### ISSUE THREAD

**Issue by tpesce** [openid/AppAuth-iOS#46]
There are a few methods where callback blocks are dispatched on the main queue:

```
+ [OIDAuthorizationService discoverServiceConfigurationForDiscoveryURL:completion:]
+ [OIDAuthorizationService performTokenRequest:callback:]
- [OIDAuthState withFreshTokensPerformAction:]
```

This strategy makes sense if the callback block is expected to directly perform UI updates, but this will not always be the case. In cases where the callback blocks instead perform significant computation, this behavior is generally undesirable and forces calling code to perform additional dispatching.

I think it would be ideal if a mechanism could be provided to specify the queue for callback dispatch. For possible approaches, take a look at the mechanisms provided by NSURLSession and Alamofire.

**Comment by StevenEWright** [comment]
I, for one, would not be opposed to seeing this feature added. Certainly, the motivation for dispatching the main thread was simplicity - it's the safe choice in the absence of any way to customize the behavior. I do think that if we add a feature to control this, that: existing code should continue to work as-is. So long as we can accomplish that, and don't add signifigant complexity to the API or the implementation, then LGTM. If William feels the same, I'd say "Feel free to submit a PR!"

**Comment by tpesce** [comment]
Thanks @StevenEWright. If @WilliamDenniss things this is worth moving forward, I'd love to work on a PR. My initial thoughts for a solution are to: 1) Overload the identified methods to accept a dispatch queue, or 2) Provide class-level configuration for setting the dispatch queue. In both cases the default would continue to be the main queue, so backward compatibility would be preserved.

**Comment by WilliamDenniss** [comment]
My vote is for a class-level configuration setting. Hoping to avoid too many additive method definitions (similar design comment as to #28).

I'd be happy to see a PR with this enhancement.

**Comment by WilliamDenniss** [comment]
The main place where this matters is `withFreshTokensPerformAction`. Users of AppAuth may call that for every authorized API call, which could be high frequency.  

The token refresh is invoked once-per-refresh (e.g. once per hour for Google's server). The rest are basically one-time use, at the time of authorization, so there's a diminishing return of value to allow for custom dispatch queues everywhere.

What if we just solve `withFreshTokensPerformAction`, either with an additional param on that method, or a property (not class method!) on OIDAuthState?

**Comment by WilliamDenniss** [comment]
PR #273 gives the user the ability to specify the dispatch queue for `withFreshTokensPerformAction` this covers the vast majority of blocks that are called by volume, including the token refresh and user's API calls.
