### ISSUE TITLE
Logout popup says 'Log in' instead of 'Log out'

### ISSUE THREAD

**Issue by ktran03** [openid/AppAuth-iOS#461]
**Are you filing an issue about iOS 12?**
No

**Describe the bug**
When you logout, the UIAlertViewController title says 'Wants to Use 'app_name' to Sign In'. Can this be changed to 'Sign Out' ?

**To Reproduce**
1. Implement 'OIDAuthorizationService.present(request, externalUserAgent: agent, callback: { (response, error) in'
2. In app, trigger a logout

**Expected behavior**
Instead of the popup saying 'Log in' it should say 'Log out'.

**Screenshots**

**Desktop (please complete the following information):**
 - iOS 12

**Smartphone (please complete the following information):**
 - Simulator

**Comment by ktran03** [comment]
![73ef7b77-c1fd-49f2-b052-063d50cccb12](https://user-images.githubusercontent.com/3146415/67528157-9dc03b80-f66d-11e9-8a06-2429d2479108.jpg)

**Comment by julienbodet** [comment]
This is a system popup and there is no way to change it currently.

**Comment by ktran03** [comment]
In that case I'll close this issue.

**Comment by lukenewman** [comment]
i'd like to re-open this issue

**Comment by sethi-ishmeet** [comment]
@ktran03 How are you logging out of the app? in my case, after this popup shows, it takes to the login page instead of logging out the user.

**Comment by sethi-ishmeet** [comment]
@jakeherrmann04 In my case, I was missing `PostLogoutRedirectUri` in our Identity Server Database. Once I added it, the sheet would dismiss after logout.

**Comment by fukemy** [comment]
hello, can we avoid to show popup and just open webpage to logout? Thanks

**Comment by atif-khan** [comment]
Is this still not resolved?

**Comment by lehelmedves** [comment]
> @jakeherrmann04 In my case, I was missing `PostLogoutRedirectUri` in our Identity Server Database. Once I added it, the sheet would dismiss after logout.

The sheet disappears when the logout is performed on the identity server, however I do not get anything in the callback on iOS. This callback is never called:

```
OIDAuthorizationService.present(request, externalUserAgent: externalUserAgent) { _, _  in
    print("---------------------> WENT INTO THE COMPLETION!!!!!!")
}
```

Any ideas why?

**Comment by saurabh297** [comment]
Is this still not resolved?

**Comment by Ravi-Kiran-HR** [comment]
Is this still not resolved? I am facing the same 'Login in' alert while invoking presentEndSessionRequest still on pod 'AppAuth', '1.7.1'
