### ISSUE TITLE
Credentials are stored after token expiration. 

### ISSUE THREAD

**Issue by sdprogov** [openid/AppAuth-iOS#465]
I understand that what's storing the user credentials is ASWebAuthenticationSession or SFAuthenticationSession, but I need a way to kill these sessions short of killing the app when a token expires. 

The normal workflow for our app is to auto-logout the user if the token expires. Right now, what happens is when the user clicks the login button, AppAuth simply refetches a new token behind the scenes, not forcing them to re-enter their credentials which is what we require.

I'm aware about the OIDEndSessionRequest, and it works when the user manually chooses to logout but this will not work when we need to force the user to be logged-out.

If there is an existing API/function that allows for this, please point me in the right direction. If not,  is there plans to include one?

**Comment by WilliamDenniss** [comment]
It's really up to the OAuth / OpenID Provider to end their active sessions in the browser tab if that's what they desire. AppAuth is working as intended here (deferring to the OAuth / OpenID Provider).
