### ISSUE TITLE
Fix Static Code Analysis Issue in OIDRegistrationRequest.m if possible

### ISSUE THREAD

**Issue by kmdarshan** [openid/AppAuth-iOS#467]
![Screen Shot 2019-11-04 at 4 19 18 PM](https://user-images.githubusercontent.com/630991/68168822-fbcb0980-ff1e-11e9-9c41-7874eb760001.png)

Please see the screen shot attached to refer to the lines of code where I am getting an error when I run this file under the xcode static analyzer.

**Comment by WilliamDenniss** [comment]
Pull requests (with a CLA) are welcome.
