### ISSUE TITLE
SDK 13.2 - general error -3 when trying to sign in

### ISSUE THREAD

**Issue by sdprogov** [openid/AppAuth-iOS#471]
**Describe the bug**
After upgrading to Xcode 11.2, and building the application, and trying to sign in general error -3 results. This does not happen when building with Xcode 11.0. 

**To Reproduce**
1)Make sure your Xcode is 11.2, and build the application (either device or simulator reproduces this)
2)Have code that calls authStateByPresentingAuthorizationRequest
3)User will be presented with system popup asking them to "continue" or "cancel" 
4)After pressing "continue", immediately callback with -3 error. However if this exact same code base was built with Xcode 11.0, it works fine. 

**Expected behavior**
Proceed to Login browser

**Desktop (please complete the following information):**
 - OS:Xcode 11.2 is relevant here
 - Version (1.2.0)

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - OS: 13.1

**Additional context**
This is due to upgrading Xcode to 11.2 (released Oct 31) and rebuilding the application against the latest Xcode.

**Comment by rursache** [comment]
same issue on xcode 11.2.1

**Comment by sdprogov** [comment]
Closing this issue. Turns out the version was not 1.2.0 and was the difference, not the Xcode version.

**Comment by rursache** [comment]
@sdprogov how did you fix this? i’m using the latest code from master branch and still having this issue. thanks
