### ISSUE TITLE
clang static code analyzer issues with AppAuth sdk

### ISSUE THREAD

**Issue by PraveenKolipaka1** [openid/AppAuth-iOS#472]
Platform details: Mac OSX 10.14.5,,Xcode 10.2
SDK: https://github.com/openid/AppAuth-iOS/releases/tag/0.95.1

clang static code analyzer is notifying few complaints (5 different bugs) as below.
Attached complete clang bug report .
[Archive.zip](https://github.com/openid/AppAuth-iOS/files/3816309/Archive.zip)
Needed SDK which has fixes for the above stated false positive bugs?

**Comment by WilliamDenniss** [comment]
For this type of analysis (improving overall quality, rather than looking at specific behavioral bugs), I'd rather see a pull request that fixes it than a bug report.
