### ISSUE TITLE
Authorize endpoint query parameters are overwritten when creating an AuthorizationRequest with additional parameters

### ISSUE THREAD

**Issue by adamayoung** [openid/AppAuth-iOS#475]
**Are you filing an issue about iOS 12?**
No

**Describe the bug**
When using Microsoft Azure AD B2C, the policy query parameter ("p") specified in the well known authorize endpoint gets overwritten when additional parameters are supplied when creating the authorisation request.

Seems to be happening here:
https://github.com/openid/AppAuth-iOS/blob/e07ba3325e2b5e9cca1c7a022715fe98368dd18d/Source/OIDAuthorizationRequest.m#L338

**To Reproduce**
1. Configure AppAuth to authenticate against an Azure AD B2C using its well known enpdoint
2. Create an AuthorizationRequest with the service configuration and additional parameters e.g. prompt=login, login_hint=
3. print out the authorisation request URL
4. When the service configuration's authorize endpoint url contains any query parameters, they are overwritten by the additional parameters you supply to the AuthorizationRequest

**Expected behavior**
I would not expect query parameters in the well known endpoint's authorize endpoint to be overwritten when additional parameters (as the name suggests) are supplied

**Smartphone:**
 - Device: iPhone 11 Pro Max
 - OS: iOS 13.2.2

**Comment by Highspeed7** [comment]
I believe I'm facing this same issue... I'm using react native and whenever it attempts to navigate to the login portal I get a popup saying "my app" wants to Use "microsoftonline.com" to Sign In... once I click continue, it navigates to simply login.onmicrosoft.com instead of to the appropriate policy I initially defined; So my login flow is never initiated.

**Comment by cwe1ss** [comment]
Same issue, I think. The IdP we're using has a required query string parameter in its URL and it therefore uses a wrong URL on iOS. Login works fine on Android.

**Comment by ehvattum** [comment]
We are experiencing the same issue.

**Comment by ehvattum** [comment]
A workaround we have found to work is issuing all the enpoints directly, and not use dynamic discovery.
- Remove any query parameters from the authorize-request
- Add the required additional query paramter to additionalParameters: `p=b2c_1_signinup` in our case.

We use this library through react-native-app-auth, and this configuration also work on the android version of appauth.

**Comment by WilliamDenniss** [comment]
If there's a patch for AppAuth that doesn't introduce spec non-compliant behavior, I'd be happy to consider it.

**Comment by bryanCancelWT** [comment]
@ehvattum @WilliamDenniss @mdanazhiev 
if this is still relevant
another solution was suggested by me here
https://github.com/MaikuB/flutter_appauth/issues/242

it's what I'm currently using
