### ISSUE TITLE
Sharing session between Safari (web app) and iOS app

### ISSUE THREAD

**Issue by deeplinkage** [openid/AppAuth-iOS#477]
I'm using AppAuth successfully to log in to my iOS application. It is using idP, I get the login page and I'm able to get the tokens successfully. No issues there.

I need to implement functionality using iOS URL schema, where user will click on the Download button on the web, and open up the iOS app and start the download on mobile app.

We don't use persistent cookies on the web app. 

Question: Is is possible to share the session from web to iOS mobile app since user is logged in on web, and to log in user on mobile automatically if it's not logged in already.

Thanks in advance.

**Comment by WilliamDenniss** [comment]
Persistent cookies are shared between Safari and the external user agent that AppAuth uses, so if you have a persistent cookie, the user can already be signed in. This means they won't need to sign in all over again, however, it's still not completely automatic.

If you don't use persistent cookies, then no state is shared.
