### ISSUE TITLE
API_UNAVAILABLE(macCatalyst) prevents Xcode 10 from compiling version 1.3.0

### ISSUE THREAD

**Issue by acruis** [openid/AppAuth-iOS#489]
**Describe the bug**
It doesn't seem like Xcode 10 can parse `API_UNAVAILABLE(macCatalyst)`, which was [introduced](https://github.com/openid/AppAuth-iOS/commit/7b6c272f515f3de23ccde0b2928744d176443dc3#diff-1e5249f3cee1bc23315210419d34ca19R30) in class and method declarations moving from 1.2.0 to 1.3.0. This causes compilation to fail where `macCatalyst` is used to mark availability.

A suggestion is to instead wrap the class/method definitions with
```objc
#if !TARGET_OS_MACCATALYST
// Code to exclude from Mac.
#endif
```
as suggested by [Apple documentation](https://developer.apple.com/documentation/xcode/creating_a_mac_version_of_your_ipad_app?language=objc).

**To Reproduce**
1. Compile the project in Xcode 10 

**Expected behavior**
Successful compilation instead of failing at `OIDExternalUserAgentIOS` and other classes which rely on `macCatalyst` for marking API availability.

**Screenshots**
![Screenshot 2019-11-25 at 3 23 24 PM](https://user-images.githubusercontent.com/8437638/69520524-e71ae800-0f97-11ea-96c7-67360f0dc236.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Xcode version: 10.2.1
- Cocoapods: 1.6.1

**Additional context**
I found a StackOverflow question from someone experiencing this problem as well: https://stackoverflow.com/questions/59023380/firebase-ios-swift-authentication-api-unavailablemaccatalyst-problem

**Comment by ouachman** [comment]
Same happening for me. For the time being I am staying on 1.2.0

**Comment by WilliamDenniss** [comment]
The policy of AppAuth is only to target the current base SDK, and current versions of Xcode (which is Xcode 11), which is why the Catalyst support doesn't have Xcode checks. Using Xcode 11 you can still target back to iOS 8, as we support a deployment target of iOS 8.

We do use `#if !TARGET_OS_MACCATALYST` exactly in the way suggested by Apple that you linked (to guard against code not supported on Mac). If we wanted to support Xcode 10, the correct approach would be using IOS version #defines, like so:

```
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000
#endif
```

This is what we use on the beta branches, for example.

So this isn't a bug in the Catalyst implementation, it's just the reality of us no longer supporting Xcode 10.

The reason we don't support Xcode 10 is that there's not really any value. You may as well be using version 1.1.0, as 1.2.0 and 1.3.0 add features that would simply be #ifdef'd out for you anyway.

To reiterate, while we only support the latest SDK for compiling, we support a deployment target of iOS 8, and if you need to build on older SDKs, you can always use older versions.

**Comment by ouachman** [comment]
Thanks for the clear explanation.

On our side we have a clear policy about iOS base SDK. And as of today, iOS13 has not been cleared out yet. So we must keep building under iOS12, which is not possible using Xcode 11 as Xcode does not allow to change the base SDK. So we have to stick with Xcode 10.

For the time being we will stay under AppAuth 1.2.0 then.

As iOS 13 is not required to be the base SDK until march 2020, do you think manually do the change you suggested will be enough to build AppAuth 1.3.0 under Xcode 10? I would not want to miss any new developments in the meantime.

**Comment by wilmarvh** [comment]
You could argue that not supporting Xcode 10 anymore is a breaking change, which would've warranted version 2.0.0 instead of a minor bump to 1.3.0.

**Comment by acruis** [comment]
That's an interesting point.

At surface level, this is not a "breaking" code change. The user doesn't have to update their code due to the change from `1.2.0` to `1.3.0`. On the other hand, users do have to update their compilation toolchain as Xcode 10 doesn't compile the new code.

In the first place, the `API_(UN)AVAILABLE` macro is not anything new, so I imagine this change could've been tricky to determine as "breaking Xcode 10".

You could even argue that this is because CocoaPods doesn't allow specifying the minimum Xcode version. [Rust crates](https://users.rust-lang.org/t/rust-version-requirement-change-as-semver-breaking-or-not/20980) has an ongoing discussion that seems very similar to this.

**Comment by wilmarvh** [comment]
> You could even argue that this is because CocoaPods doesn't allow specifying the minimum Xcode version. 

This problem exists without the use of CocoaPods though. Opening the example project with Xcode 10 yields the same compilation error.

**Comment by acruis** [comment]
Right, CocoaPods is only slightly related in the sense that it'd install 1.3.0 for you as long as the lockfile is not present and the version requirement is `~> 1.0`, regardless of whether your Xcode actually supports it.

Off the top of my head I don't see any drawbacks to bumping to `2.0.0` either, but maybe there are some?

**Comment by ckOfor** [comment]
Any fix?

**Comment by yortyrh** [comment]
Hello, this is saying 'wontfix'. Is there any work around?

**Comment by xhirazi** [comment]
+1

**Comment by ArtiomLK** [comment]
Updating to Xcode 11.2 fixed the problem for me.

**Comment by anastely** [comment]
Any updates ?

**Comment by MahmoudShaeer** [comment]
+1000000

**Comment by vishalsiddhi** [comment]
Facing same issue. Any updates?

**Comment by julienbodet** [comment]
Please see https://github.com/openid/AppAuth-iOS/issues/489#issuecomment-558378834 above.

**Comment by vishalsiddhi** [comment]
> Please see [#489 (comment)](https://github.com/openid/AppAuth-iOS/issues/489#issuecomment-558378834) above.

Thanks for your reply. 

I had checked but didn't able to figure out that what exactly I need to do? Do I need to use this with only latest Xcode? Currently I am using Xcode 10.2.1.

What changes I need to apply to use this with Xcode 10.2.1 ?

**Comment by vishalsiddhi** [comment]
> Please see [#489 (comment)](https://github.com/openid/AppAuth-iOS/issues/489#issuecomment-558378834) above.

I am able to resolve this issue by below steps : 

close Xcode
rm -rf ~/Library/Developer/Xcode/DerivedData/
pod deintegrate
pod install
restart Xcode

Thanks for response.

**Comment by acruis** [comment]
> > Please see [#489 (comment)](https://github.com/openid/AppAuth-iOS/issues/489#issuecomment-558378834) above.
> 
> I am able to resolve this issue by below steps :
> 
> close Xcode
> rm -rf ~/Library/Developer/Xcode/DerivedData/
> pod deintegrate
> pod install
> restart Xcode
> 
> Thanks for response.

You sure this works? How does your Podfile look like? Are you sure you're still using Xcode 11 to build?

**Comment by matheuscuba** [comment]
Downgrading de version of the library to `1.2.0` solved my problem:

In my Podfile:
`pod 'AppAuth', '1.2.0'`

Had to delete `Podfile.lock` and then run 

`rm -rf ~/Library/Caches/CocoaPods; rm -rf Pods; rm -rf ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install;`

to reset and reinstall all pods

**Comment by nikollaih** [comment]
> > Please see [#489 (comment)](https://github.com/openid/AppAuth-iOS/issues/489#issuecomment-558378834) above.
> 
> I am able to resolve this issue by below steps :
> 
> close Xcode
> rm -rf ~/Library/Developer/Xcode/DerivedData/
> pod deintegrate
> pod install
> restart Xcode
> 
> Thanks for response.

It works for me, thank you  (Xcode 11.4)

**Comment by anastely** [comment]
Guys, Is necessary to update Xcode to 11.4 to solve this issue? 

because I have Mojave right now and i can't update Xcode because it's required macOS 10.15.2 or later and I don't have?

**Comment by acruis** [comment]
@anastely Use 1.2.0 instead of 1.3.0

**Comment by anastely** [comment]
@acruis THANK YOU

**Comment by acruis** [comment]
To summarize the fix: **Use 1.2.0**

**Comment by DenisSouza2019** [comment]
> Fazer o downgrade da versão da biblioteca para `1.2.0`resolver meu problema:
> 
> No meu Podfile:
> `pod 'AppAuth', '1.2.0'`
> 
> Tinha que excluir `Podfile.lock`e depois executar
> 
> `rm -rf ~/Library/Caches/CocoaPods; rm -rf Pods; rm -rf ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install;`
> 
> redefinir e reinstalar todos os pods

**Simple and effective method!**

**Comment by KushalDesai1** [comment]
> Thanks for the clear explanation.
> 
> On our side we have a clear policy about iOS base SDK. And as of today, iOS13 has not been cleared out yet. So we must keep building under iOS12, which is not possible using Xcode 11 as Xcode does not allow to change the base SDK. So we have to stick with Xcode 10.
> 
> For the time being we will stay under AppAuth 1.2.0 then.
> 
> As iOS 13 is not required to be the base SDK until march 2020, do you think manually do the change you suggested will be enough to build AppAuth 1.3.0 under Xcode 10? I would not want to miss any new developments in the meantime.

Hello. I am actually a React Native developer with Android background. I checked my podfile but there is nothing. Can you please explain how to downgrade AppAuth? 

I am using Xcode 10.1

**Comment by aecvargas** [comment]
> Downgrading the version of the library to `1.2.0` solved my problem:
> 
> In my Podfile:
> `pod 'AppAuth', '1.2.0'`
> 
> Had to delete `Podfile.lock` and then run
> 
> `rm -rf ~/Library/Caches/CocoaPods; rm -rf Pods; rm -rf ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install;`
> 
> to reset and reinstall all pods

I used this solution to fix the initial problem but I am now getting more issues than before

> /Users/user/Desktop/Application/demo/platforms/ios/App/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.h:7:84: Cannot find protocol declaration for 'ASAuthorizationControllerDelegate'; did you mean 'UINavigationControllerDelegate'?

> /Users/user/Desktop/Application/demo/platforms/ios/App/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.h:7:119: Cannot find protocol declaration for 'ASAuthorizationControllerPresentationContextProviding'

> /Users/user/Desktop/Application/demo/platforms/ios/App/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.m:505:28: Property 'credential' not found on object of type '__strong id'

> /Users/user/Desktop/Application/demo/platforms/ios/App/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.m:506:13: Use of undeclared identifier 'ASAuthorizationAppleIDCredential'

There are a couple more but I assume they're all somehow related and this is because I've downgraded the AppAuth but I can't seem to find any other solution that doesn't result in the same or more errors.

This is also running on `Ionic V1 ios@5.0.0` because I have `Xcode version 10.1` and I am unable to update the version of Xcode due to the OS version I am running on `macOS High Sierra Version 10.13.6`.
