### ISSUE TITLE
Manually delete access token on logout from OIDAuthState

### ISSUE THREAD

**Issue by vin25** [openid/AppAuth-iOS#491]
Is there a way to manually delete the access token + other required details from the OIDAuthState object and keep the refresh token?

As I understand, it can be done using OIDEndSessionRequest via the server. I am looking for a way to do it locally without the server. When the user presses logout, I would like to locally discard the access token and any other details (if required) while keeping the refresh token.

**Comment by WilliamDenniss** [comment]
This isn't supported. However, you can extract the refresh token directly and do whatever you like with it.
