### ISSUE TITLE
Can't build ios framework with carthage 

### ISSUE THREAD

**Issue by g52302010** [openid/AppAuth-iOS#492]
When i run carthage update --platform ios i got failed log as below: 
** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/aragon_mini2/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/AppAuth-iOS/7e0b5c100d69caac34372efdad34b22b3464ddea/Build/Intermediates.noindex/ArchiveIntermediates/AppAuth_iOS/IntermediateBuildFilesPath/AppAuth.build/Release-iphoneos/AppAuth_iOS.build/Objects-normal/armv7/OIDExternalUserAgentIOSCustomBrowser.o /Users/aragon_mini2/Downloads/AppAuth-iOS-1.2.0/Examples/Example-iOS_ObjC-Carthage/Carthage/Checkouts/AppAuth-iOS/Source/iOS/OIDExternalUserAgentIOSCustomBrowser.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

I don't know why this happen because it only happens on ios platform. When i run  carthage update --platform wathos/tvos/macos it build success. 
I do this on xcode 10.2.1 and AppAuth 1.2.0.

**Comment by julienbodet** [comment]
I see you use the AppAuth's example. If you didn't make any change to the Cartfile, you'll be building last commit of master (remote repository) which is version 1.3.0 and doesn't support Xcode 10 (see #489). You can verify which commit you point to in the `Cartfile.resolved` file.

If you want to continue using Xcode 10, then point to version 1.2.0 by updating your Cartfile to:
```
github "openid/AppAuth-iOS" == 1.2.0
```

Let me know if that works for you.

**Comment by g52302010** [comment]
> I see you use the AppAuth's example. If you didn't make any change to the Cartfile, you'll be building last commit of master (remote repository) which is version 1.3.0 and doesn't support Xcode 10 (see #489). You can verify which commit you point to in the `Cartfile.resolved` file.
> 
> If you want to continue using Xcode 10, then point to version 1.2.0 by updating your Cartfile to:
> 
> ```
> github "openid/AppAuth-iOS" == 1.2.0
> ```
> 
> Let me know if that works for you.

It works for me. Thank you very much.
