### ISSUE TITLE
Two endpoints for token requests

### ISSUE THREAD

**Issue by QuentinArnault** [openid/AppAuth-iOS#494]
Hi,

I have integrated the AppAuth-iOS library with success for login/logout feature. 👍

I'm integrating now the refresh procedure with the `performActionWithFreshTokens` and I have some difficulties. As far as I understand the refresh tooken request is handled inside the `performActionWithFreshTokens` function with the url setup with the `OIDServiceConfiguration`.
The `tokenEndpoint` set is used for the access token request and the refresh access token request. But in our case we have one endpoint by kind of request.
`<baseURL>/token` for access token request
`<baseURL>/oauth2/token` for refresh token request

How is it possible to handle this with AppAuth library?

**Comment by WilliamDenniss** [comment]
RFC 6749 specifies these as the same endpoint (the "token endpoint") for both these requests. 

Token endpoint specified in `Section 3.2 Token Endpoint`, and referenced in  `4.1.3.  Access Token Request`, and `6.  Refreshing an Access Token`. Furthermore, the discovery specifications only support a single "token endpoint".

Unfortunately, it appears your server may not be fully spec compliant in this regard.
