### ISSUE TITLE
Support for native login screen and social signup / signing 

### ISSUE THREAD

**Issue by PrasadPotale** [openid/AppAuth-iOS#497]
Our client wants native login screen, also social signup invocation after the native button clicks, is there any documentation available which we can refer?

We are able to implement both login and social signup and sign in with the latest SDK but client do not like the approach of showing login screen in the webview.

I'm looking for the help for login, social signup and social signin apis integration with the SDK.

Thanks.

**Comment by Allan-Nava** [comment]
i use the social login with additional parameters with keycloak using kc_idp_hint=google but i can't get the token, with Android it works!

**Comment by WilliamDenniss** [comment]
This library is for OAuth, not native or social signup. You could however integrate this library into another library that did offer those functions.

**Comment by Allan-Nava** [comment]
> This library is for OAuth and OpenID Connect, not native or social signup. You could however integrate this library into another library that did offer those functions.

Ok thanks
