### ISSUE TITLE
UIWindowScene not active when running App from Shortcut Items (Home screen quick actions)

### ISSUE THREAD

**Issue by urosMihailovic** [openid/AppAuth-iOS#498]
**Describe the bug**
When trying to authenticate the user after he launched the App through the quick action I get:
`Error Domain=org.openid.appauth.general Code=-3 "(null)" UserInfo={NSUnderlyingError=0x60000299a7f0 {Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=3 "The UIWindowScene for the returned window was not in the foreground active state." UserInfo={NSDebugDescription=The UIWindowScene for the returned window was not in the foreground active state.}}}` and as a result no login form is presented. Interesting thing is that this only happens on iOS 13.0+ and on slower devices. My App doesn't use `UIWindowScenes` and I've made sure that the windows are key and active, still didn't help. Has anyone ran into this kind of a problem? 

**Steps to reproduce the behavior:**

1) Run the App using shortcut items/quick actions
2) After App is launched try authenticating the user with `OIDAuthState.authState(byPresenting: ,presenting: )` method
3) Error happens and no Safari based login form is presented

**Test device:**

Device: iPhone 8
OS: iOS 13.3
Version: AppAuth-iOS tag 1.3.0

**Comment by KoCMoHaBTa** [comment]
I have the same problem when trying to start web auth from `viewDidLoad` of my first view controller. 
If i do it from `viewDidAppear` - it works for the moment. 
It is really inconvenient at this point - you have to make sure that the app has completely launched and is on foreground.

**Comment by WilliamDenniss** [comment]
Happy to consider a patch for this issue.

**Comment by willwl** [comment]
Having the same issue. I thought the app was in background.

**Comment by kcede** [comment]
Same issue even when calling from `viewDidAppear`. Added a small delay as a workaround.

**Comment by regimaverick02** [comment]
I am still facing the same issue. Any proper solution other than adding delay out for this?
@kcede, can you show how you added the delay?

**Comment by kcede** [comment]
@regimaverick02  I wrapped the call with `DispatchQueue.main.asyncAfter()` and a few hundred milliseconds delay.

**Comment by BenSullivan-iOS** [comment]
We are still facing the same issues, is there a fix which doesn't require using `asyncAfter`?

**Comment by petea** [comment]
Might try watching for [UISceneDidActivateNotification](https://developer.apple.com/documentation/uikit/uiscenedidactivatenotification?language=objc) from the scene associated with your UIViewController's window.

**Comment by regimaverick02** [comment]
Adding a delay is sort of hack.
What i have done is subscribe to [UIApplicationDidBecomeActiveNotification](https://developer.apple.com/documentation/uikit/uiapplicationdidbecomeactivenotification) . When i get the notification, I launch the ASWebAuthenticationSession.

> @regimaverick02 I wrapped the call with `DispatchQueue.main.asyncAfter()` and a few hundred milliseconds delay.
