### ISSUE TITLE
OIDAuthState.authStateByPresentingAuthorizationRequest with presentingViewController is missing?

### ISSUE THREAD

**Issue by AndreasDolphin** [openid/AppAuth-iOS#499]
**Describe the bug**
I am implementing this library in our app and everything has been fine up til where I should initiate the OAuth flow. I'm following the documentation and [when](https://github.com/openid/AppAuth-iOS#authorizing-ios) I'm supposed to launch the auth flow using:
```
[OIDAuthState authStateByPresentingAuthorizationRequest:request
                               presentingViewController:self
                                               callback:callback];
```
I cannot find it, the only one I do find is:
```
[OIDAuthState authStateByPresentingAuthorizationRequest:request
                                      externalUserAgent:agent
                                               callback:callback];
```
**To Reproduce**
1. Create an iOS project
2. Get your hands on some OAuth service information
3. Follow this [documentation](https://github.com/openid/AppAuth-iOS)
4. At the point where you are going to authenticate, try to present the flow using a view-controller.

Note: The documentation does not mention a version of AppAuth to use, so I ran it like that, but have now specified the latest version I could see, 1.3.0 Behavior has not changed.

**Expected behavior**
I should be able to do the flow using a view-controller, as written in the documentation.

**Screenshots**
![Screenshot 2020-01-14 16 04 49](https://user-images.githubusercontent.com/22586191/72355414-b88fd280-36e7-11ea-87e5-421bcc106dd0.png)

**Desktop:**
 - OS: macOS Catalina
 - Version: 10.15.2
 - Xcode version: 11.3.1 (11C504)

**Smartphone:**
 - Device: iPhone7, iPad Mini 2
 - OS: 13.1.3, 12.4.2

**Additional context**
We have the flow already implemented on Android using AppAuth-Android, working nicely, connecting to the same OAuth service using the same endpoints, client ID, credentials etc.

**Comment by girishw** [comment]
+1 Seeing the same problem for both iOS and MacOS projects.

**Comment by julienbodet** [comment]
@AndreasDolphin How did you import AppAuth into your project?

**Comment by AndreasDolphin** [comment]
@julienbodet through the podfile `pod 'AppAuth'` then using `pod install` in the terminal. As mentioned I later repeated this specifying version 1.3.0 just to see if this issue would go away, but it did not.

**Comment by AndreasDolphin** [comment]
As I work on multiple project concurrently I have been able to do other things. Looking at this again, I tried down-grading from 1.3.0 to 1.2.0, 1.1.0, 1.0.0, 0.9.5, 0,9,2, 0.8.0, 0.4.0 and at 0.3.0 I finally saw the method I was looking for existing in `OIDAuthState.h`.

What is confusing is that it appears to exist in the current source, over [here](https://github.com/openid/AppAuth-iOS/blob/master/Source/iOS/OIDAuthState%2BIOS.h#L44). But it does not exist in the header file I get through the pod?

When I get time I'll look at including the library by other means, like a statically linked one.

**Comment by AndreasDolphin** [comment]
OK, progress has been made. I had issues getting the static library to work in our project, so I cloned and ran the example project. Doing this I noticed that it used `OIDAuthState+IOS.h` while I was using `OIDAuthState.h`.

Switching to the IOS-variant fixed my problem! So in this case I had just missed that there was a specific version of the class for IOS. Hopefully it'll stay working when we build for Catalyst 😅 

Closing this now, hopefully it can help others that bump into the same issue.

**Comment by girishw** [comment]
How can I solve this problem in Swift? I import AppAuth.

**Comment by girishw** [comment]
@AndreasDolphin Were you able to get this working on Catalyst?

**Comment by AndreasDolphin** [comment]
@girishw Just change your import like I did, to use the category `IOS`. Regarding Catalyst, I built that version just now, and it appears to be working fine 😁

**Comment by girishw** [comment]
@AndreasDolphin Did you have to do anything extra to get it working on Catalyst? The redirect is not working for me. 

I have added the URL scheme to info.plist. When I try to authorize, it opens a web view, I successfully complete the authentication and then it switches over to Safari (without opening a new tab or redirecting a website) instead of the app.  `OIDAuthState.authState(byPresenting: authorizationRequest, presenting: self)` callback is not called nor is  `application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:])
`
My scopes are [ kGTLRAuthScopeCalendarEvents,OIDScopeOpenID, OIDScopeEmail]

The same configuration works for a straight MacOS app.

**Comment by dg76** [comment]
For future users coming here: Further above AndreasDolphin says that it fixed it for him to include "OIDAuthState+IOS.h" instead of just "OIDAuthState.h". But I think it is better to just

```
#import "AppAuth.h"
```

Because inside "AppAuth.h" there is

```
#elif TARGET_OS_IOS || TARGET_OS_MACCATALYST
#import "OIDAuthState+IOS.h"
```

i.e. it takes care of this platform specific problem automatically (and it fixed the problem for me).

**Comment by shrinivas-elear** [comment]
> @AndreasDolphin Did you have to do anything extra to get it working on Catalyst? The redirect is not working for me.
> 
> I have added the URL scheme to info.plist. When I try to authorize, it opens a web view, I successfully complete the authentication and then it switches over to Safari (without opening a new tab or redirecting a website) instead of the app. `OIDAuthState.authState(byPresenting: authorizationRequest, presenting: self)` callback is not called nor is `application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) ` My scopes are [ kGTLRAuthScopeCalendarEvents,OIDScopeOpenID, OIDScopeEmail]
> 
> The same configuration works for a straight MacOS app.

Hey @girishw Did you got the solutions for this I'm facing the same issue

**Comment by girishw** [comment]
@shrinivas-elear I don't see the problem in newer versions of MacOS.
