### ISSUE TITLE
Add support for additionalParameters when refreshing token using withFreshTokensPerformAction:

### ISSUE THREAD

**Issue by ProjectLane** [openid/AppAuth-iOS#50]
Hello, 

There doesn't seem to be a way to supply additional parameter when refreshing tokens using the recommended `[OIDAuthState withFreshTokensPerformAction:]` method. 

Currently the manual way to achieve this is to obtain a request with `[OIDAuthState tokenRefreshRequestWithAdditionalParameters:]`, perform the request with `[OIDAuthorizationService performTokenRequest:callback:]`, and then update the auth state with `[OIDAuthState updateWithTokenResponse:]`. 

Doing this seems to go against the documentation to use `[OIDAuthState withFreshTokensPerformAction:]` to refresh tokens.  I just wasn't sure if there was a reason to not include a method capable of performing this action in the more preferred way. 

I've taken a stab at the functionality inside this PR: [#49](https://github.com/openid/AppAuth-iOS/pull/49)

**Comment by ProjectLane** [comment]
Forgot to mention in the initial comment that this [feature](https://github.com/openid/AppAuth-Android/blob/0.3.0/library/java/net/openid/appauth/AuthState.java#L442) currently exists inside of Android, and is solved in the same manner.

**Comment by WilliamDenniss** [comment]
Agree, let's fix this the same way as Android. Have commented in your PR.

**Comment by WilliamDenniss** [comment]
Resolved by e6acfd97ad4e132fdd99baa3191bfa07d862bc1e.
