### ISSUE TITLE
Application refused by Apple Review

### ISSUE THREAD

**Issue by JesterX666** [openid/AppAuth-iOS#505]
After migrating to version 1.3, our application just got refused by Apple Review team.

Reason :

During review, your app installed or launched executable code, which is not permitted on the App Store. Specifically, your app uses the itms-services URL scheme to install an app.

Version 1.3 uses the following code :

+ (instancetype)CustomBrowserChrome {
  // Chrome iOS documentation: https://developer.chrome.com/multidevice/ios/links
  OIDCustomBrowserURLTransformation transform = [[self class] URLTransformationSchemeSubstitutionHTTPS:@"googlechromes" HTTP:@"googlechrome"];
  NSURL *appStoreURL =
  [NSURL URLWithString:@"**itms-apps://itunes.apple.com/us/app/chrome/id535886823**"];
  return [[[self class] alloc] initWithURLTransformation:transform
                                        canOpenURLScheme:@"googlechromes"
                                             appStoreURL:appStoreURL];
}

This is urgent.  If you can fix it fast.

**Comment by JesterX666** [comment]
Duplicate #506

**Comment by shashi-kiwi** [comment]
@JesterX666 .
 I am still facing this issue. Can u pls help how you able to get approve app from Apple.
Please its urgent.
Shashi
