### ISSUE TITLE
Apple refused our application submission

### ISSUE THREAD

**Issue by JesterX666** [openid/AppAuth-iOS#506]
After migrating to version 1.3, our application just got refused by Apple Review team.

Reason :

During review, your app installed or launched executable code, which is not permitted on the App Store. Specifically, your app uses the itms-services URL scheme to install an app.

Version 1.3 uses the following code :

+ (instancetype)CustomBrowserChrome {
  // Chrome iOS documentation: https://developer.chrome.com/multidevice/ios/links
  OIDCustomBrowserURLTransformation transform = [[self class] URLTransformationSchemeSubstitutionHTTPS:@"googlechromes" HTTP:@"googlechrome"];
  NSURL *appStoreURL =
  [NSURL URLWithString:@"**itms-apps://itunes.apple.com/us/app/chrome/id535886823**"];
  return [[[self class] alloc] initWithURLTransformation:transform
                                        canOpenURLScheme:@"googlechromes"
                                             appStoreURL:appStoreURL];
}

This is urgent.  If you can fix it fast.

**Comment by WilliamDenniss** [comment]
The way to fix this is to delete `OIDExternalUserAgentIOSCustomBrowser.h` and `OIDExternalUserAgentIOSCustomBrowser.m`, assuming you're not using these (they are not used by default, so likely you are not).

You can clone AppAuth and reference it in your Podfile as a [relative path pod](https://github.com/openid/AppAuth-iOS/blob/7e0b5c100d69caac34372efdad34b22b3464ddea/Examples/Example-iOS_ObjC/Podfile#L6) (like how the samples do it), allowing you to easily delete this file.

Are there any other reports of this type of rejection? If anyone else encounters this, please add your story so we can confirm this is a general trend, and not a one-off.

**Comment by WilliamDenniss** [comment]
Discussed with @petea, a few things:

1/
If `itms-apps://` is no longer allowed (is it?) we should remove it and use a different fallback.

2/
This code isn't used by 99% of users in any case, so it probably should be moved to its own subspec, e.g. "EnterpriseUserAgents" (or removed from the podspec completely and placed in its own "UserAgentExamples" folder) 

If we go the subspec route, we can set the default like so:

default_subspec = 'ExternalUserAgent' so that this new one wouldn't be included by default.

**Comment by chrismash2** [comment]
The way I've directed users to my list of apps on the app store is with https://itunes.apple.com/gb/artist/<name>/<id>?mt=8 (can also be configured to direct to a specific app).

But I would vote for moving the agent out to the examples folder to avoid issues like this in the future

**Comment by chrismash2** [comment]
I'm interested to know how long it would take for a PR for this to make its way into a release...

**Comment by chrismash2** [comment]
This has me concerned in terms of my adoption of AppAuth as I'm not going to be the one shipping the apps. @JesterX666 at what point did apple reject you? Was it during the upload process of the submission or was it during the manual app review stage that it was rejected? I've done a test upload (that won't go to app review) and it wasn't rejected at the upload stage. Also, were you using the Chrome user agent specifically or are they rejecting it due to the presence of the code?

**Comment by WilliamDenniss** [comment]
@chrismash2 it would appear this is a one-off rejection, as we've not heard from anyone else having similar problems. Nevertheless, there is a plan in the works to move this code into a sub-spec for those who are not needing it, and changing how it works as well for those who are.

**Comment by chrismash2** [comment]
yeah, reading back the original post it does sound like they were using the enterprise-only 'install chrome' stuff in a public-facing app, so not a concern for anyone not triggering that functionality

**Comment by shashi-kiwi** [comment]
> After migrating to version 1.3, our application just got refused by Apple Review team.
> 
> Reason :
> 
> During review, your app installed or launched executable code, which is not permitted on the App Store. Specifically, your app uses the itms-services URL scheme to install an app.
> 
> Version 1.3 uses the following code :
> 
> * (instancetype)CustomBrowserChrome {
>   // Chrome iOS documentation: https://developer.chrome.com/multidevice/ios/links
>   OIDCustomBrowserURLTransformation transform = [[self class] URLTransformationSchemeSubstitutionHTTPS:@"googlechromes" HTTP:@"googlechrome"];
>   NSURL *appStoreURL =
>   [NSURL URLWithString:@"**itms-apps://itunes.apple.com/us/app/chrome/id535886823**"];
>   return [[[self class] alloc] initWithURLTransformation:transform
>   canOpenURLScheme:@"googlechromes"
>   appStoreURL:appStoreURL];
>   }
> 
> This is urgent. If you can fix it fast.

Hi Can u please tell - How you set Redirect URI for iOS App?
Thanks in advance

**Comment by petea** [comment]
I think we're all done here.  Should we close?

**Comment by shashi-kiwi** [comment]
@petea 
   When iam running pod install , i am getting 
+ (instancetype)CustomBrowserChrome {
  // Chrome iOS documentation: https://developer.chrome.com/multidevice/ios/links
  OIDCustomBrowserURLTransformation transform = [[self class] URLTransformationSchemeSubstitutionHTTPS:@"googlechromes" HTTP:@"googlechrome"];
  NSURL *appStoreURL =
  [NSURL URLWithString:@"itms-apps://itunes.apple.com/us/app/chrome/id535886823"];
  return [[[self class] alloc] initWithURLTransformation:transform
                                        canOpenURLScheme:@"googlechromes"
                                             appStoreURL:appStoreURL];
}
So finally what i have to do for not getting reject from Apple.
Please answer its urgent.
Thanks InAdvance,
Shashi

**Comment by petea** [comment]
This was fixed with #553
