### ISSUE TITLE
OIDTokenRequest.m  create JSON Request Body instead of string request body

### ISSUE THREAD

**Issue by richardli123** [openid/AppAuth-iOS#509]
**Describe the bug**
This isnt really a bug but I was wondering if it was possible to create a JSON object as the request body instead of a body string. In OIDTokenRequest.m it constructs the request body in a string but my API requires an object in the request like so. {paramName: paramValue, paramName2: paramValue2}. I dont have any prior experience with Swift/Objective C so any help with this would be greatly appreciated. 

Thank you in advance!

**Smartphone (please complete the following information):**
 - Device: iPhone simulator

**Comment by WilliamDenniss** [comment]
OIDTokenRequest is an implementation for standard RFC6749 OAuth servers. I believe we have supported that API correctly, so I don't believe this isneeded.
