### ISSUE TITLE
Dialog asking for sign-in permissions freezes my ios application without errors

### ISSUE THREAD

**Issue by marwamelfeky** [openid/AppAuth-iOS#510]
My ios application is migrated from swift 3 to swift 5 , I want to add a new feature and allow user to login with facebook and google . After adding facebook sdk and setting url schemes . The permission dialog cause my app to stop working . After pressing continue in the dialog the screen blurs with no crashes or errors . The same code works for ios 10 because the dialog doesn't appear the problem happens  with ios 12 and above.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-13 at 13 46 19](https://user-images.githubusercontent.com/4593749/74601656-4d9c3780-50a9-11ea-8c6c-2f51cf1fe0ea.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-13 at 13 46 28](https://user-images.githubusercontent.com/4593749/74601658-52f98200-50a9-11ea-986f-9d5cbf64da8b.png)

**Smartphone (please complete the following information):**
 - Device: all devices 
 - OS: 12.0 and above
 - Browser safari

**Comment by WilliamDenniss** [comment]
I've not seen this. Are you retaining the object after launching the OAuth flow? If not, do that. If so, maybe it's an Apple bug?
