### ISSUE TITLE
App is getting crashed while entering password in text field 

### ISSUE THREAD

**Issue by victorynaveen** [openid/AppAuth-iOS#511]
We are using iOS 13.3.1 version
Xcode version 11.3.1.
Once we redirecting to the safari using appAuth, Where we entering our password app is getting crashing immediately.
**Below are the crash logs**

MAIN THREAD - CRASHED

libswiftCore.dylib
swift_slowAlloc.cold.1
libswiftCore.dylib
_swift_allocObject_(swift::TargetHeapMetadata<swift::InProcess> const*, unsigned long, unsigned long)
libswiftCore.dylib
swift_allocObject
libswiftCore.dylib
function signature specialization <Arg[2] = Dead> of static Swift.__StringStorage.(create in _A317BBF16F3432B4D1DDED3E0452DA4D)(capacity: Swift.Int, countAndFlags: Swift._StringObject.CountAndFlags) -> Swift.__StringStorage
libswiftCore.dylib
Swift._StringGuts.(prepareForAppendInPlace in _408A76AB043BD3EFBAB6FAAAAA9B4914)(otherUTF8Count: Swift.Int) -> ()
libswiftCore.dylib
Swift._StringGuts.append(Swift._StringGutsSlice) -> ()
xxxxxx_MyAccount
_hidden#22792_
xxxxxx_MyAccount
_hidden#22740_ __hidden#796_:0
xxxxx_MyAccount
_hidden#5195_ __hidden#796_:0
AFNetworking
_hidden#122_ __hidden#145_:0
xxxxxxxx_MyAccount
_hidden#22759_ __hidden#796_:0
xxxxx_MyAccount
_hidden#22754_ __hidden#22894_:170
xxxxxl_MyAccount
_hidden#22775_ __hidden#796_:0
xxxxxxl_MyAccount
_hidden#22757_ __hidden#796_:0
AFNetworking
_hidden#832_ __hidden#1064_:248
libdispatch.dylib
_dispatch_call_block_and_release
xxxxxxl_MyAccount
main __hidden#794_:37
libdyld.dylib
start

**Could you please do the needful as earliest.**

**Comment by victorynaveen** [comment]
Could you please help us to get the solution as earliest

**Comment by WilliamDenniss** [comment]
This doesn't appear to be an AppAuth bug.
