### ISSUE TITLE
how to delete access token on logout from OIDAuthState.

### ISSUE THREAD

**Issue by gouravideal** [openid/AppAuth-iOS#513]
When i login by appauth. i am unable to login with other user. please tell me logout with clear access token. logout not working with my project. please help me for logout.  
@chrismessina  @dwaite @nov @jeromelebel @ve7jtb

**Comment by WilliamDenniss** [comment]
Not sure what the issue is here. To logout it the browser, the IdP needs to clear the cookie. If they support OIDC Logout, then you can use that.
