### ISSUE TITLE
support client_secret_post

### ISSUE THREAD

**Issue by jfitz1** [openid/AppAuth-iOS#516]
Support client_secret_post on request for access token in the Authorization Code flow, using OIDAuthorizationRequest and subsequently OIDTokenRequest

Currently, there is support for client_secret_basic.  client_id can be sent as a post parameter if client_secret is nil based on here: https://github.com/openid/AppAuth-iOS/blob/65ef95c6b38c7889fdda7a22f242fa0156fd43b2/Source/OIDTokenRequest.m###L277-L293

side note, we use AppAuth on Android, which has the client authentication options here:
https://github.com/openid/AppAuth-Android#utilizing-client-secrets-dangerous

warnings about client_secret in app are understood (less than ideal, no static, only dynamic).

**Comment by WilliamDenniss** [comment]
This is unnecessary as RFC 6749 mandates that servers support Basic Auth.

```
The authorization server MUST support the HTTP Basic
   authentication scheme for authenticating clients that were issued a
   client password.
```

AppAuth uses Basic Auth when the client has a secret, as allowed by RFC 6749.

**Comment by jfitz1** [comment]
thanks @WilliamDenniss  !
