### ISSUE TITLE
Updating the Apache Licence

### ISSUE THREAD

**Issue by pertau** [openid/AppAuth-iOS#523]
This just came up on checking automatically fetched licences of used libraries in our project.
It looks like copyright year and name of copyright owner is missing. 

> *APPENDIX: How to apply the Apache License to your work.
      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.
 Copyright [yyyy] [name of copyright owner]

**Comment by julienbodet** [comment]
For reference, this was discussed in [that pull request](https://github.com/openid/AppAuth-iOS/pull/332).
