### ISSUE TITLE
Issue AppAuth "invalid_grant: Bad Request"

### ISSUE THREAD

**Issue by VanMinh-sudo** [openid/AppAuth-iOS#526]
Hi everyone! 
I have used AppAuth iOS for access Google Drive, 10 days ago, everything worked fine, I could fetch files from my drive normally. But today, (I have not changed code for 10 days) I can not fetch files, it's having this issue:
Error Domain=org.openid.appauth.oauth_token Code=-10 "invalid_grant: Bad Request" UserInfo={OIDOAuthErrorResponseErrorKey={
    error = "invalid_grant";
    "error_description" = "Bad Request";
}, NSUnderlyingError=0x600000d1cdb0 {Error Domain=org.openid.appauth.remote-http Code=400 "{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}" UserInfo={NSLocalizedDescription={
  "error": "invalid_grant",
  "error_description": "Bad Request"
}}}, request=<NSMutableURLRequest: 0x6000003cdbf0> { URL: https://www.googleapis.com/drive/v3/files?fields=kind%2C%20nextPageToken%2C%20files%28id%2C%20mimeType%2C%20kind%2C%20name%2C%20webViewLink%2C%20thumbnailLink%2C%20trashed%2C%20parents%2C%20fileExtension%2C%20modifiedTime%2C%20size%29&prettyPrint=false&q=%27root%27%20IN%20parents }, NSLocalizedDescription=invalid_grant: Bad Request}

Does anyone have any solution for this issue?

**Comment by VanMinh-sudo** [comment]
[solve]I just forgot to assign auth state for GTLRDriveService.

**Comment by GokulN-stack** [comment]
> [solve]I just forgot to assign auth state for GTLRDriveService.

@VanMinh-sudo Hi, I'm stuck with the same issue. I'm using a different 3'rd party vendor that does authorization through openid. But, while getting the tokenid, I get the same "Invalid Grant" error. I see you mentioned you assigned auth state. Can you throw more light into it? Any info would be helpful. Appreciate you taking time on this.

**Comment by chetan-duke** [comment]
Any luck?
