### ISSUE TITLE
Universal Links workflow?

### ISSUE THREAD

**Issue by huseyinbagana** [openid/AppAuth-iOS#532]
Universal Links not working with redirect.

**Comment by kunwar231** [comment]
> Universal Links not working with redirect.

why did you close this issue? could you please help me, I am facing the same issue

**Comment by shobhitpuri** [comment]
@huseyinbagana Do you know if Universal Links are supported with `ASWebAuthenticationSession` webview that library uses for iOS 12+? Did you ever get it working @kunwar231 ?

**Comment by huseyinbagana** [comment]
@shobhitpuri Actually I did not use AppAuth-iOS to solve that issue. Here is my workaround solution: 

First of all, I created a static instance of **ASWebAuthenticationSession** (_callbackURLScheme should be empty string_)  and afterward I just proceed with the standard process in **ASWebAuthenticationSession**. When authSession redirects the exact universal link I just handle that in SceneDelegate and close the authSession. 
```

func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
        guard userActivity.activityType == NSUserActivityTypeBrowsingWeb,
            let incomingURL = userActivity.webpageURL,
            let components = NSURLComponents(url: incomingURL, resolvingAgainstBaseURL: true) else {
                return
        }
        
        // Check for specific URL components that you need
        guard let path = components.path,
            let params = components.queryItems else {
                return
        }
        ...
        authSession?.cancel()
        ...
        //Decode URL Parameters here
    }
```
