### ISSUE TITLE
Release 1.3.1 to cocoapods

### ISSUE THREAD

**Issue by chrismash2** [openid/AppAuth-iOS#533]
v1.3.1 doesn't appear to have been pushed to the cocoapods repo. 1.3.0 is showing as the latest available.

**Comment by chrismash2** [comment]
@julienbodet ?

**Comment by rziehl** [comment]
Bumping again. @julienbodet pushing new builds to TestFlight is getting blocked for us because of this.

**Comment by julienbodet** [comment]
@chrismash2 @rziehl 1.3.1 is now available through cocoapods.

**Comment by rziehl** [comment]
Much appreciated @julienbodet and @WilliamDenniss! Thanks a bunch!

**Comment by chrismash2** [comment]
many thanks!
