### ISSUE TITLE
If user clicks on deny error code is incorrect

### ISSUE THREAD

**Issue by Igor-Palaguta** [openid/AppAuth-iOS#56]
If user clicked on deny expected code is ```OIDErrorCodeOAuthAccessDenied```, but really have this ```OIDErrorCodeOAuthAuthorizationClientError```, as this condition always true for this case, and it changes source error:

```
  if (!OIDIsEqualIncludingNil(_request.state, response.state)) {
    NSMutableDictionary *userInfo = [query.dictionaryValue mutableCopy];
    userInfo[NSLocalizedFailureReasonErrorKey] =
        [NSString stringWithFormat:@"State mismatch, expecting %@ but got %@ in authorization "
                                    "response %@",
                                   _request.state,
                                   response.state,
                                   response];
    response = nil;
    error = [NSError errorWithDomain:OIDOAuthAuthorizationErrorDomain
                                code:OIDErrorCodeOAuthAuthorizationClientError
                            userInfo:userInfo];
  }
```

**Comment by StevenEWright** [comment]
[@WilliamDenniss To triage and decide if this is a bug.]

**Comment by WilliamDenniss** [comment]
According to [Section 4.1.2.1 of RFC](https://tools.ietf.org/html/rfc6749#section-4.1.2.1) (the Authorization Error Response), the error response MUST contain state when it was present in the request.

But, when there's an error, `response` in that code is always nil (we don't create the response object for error responses), causing the condition to be true when the request used state (as it should).

**Comment by WilliamDenniss** [comment]
`response` is really a success response only the way we implemented the API.
