### ISSUE TITLE
iOS 9 + : How can i authenticate Google Drive API using AppAuth

### ISSUE THREAD

**Issue by iAviatorJose** [openid/AppAuth-iOS#58]
Hello there,

I am able to sign in with google account using AppAuth.
But when i try to fetch list of files that i have in Google drive A/C.

I am using 'GoogleAPIClient/Drive' for Google Drive.

As i see the google drive documentation is not perfect. 
Can you suggest something about how can i go with it.?

**Comment by StevenEWright** [comment]
Could you comment on the specifics of what you've tried so far and what the results were?

The way things stand right now, I believe you'll need to create an implementation of the GTMFetcherAuthorizationProtocol protocol yourself (an implementation which would be backed by AppAuth), and provide it to the Drive API.

**Comment by WilliamDenniss** [comment]
Hi @iAviatorJose, firstly you should use [`GoogleAPIClientForREST`](https://github.com/google/google-api-objectivec-client-for-rest/) (a.k.a GTLR) and not `GoogleAPIClient` as the latter is deprecated and isn't as well supported anymore.  To authorize API calls to Google, you use GTMAppAuth which is a Google-specific extension to AppAuth designed to work with GoogleAPIClientForREST.

The `GoogleAPIClientForREST` pod is currently out of date, so reference it from master like so:

```
target 'GTMAppAuth Drive Example iOS' do
  platform :ios, '8.0'

  pod 'GTMAppAuth'
  pod 'GoogleAPIClientForREST/Drive', :git => 'https://github.com/google/google-api-objectivec-client-for-rest.git'
end
```

To help you out, I created an iOS GTMAppAuth+GoogleAPIClientForREST sample, complete with some Drive API calls which you can try out: https://github.com/WilliamDenniss/GTMAppAuthDriveExampleiOS

GoogleAPIClientForREST itself has a [macOS Drive sample](https://github.com/google/google-api-objectivec-client-for-rest/tree/master/Examples/DriveSample) which you can reference, though it's set up a little differently (not using CocoaPods for dependency management). The Drive API calls are the same on macOS and iOS, how you authorize the user and display the results differs slightly.
