### ISSUE TITLE
Swift 5.3/Xcode 12 compatibility?

### ISSUE THREAD

**Issue by johnrogers** [openid/AppAuth-iOS#587]
Hello there,

We were wondering if/when AppAuth intends to support the latest version of Xcode. Currently it is the only dependency we're waiting on to be able to target iOS 14 with our builds.

Kind regards,
John

**Comment by tkctrifork** [comment]
@johnrogers Why did you close this issue? Did you find a solution to it? I am experiencing the same problem after installing Xcode 12.
