### ISSUE TITLE
IdentityServer login notification open and close immediately in SwiftUI

### ISSUE THREAD

**Issue by MrWoWander** [openid/AppAuth-iOS#591]
I'm not really a Pro in programming for iOS, so I immediately say that I could have made a mistake somewhere

I am implementing an application on a pure SwiftUI (without UIKit), which is connected to the IdentityServer. For an example of working with AppAuth, I chose the example that was in the repository. I tried to repeat it, slightly rewriting the methods under SwiftUI and ran into the problem that when I click on the "Log in" button, an alert opens and then immediately closes. 
[Video](https://youtu.be/cXIzeiSXc7c)

The console displays a WARNING:
[Warning] Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<SFAuthenticationViewController: 0x7fad2c011a00>)

My repository: https://github.com/RTUITLab/ITLab-iOS/tree/feature/authorize/ITLab

Thank you in advance for your help

**Comment by below** [comment]
Is this still an open issue?

**Comment by MrWoWander** [comment]
> Is this still an open issue?

I made the transition from UIKit to SwiftUI myself

You can analyze the same repository that I threw above, only from the master branch

**Comment by Corgizzz** [comment]
@MrWoWander Hello Sir,
I have the same issue,
But I can't find your repository,
Can you tell me how to fix it,

Thanks!
