### ISSUE TITLE
Support "prompt" OpenID Connect auth request parameter

### ISSUE THREAD

**Issue by iainmcgin** [openid/AppAuth-iOS#6]
[OpenID Connect Core 1.0, Section 3.1.2.1](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), 
"prompt" parameter:

> OPTIONAL. Space delimited, case sensitive list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. The defined values are:
> 
> `none`
> The Authorization Server MUST NOT display any authentication or consent user interface pages. An error is returned if an End-User is not already authenticated or the Client does not have pre-configured consent for the requested Claims or does not fulfill other conditions for processing the request. The error code will typically be login_required, interaction_required, or another code defined in Section 3.1.2.6. This can be used as a method to check for existing authentication and/or consent.
> 
> `login`
> The Authorization Server SHOULD prompt the End-User for reauthentication. If it cannot reauthenticate the End-User, it MUST return an error, typically `login_required`.
> 
> `consent`
> The Authorization Server SHOULD prompt the End-User for consent before returning information to the Client. If it cannot obtain consent, it MUST return an error, typically `consent_required`.
> 
> `select_account`
> The Authorization Server SHOULD prompt the End-User to select a user account. This enables an End-User who has multiple accounts at the Authorization Server to select amongst the multiple accounts that they might have current sessions for. If it cannot obtain an account selection choice made by the End-User, it MUST return an error, typically `account_selection_required`.

**Comment by chamnap** [comment]
+1

**Comment by chamnap** [comment]
I hope this library will support `select_account` as well.

**Comment by chamnap** [comment]
@iainmcgin, What is the best way to make it work for now?

**Comment by iainmcgin** [comment]
You can always specify the prompt value as an additional parameter; direct support by the library would just be for convenience.

**Comment by WilliamDenniss** [comment]
Yes, please use the `additionalParameters` to add this param. e.g.: https://github.com/openid/AppAuth-iOS/blob/master/Source/OIDAuthorizationRequest.h#L160

**Comment by tcobbs-bentley** [comment]
@WilliamDenniss I know this was from _years_ ago, but I personally find it very aggravating that AppAuth-iOS **requires** you to use the "prompt" additional parameter, and AppAuth-Android **disallows** the use of the "prompt" additional parameter (forcing you to instead use `setPrompt` on the `AuthorizationRequest.Builder`). I realize that these two libraries are very different from each other due to OS and style constraints, but having differences like this feels like active sabotage on the part of OpenID.
