### ISSUE TITLE
Where to find logs from AppAuthRequestTrace NSLog?

### ISSUE THREAD

**Issue by postpasspost** [openid/AppAuth-iOS#619]
I'm using Flutter AppAuth and I'm trying to debug a problem I have with AppAuth-iOS.
I'm trying to get logs to show and know where to find them. I've built a CocoaPod like this:

```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'AppAuth', :git => 'https://host/repo/AppAuth-iOS'
end
```

I commented everything to have logs even if I didn't defined _APPAUTHTRACE

```
//#ifdef _APPAUTHTRACE
//#   define AppAuthRequestTrace(fmt, ...) NSLog(fmt, ##__VA_ARGS__);
//#else // _APPAUTHTRACE
//#   define AppAuthRequestTrace(...)
//#endif // _APPAUTHTRACE

// Log everything on this repo
#define AppAuthRequestTrace(fmt, ...) NSLog(fmt, ##__VA_ARGS__);
```

I would like to know where to find the logs from AppAuthRequestTrace.

**Comment by postpasspost** [comment]
I was able to find the logs in the console for the process Runner.

**Comment by fukemy** [comment]
can u find this?
