### ISSUE TITLE
SharedApplication is unavailable when adding POD

### ISSUE THREAD

**Issue by angelu25** [openid/AppAuth-iOS#621]
I'm adding native AppAuth to an iOS project via cocoa pods.
As soon as I'm adding the POD, it is failing to compile because of sharedApplication is unavailable.
![image](https://user-images.githubusercontent.com/6308120/108715451-2f1e1700-751b-11eb-9db2-23bdf0eb7862.png)

How can I solve this issue?

**Comment by below** [comment]
It appears as if you are using AppAuth in an App Extension, where UIApplication is not available.

In an extension, you can use AppAuth Core
