### ISSUE TITLE
AuthenticationResponse missing client secret while using PKCE with S256

### ISSUE THREAD

**Issue by AndyGettingAn** [openid/AppAuth-iOS#629]
Getting error "missing client_secret" when trying to authentication a user using an 'OIDExternalUserAgentIOS'.

I implemented the same task in a flutter app using the flutter wrapper 'flutter_appauth' and it executed fine without needing to specify a client_secret. Using this library the authentication only works with setting the client_secret.

Here my config:
```
let config = OIDServiceConfiguration.init(authorizationEndpoint: authorizationEndpoint, tokenEndpoint: tokenEndpoint)

let request = OIDAuthorizationRequest.init(configuration: config, clientId: client_id, scopes: scopes, redirectURL: redirectUrl, responseType: OIDResponseTypeCode, additionalParameters: nil)

let agent = OIDExternalUserAgentIOS.init(presenting: self)!

self.authState = OIDAuthState.authState(byPresenting: request, externalUserAgent: agent ) { authState, error in
  if let authState = authState {
  
  } else {
  
  }
}
```

Executing this in my ViewController.

iOS 14

Error Message: 
```
{NSLocalizedDescription={"errorCode":1,"apiError":"ParameterInvalid","errorMessage":"One or more required parameters was invalid in your API call. invalid_request, Missing parameters: client_secret","localizedMessage":"Invalid parameter(s): invalid_request, Missing parameters: client_secret"}}}}
```

What am I doing wrong? Is there any way to execute this on iOS Without needing to specify a client_secret? I looked through every issue/tutorial/documentation.

**Comment by zaphoyd** [comment]
I'm also seeing the same error. I see that this was closed without comment, was there a resolution regarding the correct way to use a PKCE flow with appauth without supplying a client secret?
