### ISSUE TITLE
Unable to login with AppStore version. Same Release build Adhoc works fine

### ISSUE THREAD

**Issue by rjfellman** [openid/AppAuth-iOS#64]
Is there any reason that the AppStore build would not behave the same as another Release build that is used for AdHoc? I'm getting this error from my authentication site's login page after submitting the credentials or continuing if the cookies are there. The difference between the two is only CodeSigning, and also being distributed via TestFlight in  #Appstore.

"The operation couldn't be completed. (org.openid.appauth.general error -5.)"

Any help is greatly appreciated!

**Comment by rjfellman** [comment]
Closing this - turns out it was not related to the library.

**Comment by klmitchell2** [comment]
@rjfellman , what was this related to? I'm receiving the same error with AppAuth.

**Comment by uguraktas** [comment]
I have same issue too
