### ISSUE TITLE
Error: The UIWindowScene for the returned window was not in the foreground active state

### ISSUE THREAD

**Issue by adiashok123** [openid/AppAuth-iOS#642]
While doing a interactive login, we are getting an error in loop, it repeatedly ask for login credentials and fails with the  same  error.

Attaching the error logs:

<Error>: MSAL-Auth: Error: Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=3 "The UIWindowScene for the returned window was not in the foreground active state." UserInfo={NSDebugDescription=The UIWindowScene for the returned window was not in the foreground active state., MSALCorrelationIDKey=XXXXXXXXXXXXXXXX}

Device : iPhone
MSAL SDK : 1.1.13
iOS Version : 14.4.2

**Comment by tichise** [comment]
This issue seems to address the same issue.

[UIWindowScene not active when running App from Shortcut Items (Home screen quick actions) · Issue #498 · openid/AppAuth-iOS](https://github.com/openid/AppAuth-iOS/issues/498)

**Comment by enterprise-support-install** [comment]
happens for me when user logs in ok, logs out, logs in again, shows webview. login ok on web, safari tries to close and VC in wrong state. But if they kill the app before loggin in again then seem to work. but not really practical.
