### ISSUE TITLE
Add support for iOS 15

### ISSUE THREAD

**Issue by XabierGoros** [openid/AppAuth-iOS#651]
Currently the library is compiled among other platforms for any iOS device. This includes compiling the framework for extensions, which we know they have their own particularities for this library. They are not able to use both `openURL` and `sharedApplication` functions of the `UIApplication` class, and the solution for it is to use AppAuthCore (there're even [some examples](https://github.com/openid/AppAuth-iOS/tree/master/Examples/Example-iOS_Swift-Carthage/Example_Extension) here).

Starting with iOS 15 and it's Swift compiler version, the library crashes when compiling to any iOS device target, in other words, the precondition of `NS_EXTENSION_UNAVAILABLE_IOS("Use view controller based solutions where appropriate instead.")` now fails to compile when it didn't before. I guess it is because the `APPLICATION_EXTENSION_API_ONLY` flag now seems to be enabled by default through SwiftPM.

What should we do to support iOS 15? I got a fork working on iOS 15 with some changes, but the main idea is to redirect those iOS Extension target consumers to use AppAuthCore. WDYT @WilliamDenniss?

**Source/AppAuth/iOS/OIDAuthState+IOS.h**

```objc
@interface OIDAuthState (IOS)

+ (id<OIDExternalUserAgentSession>)
    authStateByPresentingAuthorizationRequest:(OIDAuthorizationRequest *)authorizationRequest
                     presentingViewController:(UIViewController *)presentingViewController
callback:(OIDAuthStateAuthorizationCallback)callback NS_EXTENSION_UNAVAILABLE_IOS("Extensions are not supported by this library. Use AppAuthCore instead.");

+ (id<OIDExternalUserAgentSession>)
    authStateByPresentingAuthorizationRequest:(OIDAuthorizationRequest *)authorizationRequest
                     callback:(OIDAuthStateAuthorizationCallback)callback API_AVAILABLE(ios(11)) API_UNAVAILABLE(macCatalyst)
    __deprecated_msg("This method will not work on iOS 13. Use "
                     "authStateByPresentingAuthorizationRequest:presentingViewController:callback:") NS_EXTENSION_UNAVAILABLE_IOS("Extensions are not supported by this library. Use AppAuthCore instead.");

@end
```

**Source/AppAuth/iOS/OIDExternalUserAgentIOS.m**

```objc
 - (BOOL)presentExternalUserAgentRequest:(id<OIDExternalUserAgentRequest>)request
                                session:(id<OIDExternalUserAgentSession>)session NS_EXTENSION_UNAVAILABLE_IOS("Extensions are not supported by this library. Use AppAuthCore instead."); 
```

**Source/AppAuthEnterpriseUserAgent/iOS/OIDExternalUserAgentIOSCustomBrowser.m**

```objc
 - (BOOL)presentExternalUserAgentRequest:(nonnull id<OIDExternalUserAgentRequest>)request
                                session:(nonnull id<OIDExternalUserAgentSession>)session NS_EXTENSION_UNAVAILABLE_IOS("Extensions are not supported by this library. Use AppAuthCore instead."); 
```

**Comment by guidedways** [comment]
Got the same issue here. Xcode 13 won't compile AppAuth for an iOS project anymore when used as a module.

**Comment by jingx23** [comment]
It works again with Beta 5, they reverted the changes.

"Resolved in Xcode 13 Beta 5

You don’t need to annotate code as unavailable for use in application extensions if it references APIs annotated as unavailable for use in application extensions. This reverts a requirement that Xcode 13 Beta 3 introduced. (80615922) (FB9332020)"

https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes

**Comment by XabierGoros** [comment]
You're right @jingx23, saved by the bell. They've rolled back the changes on Beta 5, and we can still use current AppAuth releases. I've my doubts though whether we should make some changes here anyway, but that could be discussed later on.
