### ISSUE TITLE
Plans for Swift 3?

### ISSUE THREAD

**Issue by clayellis** [openid/AppAuth-iOS#67]
Are there any plans for a version of AppAuth-iOS in Swift? I understand that a lot of organizations are still waiting to support Swift. If there aren't any plans by openid to support Swift, I'd like to start a discussion to find out what the reasons behind that decision may be? I'd also like to find volunteers (of which I'd be one) who might be willing to commit some time to creating either a Swift branch or new Swift repo. I think it would make sense to start with a `swift3` branch and if it progresses enough, we could break it out into its own repo. Of course, this would duplicate efforts to introduce new enhancements, but I strongly believe that having a purely-Swift version of AppAuth-iOS would greatly increase community interest. A lot of Objective-C projects are being ignored categorically these days. 

Thoughts?

**Comment by WilliamDenniss** [comment]
What is the advantage of the library itself being in swift if you can use it in swift anyway?

I don't really like the idea that all future changes would have to be made twice. What about focusing on ensuring that it works great with swift rather than worrying about the underlying code?

**Comment by StevenEWright** [comment]
"If there aren't any plans by openid to support Swift"

I, for one, am **very** keen on supporting Swift.

@clayellis Can you think of any reason a library written in Objective-C couldn't meet some of the Swift goals you had in mind?

**Comment by Laptopmini** [comment]
+1

Now that Google has officially recommended this library to use OAuth with their services, the demand for this is only going to grow. 

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by WilliamDenniss** [comment]
#60 is fixed.

We want to make Swift a first class citizen for AppAuth, but are not porting the library.  Please file any bugs that affect your enjoyment of AppAuth with Swift!
