### ISSUE TITLE
Authorization error: invalid_request: AADSTS900144: The request body must contain the following parameter: 'client_id'.

### ISSUE THREAD

**Issue by Ankurupadhy** [openid/AppAuth-iOS#671]
Authorization error: invalid_request: AADSTS900144: The request body must contain the following parameter: 'client_id'.
Trace ID: a7990881-fed4-4781-8b5d-443fccee2f00
Correlation ID: 7deba295-06c6-46e2-8408-78a828489ec1
Timestamp: 2021-12-16 13:40:32Z - https://login.microsoftonline.com/error?code=900144

**Comment by Ankurupadhy** [comment]
it has been resolved by owner

**Comment by Maver404** [comment]
Hi @Ankurupadhy can you please provide me the solution? I'm struggling the same issue and cannot see any library updates
