### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by tcobbs-bentley** [openid/AppAuth-iOS#677]
Given how long it has been since the last release, this project *appears* to be dead. However, since the master branch did receive commits a few months ago, maybe it's not really dead.

If this project is dead, that should be announced.

If this project is **not** dead, please close this issue. However, some kind of public announcement explaining the delay would be greatly appreciated, especially in light of the fact that anyone using the project automatically gets two warnings from Xcode that cannot be disabled, and there are at least two open PRs with fixes for that problem.

I apologize for creating a bug that's not really a bug, but I am very worried about using a project that appears to be dead. The only reasons I haven't concluded that it is definitely dead are the relatively recent commits to the master branch and the fact that it comes from an organization that is still alive.

**Comment by holgerde** [comment]
There is already an [issue](https://github.com/openid/AppAuth-iOS/issues/652) discussing the state of this project.

**Comment by tcobbs-bentley** [comment]
Sorry submitting what is essentially a dupe.
