### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by elsesiy** [openid/AppAuth-iOS#71]
Hi,

as proposed for Carthage in #25 it'd be great to have support for the [Swift Package Manager](https://swift.org/package-manager/). Is that something you'd consider adding soon? Otherwise I'm happy to make the changes and submit a PR (already signed the agreement!).

Cheers!

**Comment by WilliamDenniss** [comment]
I'd love to see your PR with Swift Package Manager support. If you send one through I'll be sure to review ASAP. Thanks for signing the CLA!

**Comment by WilliamDenniss** [comment]
I see that there's no support for iOS yet. Per the [readme](https://github.com/apple/swift-package-manager) `Note that at this time the Package Manager has no support for iOS, watchOS, or tvOS platforms.`

Maybe we should just focus on the two options we currently have: CocoaPods and static-lib, plus Carthage?

**Comment by elsesiy** [comment]
@WilliamDenniss Yeah you're right. Unfortunately I discovered that after opening up the issue :/ You might want to keep it in mind though...

**Comment by WilliamDenniss** [comment]
Yep, let's revisit it when the situation changes.
