### ISSUE TITLE
Is it Possible to Place this Library within an App Extension like Packet Tunnel?

### ISSUE THREAD

**Issue by Stunner** [openid/AppAuth-iOS#729]
I have a question on if there is support for having this library be run from within an App Extension? If so is there any kind of documentation on this?

**Comment by petea** [comment]
[AppAuthCore](https://github.com/openid/AppAuth-iOS/tree/master/Source/AppAuthCore) is designed to be App Extension compatible.  There's a [Widget App Extension](https://github.com/openid/AppAuth-iOS/tree/master/Examples/Example-iOS_ObjC/Example-iOS_ObjC_Extension) in our ObjC example app that might be relevant to you.
