### ISSUE TITLE
AppAuth-iOS support for App extension

### ISSUE THREAD

**Issue by gjanblaszczyk** [openid/AppAuth-iOS#74]
Hi everyone!

I am trying to use this great library with project that has enabled app extension and there is a problem with building project because in project we have this line:
https://github.com/openid/AppAuth-iOS/blob/master/Source/iOS/OIDAuthorizationUICoordinatorIOS.m#L90
I beleave because `[UIApplication sharedApplication]` is not save to use with share extension.
Are we able to fix that? I know that same problem had in past Afnetworking library and They resolved it doing some magic with pod config...

Cheers,
GregB

**Comment by WilliamDenniss** [comment]
Not quite sure I follow what the problem is here. Are you trying to use AppAuth in an app extension, or just in a project that has an app extension?

Do you have any further information about this, e.g. the relevant discussion in AFNetworking?

**Comment by gjanblaszczyk** [comment]
Hi William,
Thanks for replay but I already resolved this problem.

**Comment by pplant** [comment]
@gjanblaszczyk hi having the same problem here. Could you briefly state how you solved the issue? Thanks in adavance

**Comment by gjanblaszczyk** [comment]
Hi @pplant , I did some changes inside the project to resolve this issue but I don't remember what exactly. Maybe you could create an issue for that and I will add some comment there.
