### ISSUE TITLE
No known class method for selector 'ASWebAuthenticationSession'

### ISSUE THREAD

**Issue by LayMui** [openid/AppAuth-iOS#751]
update  to the latest version

 "@react-native-firebase/app": "^16.5.2",

and add the following to the ios/Podfile:

target 'nativeIntegration' do
  config = use_native_modules!
  **pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true**
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change false to true and then install pods
    :hermes_enabled => false
  )

  target 'nativeIntegrationTests' do
    inherit! :complete
    # Pods for testing
  end

Enables Flipper.
Note that if you have use_frameworks! enabled, Flipper will not work and
you should disable the next line.
   use_flipper!()

 

in xcode build, 

got this build error:

SFAuthenticationSession' is deprecated: first deprecated in iOS 12.0
Replace 'alloc' with 'ASWebAuthenticationSession'
 

After replace with ASWebAuthenticationSession

it give an error

No known class method for selector 'ASWebAuthenticationSession'

**To Reproduce**
1. Update  "@react-native-firebase/app": "^16.5.2",
2. Note that react-native is using the older version of "react-native": "^0.67.1",
3. Run yarn install
4. cd ios
5. Update podfile to include
``` pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
```
and run ```pod install```
Go to xcode and build

**Expected behavior**
expected to Build succedded

**Screenshots**

**Environment**
- Device: [ e.g. iPhone 13 ios 16.2 MacBook Pro 13.1  ]
-  iOS 16.2, Mac Pro Ventura 13.1 ]
- Browser: [ .Google chrome ]

**Additional context**

**Comment by mdmathias** [comment]
I think this issue has more to do with React Native and CocoaPods than AppAuth. If you believe that this issue can be fixed in AppAuth, please reply here with more detailed reproduction steps and any kind of stacktrace that can help us debug.
