### ISSUE TITLE
Can't track the function?

### ISSUE THREAD

**Issue by tiwariammit** [openid/AppAuth-iOS#768]
I have successfully able to logout but the problem is that I can't able to track the completion of success.
Here is my complete code

` 
let authEndpoint = URL(string: Urls.Hydra.authEndpoint())!
            let tokenEndpoint = URL(string: Urls.Hydra.tokenEndpoint())!
            let redirectURL = URL(string: Urls.Hydra.redirectCallbackURL())!
            
            let logoutEndpointString = Urls.Hydra.logout() + "/?redirect_uri=" + Urls.Hydra.redirectCallbackURL()
            
            let logoutEndpoint = URL(string: logoutEndpointString)!
            
            let configuration = OIDServiceConfiguration(authorizationEndpoint: authEndpoint,
                                                        tokenEndpoint: tokenEndpoint,
                                                        issuer: nil,
                                                        registrationEndpoint: logoutEndpoint,
                                                        endSessionEndpoint: logoutEndpoint)
            
            guard let idToken = hydraAuthStateModel.idToken else {
                return
            }
            
            let request = OIDEndSessionRequest(configuration: configuration,
                                               idTokenHint: idToken,
                                               postLogoutRedirectURL: redirectURL,
                                               state: hydraAuthStateModel.state!,
                                               additionalParameters: nil)
            
            let agent = OIDExternalUserAgentIOS(presenting: viewController)
            
            OIDAuthorizationService.present(request,
                                            externalUserAgent: agent!) {response, error in
                
                if let error = error {
                    print("Authorization error: \(error.localizedDescription)")
                    return
                }

                guard let response = response else {
                    print("Authorization response is nil.")
                    return
                }

                print("Authorization response: \(response)")

                success?()
            }
`

The method 
` OIDAuthorizationService.present(request,
                                            externalUserAgent: agent!) {response, error in`
didn't trigger so, is there anyway to catch this trigger?

**Comment by grhashmi5** [comment]
Create a variable in class level like

`private var userAgent: OIDExternalUserAgentSession?`

And then assign the present closure in that agent. I mean replace this line

```
OIDAuthorizationService.present(request,
                                        externalUserAgent: agent!) {response, error in

```                                        

With
```

currentAuthorizationFlow =  OIDAuthorizationService.present(request,
                                        externalUserAgent: agent!) {response, error in
```

**Comment by tiwariammit** [comment]
Thank you for so much
