### ISSUE TITLE
Ping federate additional parameters

### ISSUE THREAD

**Issue by bhargavSrao92** [openid/AppAuth-iOS#775]
In PingFederate, are there any options to send additional parameters in the request other than authorization? This would allow us to include them in the request and receive the response token. Additionally, can we obtain the cookies, headers, and other details related to PingFederate login information from the token response?
 In the library, it states:
@param additionalParameters The client's additional authorization parameters.
Please assist me with this request as I am unable to derive any required information from it.

**Comment by mdmathias** [comment]
I think this question is more appropriate for the [PingFederate community](https://support.pingidentity.com/s/topic/0TO1W000000Q9o7WAC/pingfederate). Please reopen this issue if there is a bug that we can fix in this library.
