### ISSUE TITLE
Browser link redirection issues to app store iOS15

### ISSUE THREAD

**Issue by bryanwil17** [openid/AppAuth-iOS#778]
**Describe the bug**
Link to open app using browser will redirect to app then redirect to app's app store 

**To Reproduce**
Observable in iOS 15
1. In the mobile webview on browser, click on 'Open' in the smart banner
2. The device will redirect to the supposed app (if the app is downloaded)
3. The device will redirect again to the App Store, showing the app download page

**Expected behavior**
The button should only open the app and the respected page, without opening App Store.

**Environment**
- Device: iPhone X, XCode Simulator
- OS: iOS15
- Browser: Safari, Chrome (chrome will only open in-app App Store view)

**Comment by mdmathias** [comment]
This doesn't sound like an AppAuth issue. I think you're having an issue with your app's scheme/URL handling.

Please reopen with more detailed reproduction steps (including initial setup, etc.) if you believe the issue lies in AppAuth.
