### ISSUE TITLE
Dismiss in-app browser Safari on user action

### ISSUE THREAD

**Issue by akoskeszeg** [openid/AppAuth-iOS#78]
We are using AppAuth-iOS in our application to handle authentication. It is working fine, although we have an issue with dismiss of in-app browser Safari.

On scenario when user is prompted to save his password by Safari, the user hasn't got the time to respond.
We have created a custom class which overrides OIDAuthorizationUICoordinatorIOS's dismissAuthorizationAnimated method, although we couldn't say when 'save password alert' has been prompted or not.

Any thoughts how can we get any information when 'save password alert' has been prompted?

Thanks.

**Comment by WilliamDenniss** [comment]
What happens exactly? Does the password prompt appear but then the SFSafariViewController is closed, and the dialog disappears?

One question: normally after password entry there is a an OAuth approval page. I would expect that the user would have the option to save the password while viewing that page, before the flow completes.

**Comment by akoskeszeg** [comment]
Yes, the 'save password' option prompt but the SFSafariViewController is closed (with the dialog) immediately and the user has no time to respond. 

Currently we are using appAuth to authenticate and not for authorization so we don't have approval page. After successful authentication the controller is dismissed and the app is called via the redirect uri.

**Comment by WilliamDenniss** [comment]
I'm not sure what you can do on the AppAuth side, since you'd have no idea on whether the user was prompted, if so what action they took taken, and when.

Since the Approval page would solve this, what I'd recommend is just adding another page to the flow that instead of an approval "[accept] [deny]" button display a message like "Welcome back Bob." and a single button "[continue]".  Of course, now all users have to tap that, so you'd need to weigh that up against the benefits.

**Comment by hupendraaplite** [comment]
![Screenshot 2023-08-18 at 2 52 51 PM](https://github.com/openid/AppAuth-iOS/assets/45382984/d9f97feb-98b4-4fe8-acb2-917d50cfbbe2)
How to remove Sign in to “app name” and & Safari

**Comment by mdmathias** [comment]
This is a change Apple made to `ASWebAuthenticationSession` targeted for iOS 17. IIRC, it started to show in a recent beta (but I could be wrong). 

I'm not aware of a way to remove the middle option from the prompt here. You could use [prefersEphemeralWebBrowserSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio?language=objc), which would not show this prompt at all. The consequence here is that the user will need to sign in each time and single sign on will not work.

**Comment by hupendraaplite** [comment]
Thanks! @mdmathias 
I have removed the alert view , Now I can direct navigate to the login screen.

Reference Link: https://github.com/openid/AppAuth-iOS/issues/120#issuecomment-784235995
