### ISSUE TITLE
Unable to add AppAuth as a dependency in a SPM package

### ISSUE THREAD

**Issue by Lapinou42** [openid/AppAuth-iOS#780]
**Describe the bug**
When trying to add the AppAuth-iOS dependency to a Swift library via Swift Package Manager, I get an error stating "product 'AppAuth' required by package 'mypackage' target 'MyPackage' not found." despite the presence of AppAuth as a product in the AppAuth-iOS package definition.

**To Reproduce**
1. Create a new Swift library using Swift Package Manager (`swift package init --type library`)
2. Add .`package(url: "https://github.com/openid/AppAuth-iOS.git", from: "1.6.2")` to the dependencies in the Package.swift file.
3. Add "AppAuth" to the dependencies of the target.
    `.target(
            name: "MyPackage",
            dependencies: ["AppAuth"]
        ),`
5. Try building the library or fetching the dependencies.
6. Observe the mentioned error.

**Expected behavior**
I expect the AppAuth-iOS library to be successfully added as a dependency and to be available for use in the Swift library..

**Environment**
- Device: Any devices
- OS: iOS 16.5
- Browser: /

**Additional context**
I've noticed that AppAuth-iOS has its source files in a "Source" directory as opposed to the typical "Sources" directory. I'm not sure if this might be the root of the problem (should not). Also, I've tried referencing the library both from its GitHub URL and from a local path to try debugging but no solution found.

**Comment by mdmathias** [comment]
I think you have an issue in your `Package.swift`. I was not able to reproduce this. Take a look at this example of depending upon AppAuth-iOS in GoogleSignIn-iOS: [declaring the dependency](https://github.com/google/GoogleSignIn-iOS/blob/main/Package.swift#L43-L47), and [depending upon it in a target](https://github.com/google/GoogleSignIn-iOS/blob/main/Package.swift#L69). 

I have some screenshots below from a small sample project. This library builds fine (the warning in the second screenshot is from not doing anything with the instantiated `OIDAuthorizationRequest`).

![Screenshot 2023-08-17 at 9 55 19 AM](https://github.com/openid/AppAuth-iOS/assets/4029922/8686a247-039a-427c-8ac6-26928948f3dd)
![Screenshot 2023-08-17 at 9 58 49 AM](https://github.com/openid/AppAuth-iOS/assets/4029922/661eaf81-3f14-4199-b4d7-b9e119bfe550)

**Comment by Lapinou42** [comment]
@mdmathias Oh 😦 
My others dependencies are registered like this : 

.target( name: "MyPackage", dependencies: ["AppAuth"] )

So to fix that, just renamed like in your screenshot works ! Maybe because the name of your product is different of the name of your package… Good to know :) 

anyway, many thanks for the quick feedback ❤️

**Comment by mdmathias** [comment]
No problem!
