### ISSUE TITLE
Library not Loaded AppAuth Flutter/IOS

### ISSUE THREAD

**Issue by Ahsankhansadozai** [openid/AppAuth-iOS#781]
**Describe the bug**
When ios app build this was the stack and app stuck on splash

dyld[3655]: Library not loaded: @rpath/AppAuth.framework/AppAuth
  Referenced from: <4F5804A8-122D-32CC-A0A5-3F8F0E6652F7> /private/var/containers/Bundle/Application/721EADA5-6BA9-4430-A823-1CCDD8F72337/Runner.app/Runner
  Reason: tried: '/usr/lib/swift/AppAuth.framework/AppAuth' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AppAuth.framework/AppAuth' (no such file), '/usr/lib/swift/AppAuth.framework/AppAuth' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AppAuth.framework/AppAuth' (no such file), '/private/var/containers/Bundle/Application/721EADA5-6BA9-4430-A823-1CCDD8F72337/Runner.app/Frameworks/AppAuth.framework/AppAuth' (no such file), '/private/var/containers/Bundle/Application/721EADA5-6BA9-4430-A823-1CCDD8F72337/Runner.app/Frameworks/AppAuth.framework/AppAuth' (no such file), '/private/var/containers/Bundle/Application/721EADA5-6BA9-4430-A823-1CCDD8F72337/Runner.app/Frameworks/AppAuth.framework/AppAuth' (no such file), '/usr/lib/swift/AppAuth.framework/AppAuth' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AppAuth.framework/AppAuth' (no such file), '/usr/lib/swift/AppAuth.framework/AppAuth' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AppAuth.framework/AppAuth' (no such file), '/private/var/containers/Bundle/Application/721EADA5-6BA9-4430-A823-1CCDD8F72337/Runner.app/Frameworks/AppAuth.framework/AppAuth' (no such file), '/private/var/containers/Bundle/Application/721EADA5-6BA9-4430-A823-1CCDD8F72337/Runner.app/Frameworks/AppAuth.framework/AppAuth' (no such file), '/private/var/containers/Bundle/Application/721EADA5-6BA9-4430-A823-1CCDD8F72337/Runner.app/Frameworks/AppAuth.framework/AppAuth' (no such file), '/System/Library/Frameworks/AppAuth.framework/AppAuth' (no such file, not in dyld cache)

**Comment by mdmathias** [comment]
Sorry that you're having an issue. I don't think this is something that we can debug on the AppAuth side. Perhaps you could attach more specific reproduction steps? If it has to do with your Flutter setup, then I suggest that you file an issue with them. 

I'm going to close this for now as I don't think the issue has to do with AppAuth. Please feel free to comment here if that's not correct and I will reopen the issue if you can provide reproduction steps on the AppAuth side of things.
