### ISSUE TITLE
Google app author

### ISSUE THREAD

**Issue by WUXIN-92** [openid/AppAuth-iOS#783]
**Describe the bug**

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**

**Environment**
- Device: [ e.g. iPhone 13, MacBook Pro, etc ]
- OS: [ e.g. iOS 15, macOS 11, etc ]
- Browser: [ e.g. Safari, Chrome, etc ]

**Additional context**

**Comment by mdmathias** [comment]
I don't think this represents a bug.
