### ISSUE TITLE
There's build error for tag 1.6.2

### ISSUE THREAD

**Issue by lisafly2014** [openid/AppAuth-iOS#790]
**Describe the bug**
in the Pods/AppAuth/AppAuth.framework/Headers/AppAuthTV.h: 19.9:

#import "OIDTVAuthorizationRequest.h"

The error is "OIDTVAuthorizationRequest.h" file not found

**To Reproduce**
Just upgrade the AppAuth version to 1.6.2 in Podfile.
1. build your project
2. You will see the build error

**Expected behavior**
No build error

**Screenshots**

**Environment**
my mac OS version is MacOS Monterey Version 12.5
XCode version:  14.2

**Comment by mdmathias** [comment]
I'm running macOS Ventura 13.6, but do have Xcode 14.2. I created a tvOS example project and generated a workspace with the 

```
project 'TestTV.xcodeproj'

target 'TestTV' do
  pod 'AppAuth/TV'
  platform :tvos, '16.0'
end
```

I was able to open TestTV.xcworkspace, add `#import "OIDTVAuthorizationRequest.h"` to a file, and build and run successfully.

Please double check that your CocoaPods setup is correct. I'm closing this as not reproducible, but feel free to follow up here with further comments if you feel that there is a bug we can address.
