### ISSUE TITLE
VoiceOver not working for announcing web modal display

### ISSUE THREAD

**Issue by DylanRJ** [openid/AppAuth-iOS#800]
**Describe the bug**
Calling 
```swift
OIDAuthorizationService.present(
    _ request: OIDAuthorizationRequest,
    externalUserAgent: OIDExternalUserAgent,
    callback: @escaping OIDAuthorizationCallback
) -> OIDExternalUserAgentSession
```
Doesn't support voiceover for the presented web modal.

**To Reproduce**
1. Go to project consuming `AppAuth`
2. Enable VoiceOver on iOS device
3. Tap on UI element triggering action `OIDAuthorizationService.present(...)`
4. Notice absence of VoiceOver announcement of web modal launching

**Expected behavior**
An announcement of a web modal being displayed through VoiceOver

**Environment**
- Device: [ e.g. iPhone SE (2nd Generation ]
- OS: [ iOS 17 ]

**Additional context**

**Comment by mbernson** [comment]
Which type of `OIDExternalUserAgent` are you using when you make this method call? The external user agent is responsible for presenting the authentication UI. 
The `OIDExternalUserAgentIOS` for example, uses ASWebAuthenticationSession for this, which is fully accessible using VoiceOver.

If you expected to hear a custom UIAccessibility announcement, that is out of the scope of AppAuth and you should implement that in your app instead.

**Comment by DylanRJ** [comment]
@mbernson I believe using `OIDAuthState.authState` has resolved this issue.
The original API used, `OIDAuthorizationService.present` seems to be outdated, closing this issue.
