### ISSUE TITLE
error Missing an expected key: 'NSPrivacyCollectedDataTypes' prevents generating Apple Privacy Reports

### ISSUE THREAD

**Issue by erjsatyam** [openid/AppAuth-iOS#829]
**Describe the bug**
Hello,

regarding the [Apple Privacy Manifest file](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc), I noticed that the PrivacyInfo file was added to AppAuth to be compliant with the new guidelines; however, when I try to generate a privacy report for my app including AppAuth through xCode I receive the following errors:

Missing an expected key: 'NSPrivacyCollectedDataType' 
Missing an expected key: 'NSPrivacyCollectedDataType' 

**To Reproduce**
Steps to reproduce the behaviour:
1. Include AppAuth package dependency in the app
2. generate the archive in xCode Product->archive 
3. open the xCode organizer
4. right click on the archive version number and press 'Generate privacy report'
5. open the archived report PDF and observe

**Comment by mdmathias** [comment]
I can reproduce this issue, but I do not yet understand why it is showing. Each of the targets copy the privacy manifest into their resources ([Package.swift](https://github.com/openid/AppAuth-iOS/blob/1.7.1/Package.swift#L43-L68), [AppAuth.podspec](https://github.com/openid/AppAuth-iOS/blob/1.7.1/AppAuth.podspec#L45-L79)).

I will continue to investigate this and hope to get a patch release out fixing the issue if that's the appropriate response.

![image](https://github.com/openid/AppAuth-iOS/assets/4029922/5eb7c669-0dbf-4d7f-8837-80b69889c758)

**Comment by mdmathias** [comment]
@erjsatyam a couple of questions:

1) Out of curiosity, does your app have its own privacy manifest? I don't think that's related to this issue, but just wanted to ask.
2) Are you using SPM or CocoaPods? I wasn't able to reproduce this issue in SPM, but was able to in CocoaPods.

**Comment by mdmathias** [comment]
Please update your dependency to https://github.com/openid/AppAuth-iOS/releases/tag/1.7.2, which should address this issue.
