### ISSUE TITLE
The redirect URL doesn't seem to be called?

### ISSUE THREAD

**Issue by oliverfoggin** [openid/AppAuth-iOS#837]
**Describe the bug**
In the docs...

> Handling the Redirect
>
> The authorization response URL is returned to the app via the iOS openURL app delegate method, so you need to pipe this through to the current authorization session (created in the previous session):

I have a modern SwiftUI app that doesn't have an AppDelegate so I have implemented the `.onOpenURL` modifier for the root view. But this is never called.

**To Reproduce**
1. Create a SwiftUI app.
2. Login using this SDK following the docs.

**Expected behavior**
I would expect the `onOpenURL` function to be hit so that I can clear the auth flow.

**Environment**
- Device: iPhone 15 Pro max
- OS: iOS 17.4

**Comment by mdmathias** [comment]
You can take a look at various resources on the web to answer your SwiftUI + AppAuth questions. [This repo](https://github.com/curityio/openid-client-ios-appauth) has what seems to be a working SwiftUI solution and has an [associated tutorial](https://curity.io/resources/learn/swift-ios-appauth/). [This Stackoverflow question](https://stackoverflow.com/questions/74136960/how-to-get-oauth2-working-with-swiftui-without-wrapping-old-libraries) could also be relevant. 

Google Sign-In iOS [has a SwiftUI sample app](https://github.com/google/GoogleSignIn-iOS/blob/main/Samples/Swift/DaysUntilBirthday/Shared/DaysUntilBirthday.swift#L41) that may be helpful to look at as well.
