### ISSUE TITLE
`presentEndSessionRequest` is not accessible from Swift

### ISSUE THREAD

**Issue by oliverfoggin** [openid/AppAuth-iOS#840]
It seems that the `OIDAuthorizationService.presentEndSessionRequest` is not available from Swift.

I can see it in the docs and in the examples but it just doesn't seem to exist.

Has this been removed?

**Comment by mingyokim** [comment]
No it has not been removed. Swift code should be able to call `presentEndSessionRequest` since we didn't explicitly mark the method as unavailable in Swift (i.e. using `NS_SWIFT_UNAVAILABLE`).

**Comment by mdmathias** [comment]
I _think_ the issue may have to do with how interop is translating the ObjC methods to Swift. There are two methods in [OIDAuthorizationService.h](https://github.com/openid/AppAuth-iOS/blob/7e2c09cbeb3bb799f26c268dbedb26325ea722a9/Sources/AppAuthCore/OIDAuthorizationService.h#L128-L144) that begin with `present`, which I believe translates to a kind of overloading of Swift methods that have the same signature (but expecting different types at the first argument) for `present(_: ... )`.

Take a look at the screenshot below with pseudo code from a sample app I just made:

![image](https://github.com/openid/AppAuth-iOS/assets/4029922/0b8b0079-5769-4248-bba3-b8ad5b6e30d7)
