### ISSUE TITLE
AppAuth v1.7.4: Cocoapods warning becase new "xcconfig": { "DEFINES_MODULE": "YES" } on podspec file

### ISSUE THREAD

**Issue by pmanuelli** [openid/AppAuth-iOS#850]
Hello,

We integrate AppAuth using Cocoapods. After upgrading AppAuth to version 1.7.4 (via updating GoogleSignIn to version 7.1.0) we are getting the following warning:

```
[!] The `MyTarget` target overrides the `DEFINES_MODULE` build setting defined in `Pods/Target Support Files/Pods-base-MyProjectBase-MyProject/Pods-base-MyProjectBase-MyProject.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

Is this change intended? Maybe you wanted to use `pod_target_xcconfig` instead of `xcconfig` on the podspec file?

Thank you!

**Comment by mdmathias** [comment]
Hi! I saw the gtm-session-fetcher issue: https://github.com/google/gtm-session-fetcher/issues/389. I tried to reproduce this warning but was not able to. Out of curiosity, can you give me repro steps? Thanks!
