### ISSUE TITLE
iOS: For Client Authentication method. How can I change to "Send client credentials in body"?

### ISSUE THREAD

**Issue by hartzedstory** [openid/AppAuth-iOS#853]
Hi there, I'm new with OAuth2. After working and researching AppAuth for iOS, I wanna know the way to change the client authentication method to "Send client credentials in body"

Currently, whenever user click on Login button in my app, I would call OIDAuthorizationRequest immediately. Arguments I passed in would like:

 "OIDAuthorizationRequest(configuration: configuration,
                                              clientId: clientID,
                                              clientSecret: clientSecret,
                                              scopes: ["service"],
                                              redirectURL: URL(string: self.redirectURI)! ,
                                              responseType: OIDResponseTypeCode,
                                              additionalParameters: nil)"
                                              
I dived in Readme.md and bunch of tutorial on the internet but those are not fit to my desire. From your own experience and knowledge, could I be educated how to change to "Send client credentials in body"? Because it's working like "Send as Basic Auth header"

Thank you all and hope you always be happy

**Comment by ywsang** [comment]
Hi! Does https://github.com/openid/AppAuth-iOS/issues/276#issuecomment-410873214 provide a solution that you're looking for?

**Comment by hartzedstory** [comment]
Hi there, sorry for my late response, I didn't set notification for Gmail.

Anyway, This #276 actually works and solve my problem. You can fix by his guidance :D

Don't forget to ask BE team to create /.well-know/ API because we need configuration from server. :D
