### ISSUE TITLE
Problems loading Google's authentication website with Safari

### ISSUE THREAD

**Issue by dg76** [openid/AppAuth-iOS#86]
Thank you for developing this library! I have a question/problem that is not directly related to the library but probably to Google's servers. But maybe you have nevertheless a solution:

I am using AppAuth-iOS to sign in to Google. It seems to work fine in most cases but some users have the problem that Safari stops when loading the page. It does not only affect the SFSafariViewController but also the stand-alone Safari. The blue bar that shows the loading process just stops/freezes at a certain point and the page is not loaded. However it works fine for most users. And _it works fine when opening the same URL on the same device with Google Chrome instead of Safari_.

Have you heard about this problem? Is there a solution?

Thank you very much!

Kind regards

Dominique

**Comment by dg76** [comment]
One user today reported that Safari loads the page again and again, i.e. it looks like a redirect loop or something like that, it has not stopped loading the page. So it might be a problem of the Google login website. But it doesn't seem to happen with Google Chrome. Is anybody from Google reading this here? Do you know a solution?

Kind regards

Dominique

**Comment by WilliamDenniss** [comment]
Closing this old bug, please re-open if it's still an issue.
