### ISSUE TITLE
Error 403: disallowed _useragent

### ISSUE THREAD

**Issue by Paperboy002** [openid/AppAuth-iOS#872]
**Describe the bug**

Request details: login_hint=gary.swinton18@gmail.com
response_type=code state=ARcZ1rr-5stLZIOA09ZMrmYS-MI775r|fOZaBsciquNaXAs1aU-
aeN9Vwj09bIT8FeONNZfzk|CwHQxypDmUO7sXiDK2uS8DV
bg18XuXJqaxy7e30gnzjOplvjlpGx|JG2nZZjT1TL5Zrt|4xDoDq
3XSWxhJPGKAq22rP7aYPt1TVipARNpU_OA7QPA

redirect_uri=https://m.facebook.com/oauth2/redirect/ client id=15057814354-
80cg059cn49j6kmhhkjam4b00on1gb2n.apps.googleuserc
access_type=online scope=openid
https://www.googleapis.com/auth/userinfo.email
flowName=GeneralOAuthFlow

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**

**Environment**
- Device: [ e.g. iPhone 13, MacBook Pro, etc ]
- OS: [ e.g. iOS 15, macOS 11, etc ]
- Browser: [ e.g. Safari, Chrome, etc ]

**Additional context**

**Comment by brnnmrls** [comment]
Closing due to lack of information but feel free to reopen if issue persists with updating the description.
