### ISSUE TITLE
Auth error: State mismatch

### ISSUE THREAD

**Issue by wmcainsh** [openid/AppAuth-iOS#88]
Hi,

I've been following the links below as a basis for using AppAuth to authenticate against IdentityServer:

[https://github.com/kamaldheeraj/AppAuthSampleSwift](url)
[https://github.com/jchnxu/TestOIDAppAuth-iOS](url)

One slight difference:
- I'm using hybrid flow so my response type is "code id_token token"

When I launch the app I get my login screen and authentication looks like it is working as expected in the server logs.

When I break in the section below the url value appears to include all of the relevant info:

    func application(
        _ app: UIApplication, 
        open url: URL, 
        options: [UIApplicationOpenURLOptionsKey: Any] = [:]) -> Bool {
    
            if currentAuthorizationFlow!.resumeAuthorizationFlow(with: url){
                currentAuthorizationFlow = nil
                return true
            }
    
        return false;
    }

But when I get to the section below, authState is nil and I get the error - Auth error: State mismatch, expecting [STATE] but got (null) in authorization response (null)

    appDelegate.currentAuthorizationFlow = 
    OIDAuthState.authState(
                byPresenting: request,
                presenting: self,
                callback: {
                (authState, error) in
    
                if authState != nil{
                    self.assignAuthState(authState: authState)
                    self.logMessage("Got authorization tokens. Access token: \
    (authState!.lastTokenResponse!.accessToken!)")
                }
                else{
                    self.logMessage("Auth error: \(error!.localizedDescription)")
                    self.assignAuthState(nil)
                }
            })

I'm new to xcode / swift so probably missing something obvious. Any suggestions?

**Comment by leastprivilege** [comment]
`code id_token token` works fine in IdentityServer - have you checked the server logs if any error shows up there?

**Comment by wmcainsh** [comment]
The Url returned from IdentityServer is:

_com.mobileapp:/iphone#code=5617e67393cd6a046f184f20fea9ecb9_
_&id_token=eyJ0eXAi………….w3d55bQ_
_&token_type=Bearer_
_&expires_in=1800_
_&scope=openid%20[myapi]20offline_access_
_&state=IwSwfFsTmFnf1sdHAWOd9Vm0x1MdKnr0JOrVz1HSk98_
_&session_state=nzZMXo0Ir-_s09HeSUd6u_6_KrNDvan_dsPtrBZbLCM.fce5ad0021bb76af50d585695cf02958_

The error returned from the authState request is:

_Auth error: State mismatch, expecting IwSwfFsTmFnf1sdHAWOd9Vm0x1MdKnr0JOrVz1HSk98 but got (null) in authorization response (null)_

**Comment by leastprivilege** [comment]
That means it looks like an AppAuth issue?

**Comment by wmcainsh** [comment]
Some progress with this. If I intercept and modify the returned URI as below things start to work:

    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey: Any] = [:]) -> Bool {
        
        let myurl = URL(string: url.absoluteString.replacingOccurrences(of: "#", with: "?"))!
        
        if currentAuthorizationFlow!.resumeAuthorizationFlow(with: myurl) {
            currentAuthorizationFlow = nil
            return true
        }
        
        return false
    }

It appears that the fragmented URI is causing a problem

@leastprivilege Is there a way to prevent this in IdentityServer? Are there any potential issues with doing this?

**Comment by leastprivilege** [comment]
If you are doing code id_token token - the tokens must be behind a hash fragment. That's per spec.

**Comment by wmcainsh** [comment]
@WilliamDenniss is this a bug?

**Comment by WilliamDenniss** [comment]
AppAuth doesn't support the hybrid flow. I'm not sure why you need to use "code id_token token" instead of just "code" which will give you the access token and ID Token after the code exchange (assuming the server supports Connect and you include the "openid" scope).

The code flow is more secure for native apps as it can be protected with PKCE.

**Comment by leastprivilege** [comment]
I personally also prefer the hybrid flow (typically code id_token).

This gives you a signed protocol response (aka id_token) which includes the c_hash.
And you can combines PKCE with that as well.

**Comment by WilliamDenniss** [comment]
I guess you can use the hybrid flow if you like with the fix you applied. Can I suggest using `code id_token` and not `code id_token token`? The latter will mean you lose the benefit of PKCE protecting the access token.

We could consider official Hybrid flow support.

**Comment by Brijak0** [comment]
Hi,
I'm trying out AppAuth for OpenId connect to a mobile app we are doing and we would like to use the hybrid flow and setting response type to Id Token Code works as described above. (Identity server 4 is used as ID provider service) We gets to logon and do consent validation, but when returning to the AppAuth demo app the state value is null. If I try the same inside an internet browser it works fine. I have tried the workaround descriped by wmcainsh but the "func application" get hits upon return of the request. Do I need to set something special here? Note return url is set the plist does the bundle name need to be alike the return url?
