### ISSUE TITLE
New Maintainership?

### ISSUE THREAD

**Issue by KarlBusse** [openid/AppAuth-iOS#887]
Question:

I’m very excited and encouraged to see so much new activity lately from folks like @brnnmrls @ywsang ! Thank you so much!!

Can I ask what transpired (or what organization decided) to bring more resources and attention to this much used and highly valued project?

**Comment by brnnmrls** [comment]
Thank you for your kind words and for bringing this to our attention! I've mentioned this to our team and they were pleased to hear the excitement. As for what transpired bringing more attention to this, we've had some great team discussions about this, and we're dedicated to a more collaborative approach to keep the repository up-to-date and well-supported.
