### ISSUE TITLE
Use Google Chrome instead of Safari

### ISSUE THREAD

**Issue by dg76** [openid/AppAuth-iOS#93]
Hi!

Sometimes Safari cannot load data from "accounts.google.com", the loading bar stops and loading of the page never finishes (I have got several reports about this problem from users). This also happens when using the Safari app instead of SFSafariViewController. However on the same devices it works fine when using Google Chrome. Thus I would like to use Google Chrome if it is installed. Is there a way to tell the library to use Google Chrome instead of Safari to open the URL?

Thank you very much!

Kind regards

Dominique

**Comment by WilliamDenniss** [comment]
You *could* hack it in pretty easily.

**However**, this may run afoul of Apple's UI Guidelines. While the guidelines are not completely clear on this point, there have been [issues](https://code.google.com/p/google-plus-platform/issues/detail?id=900) in the past with using other apps during Sign-in, so I **don't recommend this**.  Unfortunately I have no further information or insight than that, nor I suspect does anyone else on this project.

Technically though, here's how it would be done:

This method:
[- (BOOL)presentAuthorizationWithURL:(NSURL *)URL session:(id<OIDAuthorizationFlowSession>)session](https://github.com/openid/AppAuth-iOS/blob/master/Source/iOS/OIDAuthorizationUICoordinatorIOS.m#L74)

1. Delete the first half that uses SFSVC.
2. Modify the URI to use the chrome scheme (replacing https:)
3. That's it.  `[[UIApplication sharedApplication] openURL:URL]` will trigger Chrome, if the URI scheme is Chrome's custom URI scheme.
