### ISSUE TITLE
kGTLRAuthScopeYouTube and unlinked accounts

### ISSUE THREAD

**Issue by jerryhalstead** [openid/AppAuth-iOS#95]
In the previous version, before AppAuth, when a user's account is identified as "unlinked" (i.e. they don't have a YouTube channel) we'd open a webview to:
https://m.youtube.com/create_channel?chromeless=1&next=/channel_creation_done

And then monitor the webview's load requests for "channel_creation_done" per these API instructions:
https://developers.google.com/youtube/create-channel

Is there a recommended way to do this with the new AppAuth? We can send them to an SFSafariViewController, but there's no way to know when they are done/successful.

This is probably a complicated design issue, but it seems really odd that when we authorize with just the kGTLRAuthScopeYouTube scope **AND** the user doesn't have a YouTube account, they are still asked if it's ok for us to "Manage your YouTube account".

**Comment by WilliamDenniss** [comment]
Hey, given this is Google-specific can you ask it again in https://github.com/google/GTMAppAuth/issues ?
