### ISSUE TITLE
Version 1.0 Release

### ISSUE THREAD

**Issue by WilliamDenniss** [openid/AppAuth-iOS#96]
List of blocking issues for version 1.0

- [x] Swift sample #19
- [x] OpenID Certified RP #18

**Comment by wilmarvh** [comment]
@WilliamDenniss Greetings!

I see both the issues you listed as blockers for 1.0.0 release are closed. Is there anything else that's standing in the way?

**Comment by WilliamDenniss** [comment]
Just qualification testing. Have you tried the 1.0 beta branch? How did it go for you?

**Comment by wilmarvh** [comment]
> Just qualification testing. Have you tried the 1.0 beta branch? How did it go for you?

Running the beta branch yes. It's a mixed experience so far:

- Users are experiencing strange cookie sharing / state issues between Safari and `ASWebAuthenticationSession`. It's hard to pin down exactly what's happening here, but I'm guessing something secure that Apple is doing is messing up our experience. One remedy for users is to authenticate on our website, thereafter on the app, where all is well again after Safari syncs a cookie with the authentication session API.
- We're seeing a high amount of crashes, as mentioned in #376, and similarly one in `[OIDExternalUserAgentIOS presentExternalUserAgentRequest:session:]`
- Other crashes inside of SafariServices, along the lines of `[SFAuthenticationViewController dismissViewControllerAnimated:completion:]`
- The strong framework link to AuthenticationServices crashes when using CocoaPods 1.6.0 and later, as mentioned in #369, so we're stuck on CP 1.5.3.

It's rolled out to a couple 100k users, most having a positive experience. But for those where it is going wrong, it's ugly.

**Comment by WilliamDenniss** [comment]
Thanks for the feedback, this is exactly what I'm looking for!

1. I think you're running into this platform issue: #227, #186 I would suggest filing a Radar to Apple, the more people they hear from that this is a problem the higher I assume they will prioritize it
2. Can you repro #376? If so can you share a test case on GitHub that I can run? The code given in that bug works fine for me.
3. I assume these are platform issues out of our control?
4. That fix was merged, will cut a release soon.

> It's rolled out to a couple 100k users, most having a positive experience. But for those where it is going wrong, it's ugly.

Glad that it's a mostly-positive experience!

**Comment by julienbodet** [comment]
1.0.0 was released: https://github.com/openid/AppAuth-iOS/tree/1.0.0
