### ISSUE TITLE
Support Connect Hybrid Flow

### ISSUE THREAD

**Issue by WilliamDenniss** [openid/AppAuth-iOS#98]
AppAuth doesn't currently support the `id_token` response type (or any other response types other than `code`).

We will likely never support `token` due to the fact it isn't protected by PKCE, and isn't recommended by the OAuth 2.0 for Native Apps BCP.

After discussing `id_token` support with @ve7jtb, we agreed that it could be possible to use `code id_token` in a secure way with AppAuth, if you validate the ID Token, verify the `c_hash`, and only use the ID Token after the code is exchanged successfully with PKCE verification.

**Comment by WilliamDenniss** [comment]
Closing this issue as Won't Fix for now, as ID Token verification is not planned for the time being.

**Comment by icistrate** [comment]
Do you mind clarifying if `code id_token` is supported or not? (I cannot test, I am from server side, but I need this info to know how I will configure native-app clients)
